### ISSUE TITLE
dmitcat_track.php returns errors

### ISSUE THREAD

**Issue by anthonypiccolo** [digitalmethodsinitiative/dmi-tcat#102]
Hey,

I just got DMI-TCAT setup on my VPS. I created my first query bin and have followed the instructions.

I have found error when I ran php dmitcat_track.php

root@anthony:/var/www/html/dmi-tcat/capture/stream# php dmitcat_track.php
PHP Warning:  require(/var/www/dmi-tcat/capture/common/tmhOAuth/tmhOAuth.php): failed to open stream: No such file or directory in /var/www/html/dmi-tcat/capture/stream/dmitcat_track.php on line 18
PHP Fatal error:  require(): Failed opening required '/var/www/dmi-tcat/capture/common/tmhOAuth/tmhOAuth.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/dmi-tcat/capture/stream/dmitcat_track.php on line 18
root@anthony:/var/www/html/dmi-tcat/capture/stream# 

How can I fix this?

Cheers,
Anthony

**Comment by ErikBorra** [comment]
Hi @anthonypiccolo,

it seems that you have not changed the `BASE_FILE` in config.php. Set it as follows:
`define('BASE_FILE', '/var/www/html/dmi-tcat/');`

Best,

Erik

**Comment by anthonypiccolo** [comment]
Thanks Erik,

That seems to have fixed that issue, but now I'm getting another error!

/var/www/html/dmi-tcat/capture/stream# php dmitcat_track.php
PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/html/dmi-tcat/common/functions.php on line 5

Do you know what could be causing this?

Cheers,
Anthony

**Comment by ErikBorra** [comment]
That's not an error but a warning. Some mysql functions will be removed in later versions of PHP. Nothing to worry about.

Best,

Erik
