### ISSUE TITLE
Query bins aren't capturing tweets

### ISSUE THREAD

**Issue by anthonypiccolo** [digitalmethodsinitiative/dmi-tcat#103]
Hey,

So far I've got everything set up perfectly. I started a few query bins but after a period of time they have no collected any tweets when they're very active hashtags.

Does anyone know what could be wrong?

Here is a screenshot: http://i.imgur.com/BRczIn5.png

**Comment by ErikBorra** [comment]
Hi @anthonypiccolo,

have you [tested the capturing scripts](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Install-Guide#test-the-capturing-scripts)? If so, what is the output of `dmi-tcat/log/controller.log` and `dmi-tcat/log/track.log`?

Best,

Erik

**Comment by anthonypiccolo** [comment]
I forgot to run controller.php! Started capturing tweets as soon as I did that. However, if I go on the analysis page nothing is being generated. For example, there is no graph. My query bin has only collected ~100 tweets so far. Does more capturing need to happen before any analysis tools can be used? Or does the bin need to be stopped? Or perhaps something else isn't right?

Thanks for helping me out with this!

Regards,
Anthony

**Comment by ErikBorra** [comment]
Note that on the analysis page the default date selection is the previous day. You can change the date parameters and increase the resolution of your graph (e.g. from days to minutes) to see what you already captured.

Don't forget to install the [crontab](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Install-Guide#install-crontab) to make sure that the controller keeps running.

**Comment by anthonypiccolo** [comment]
Okay great, changing the date fixed things.

I believe I installed the crontab, although I'm not 100% certain I did it correctly.

How can I verify that?
