### ISSUE TITLE
Possibility to change date/timezone in analysis

### ISSUE THREAD

**Issue by ErikBorra** [digitalmethodsinitiative/dmi-tcat#105]

**Comment by dentoir** [comment]
To summarize the current issue.

- A custom timezone is set in config.php, by default is was Europe/London, now UTC
- MySQL uses the system configured time by default.
- Tweets are received in UTC and UTC is inserted in the database (but not as full UTC string, in other words: without explicit timezone in the timestamp)
- So, if the system time is UTC, there will be a discrepancy in what is stored and what isn't. To correct this mistake, we have to assume it is UTC however, thus a conver_tz(created_at, 'UTC', 'whateverwewant) should always work, I think.
- The _analysis_ part assumes the timezone as set in config.php.

We need to think about how to streamline/fix this with as little code changes possible. One think we could do is to make sure we insert tweets with the created_at including the UTC timezone. MySQL should then recognize it as UTC and at least we store everything correctly (TEST: some MySQL servers need you to load timezone recognition into the database for this to work: Ubuntu 14.04?). This is a good practice, but has a drawback: historical information currently is inserted into the database as if it were UTC. Which is not always correct, but at least consistent. If we change the way we insert the data, we would lose historical consistency.

**Comment by dentoir** [comment]
Moving this to issue #197 and closing.
