### ISSUE TITLE
When exporting tweets with 'media' selected, the export does not include media URL

### ISSUE THREAD

**Issue by plodi90** [digitalmethodsinitiative/dmi-tcat#106]
In the exported .csv there is only the 'media ID' column, but no 'media URL' one, so it's not possible to see the attached images.

On the other hand when exporting 'media frequency' there is the 'media URL' only and no 'media ID'.

**Comment by ErikBorra** [comment]
In the full export, have a look at the 'followed url' column. For media it should contain the media URL.

**Comment by plodi90** [comment]
Unfortunately that column is always empty for media (if a tweet linked both a media and a URL the followed URL refers to the url only).


________________________




E   pie.lodi@gmail.comM  +31 (0)6 11 28 56 80

S   pietro.lodi

**Comment by ErikBorra** [comment]
That's a bug which we won't be able to fix this week.

**Comment by dentoir** [comment]
@plodi90 We got around to it. Could please try to git pull and see if it works for you?

**Comment by plodi90** [comment]
Hi, I’m using the online version and indeed now I get the media URL.




Thank you!


________________________




E   pie.lodi@gmail.comM  +31 (0)6 11 28 56 80

S   pietro.lodi
