### ISSUE TITLE
cannot read pid|time from [...]/track.procinfo

### ISSUE THREAD

**Issue by bornakke** [digitalmethodsinitiative/dmi-tcat#107]
Hi DMI,

TCAT is an extremely stable tool, which is one of the reasons why we are very happy using it here in Denmark. However on the 20th March we have for the first time encountered an error using the tool. The listinging stopped and we got the follow error in the log:

<code>
cannot read pid|time from [...]/track.procinfo  
cannot read pid|time from [...]/track.procinfo  
cannot read pid|time from [...]/track.procinfo  
cannot read pid|time from [...]/track.procinfo  
</code>

I can see that the error happend following a small upgrade of our server where it were shutdown and restarted, but not what let to it. I have therefore have two questions that I hope someone can help me with an answear to: 

1) Is there any easy way to recieve an email when an error is logged to the controller.log?
2) Is there any way to recover the tweets that have not been collected the last few days? We have quite a lot of different researchers using the tool and they all now seem to miss data. I know that you have a script that can collect tweets a week back in time, but I'm unsure how to run it on already existing bins? 

Thank you and thank you for building an excelent tools.

Best regards
Tobias

**Comment by dentoir** [comment]
Hi @bornakke,

1)
If you have regular 'sendmail' e-mail configured on your server, setting the $mail_to = ''; parameter in config.php should be enough to have controller.php e-mail you when there are problems. If you are using Linux, there are several tutorials on how to configure sendmail. We use msmtp - http://msmtp.sourceforge.net/
If you have shared hosting e-mail is probably set-up already and you just need to configure the address.

2)
You should be able to use the search,php script to capture Tweets backwards in time. Set the bin name to your existing bin. Set the type to track (if you are tracking keywords). Set the keywords to your keywords. Searching backwards in time has a limit, though. I'm not sure what the current limit is (it might be 2k or 10k tweets?)

From your error message it looks like a permission error occured after a system upgrade? Removing the procinfo files from the proc/ files (when tcat is not running) should resolve this issue.

Cheers,

Emile

**Comment by bornakke** [comment]
Hi Emile,

Thanks for the reply.

The thing with the email is that I already have set up a mail server (which is working) and filled in the mail_to parameter. Also I have received other emails with errors, but this one seem to have slip the email service.

I will give search.php a shot.

Best
Tobias

**Comment by bornakke** [comment]
Hi again,

I tried using search.php, but it does not find any tweets for me:

<code>The query bin 'danskpolitik' already exists. Are you sure you want to add tweets to 'danskpolitik'? (yes/no)
yes
2015-03-25 08:36:08	key: 0	remaining requests:178
0 tweets found
</code>

My setup looks like this:
<code>
$bin_name = 'danskpolitik';
$keywords = '#dkgreen, #dkøko, #dkpol, #eupol, #ftlive, #kv13, #sundpol, #trafikpol';
$type = 'track';    
</code>

**Comment by ErikBorra** [comment]
As indicated in the comments of search.php, when using the search API you need to separate the keywords by OR instead of a comma. Also, the total search string cannot be longer than 500 characters.

**Comment by bornakke** [comment]
That worked, thank you.
