### ISSUE TITLE
ERROR: user_id still set to INT rather than BIGINT in MySQL CREATE TABLE code

### ISSUE THREAD

**Issue by Snurb** [digitalmethodsinitiative/dmi-tcat#109]
Hi,

In 'follow' mode (i.e. tracking a set of user IDs), TCAT is currently unable to track any users whose IDs are above 2147483647 (the maximum value for integers), because there's an error in the code which creates the MySQL table structure for the query bins.

In dmi-tcat/capture/common/functions.php on line 301, the following change needs to be made to the create_admin() function:

    `user_id` INT NULL,

needs to change to

    `user_id` BIGINT NULL,

(since BIGINT allows for user_id values above 2147483647).

From a quick check through the rest of create_admin(), the user_id field is correctly set to BIGINT in the other MySQL table declarations, but you might want to double-check throughout...

In existing installations, manually changing the variable type for user_id in the tcat_query_bins_users from int(11) to bigint(20) - e.g. via PHPMyAdmin - fixes this issue, and allows tracking of user IDs above 2147483647.

Axel Bruns

**Comment by ErikBorra** [comment]
Thanks for tracking down that bug. Sorry for the stupid mistake. The latest commit fixes the issue.

**Comment by Snurb** [comment]
Fab, thanks for this...

**Comment by ErikBorra** [comment]
@todo reflect change in upgrade script
