### ISSUE TITLE
Script track idle for more than 600 seconds after Migration 

### ISSUE THREAD

**Issue by bornakke** [digitalmethodsinitiative/dmi-tcat#11]
After migrating to the new version we will get a email with the following content every 10 min.:

script track was idle for more than 600 seconds - killing and starting

The log is without any valuable information to what causes the error and it appears as though at least some tweets are making it into the database. First I thought it were a database error cause by heavy migration, but the entire database has been repaired and returns no errors. 

Any suggestions anyone?

Best regards
Tobias

**Comment by dormeir99o** [comment]
Hi @ErikBorra 
Where exactly in  /var/www/dmi-tcat/capture/stream/controller.php do I change IDLETIME?
is it the parameter in the "else" of this "if"? -

  if (defined('IDLETIME')) {
        $idletime = IDLETIME;
    } else {
        $idletime = 2400;
    }

Thanks,

Dor

**Comment by ErikBorra** [comment]
@dentoir could you answer this, given our recent discussions?

**Comment by dentoir** [comment]
Hi @dormeir99o 

The IDLETIME should be set in /var/www/dmi-tcat/config.php - no need to directly edit controller.php - the numeric value in controller.php is only there in case the IDLETIME value is missing from the config file!

**Comment by dormeir99o** [comment]
Thanks @dentoir for the quick response!
