### ISSUE TITLE
Depracted warning

### ISSUE THREAD

**Issue by bornakke** [digitalmethodsinitiative/dmi-tcat#111]
Does any one else experience that they are unable to turn off php deprecated warnings? 

I'm getting this warning in the top of my analysis screen:
Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in dmi-tcat/analysis/common/functions.php on line 838

I know that it is most probably a local server thing, but I just can't seem to get rid of it no matter how I set  error_reporting in php.ini. 

Best regards
Tobias

**Comment by ErikBorra** [comment]
To not display the E_DEPRECATED errors (for example) without changing the rest of the configuration :
error_reporting(error_reporting() & (-1 ^ E_DEPRECATED));

From http://php.net/manual/en/function.error-reporting.php

**Comment by bornakke** [comment]
I inserted the code in my config.php file which solved the problem :) 

Have you considered making E_ALL minus E_deprecated the standard instead of E_ALL? It seem to me that very few users would need to know of deprecated calls but that they "scare" quite a lot of the non-technical users which then send me emails asking if the service is somehow broken.

**Comment by bornakke** [comment]
And as always - thank you for the help :)

**Comment by ErikBorra** [comment]
Great idea! Just changed that in config.php.example.
