### ISSUE TITLE
Error in specific capture

### ISSUE THREAD

**Issue by bornakke** [digitalmethodsinitiative/dmi-tcat#112]
Hi TCAT,

Sorry to bugger you again. We are experiencing an error with a specific bin resulting the following warnings (and inability to access the bin). Do you have any suggestions to what this could be? It is one of the older bins in the system so I were wondering if it could be due to old database structure. All the other bins works without problems.  

Best 
Tobias

![dmi_twitter_capturing_and_analysis_toolset__dmi-tcat_](https://cloud.githubusercontent.com/assets/745051/7023563/11eade42-dd2e-11e4-9af4-87e4013c2d46.png)

**Comment by bornakke** [comment]
Exporting to network and csv yields same mistake and result in a empty file.

**Comment by psegovias** [comment]
Did u run the migrate.php ?

**Comment by bornakke** [comment]
Good point. I ran it and changed something, but it did not solve the problem. However during the process I found out that it were marked as crashed. Following this suggestion then fixed the issue:

http://stackoverflow.com/questions/8843776/mysql-table-is-marked-as-crashed-and-last-automatic-repair-failed

Thank you for the help :)
