### ISSUE TITLE
Chart View problem?

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#115]
Any ideas why i get this?

![captura de pantalla 2015-04-30 a las 11 28 16](https://cloud.githubusercontent.com/assets/5105474/7414992/7ad6b416-ef2c-11e4-9113-b1e3313b8eff.png)

**Comment by psegovias** [comment]
Another view:

![captura de pantalla 2015-04-30 a las 12 05 31](https://cloud.githubusercontent.com/assets/5105474/7415746/3bb60bb0-ef31-11e4-9e62-fcfa6c085567.png)

**Comment by ErikBorra** [comment]
Could you provide an export of the tweets for which this view is produced?

**Comment by psegovias** [comment]
https://www.dropbox.com/s/qqgzs4z26gevwok/COBRELOA-20150430090000-20150430120000--------fullExport--45cd6cf41f.csv?dl=0

**Comment by psegovias** [comment]
I get this in SQL:


![captura de pantalla 2015-04-30 a las 18 46 52](https://cloud.githubusercontent.com/assets/5105474/7423191/5af00bb0-ef69-11e4-98cf-ddc227af5cea.png)

**Comment by psegovias** [comment]
And filter to 10:00:00 to 11:00:00 

![captura de pantalla 2015-04-30 a las 18 51 53](https://cloud.githubusercontent.com/assets/5105474/7423263/14feae4e-ef6a-11e4-8d10-64fcbffa5c5b.png)


Also, linechart its OK.

![captura de pantalla 2015-04-30 a las 18 52 43](https://cloud.githubusercontent.com/assets/5105474/7423271/2652ff24-ef6a-11e4-9233-49a4ecb590da.png)

Soo weird..

**Comment by ErikBorra** [comment]
Is this related to issue #116 ?

**Comment by psegovias** [comment]
No, not related.

**Comment by psegovias** [comment]
No, not related.

**Comment by psegovias** [comment]
Another bin, recent created.

![captura de pantalla 2015-05-07 a las 9 36 12](https://cloud.githubusercontent.com/assets/5105474/7515359/a0e1b01e-f49c-11e4-8e36-7ed9164e66dd.png)


![captura de pantalla 2015-05-07 a las 9 35 38](https://cloud.githubusercontent.com/assets/5105474/7515363/a97e3e22-f49c-11e4-99ca-533d6e742a49.png)

Only hours and day have this problem, any idea?

**Comment by psegovias** [comment]
Well, i fix this changing in the SQL sentence from_user_name to from_user_id and think it's better that way.
