### ISSUE TITLE
php klout/capture.php

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#117]
Only get this:

php capture.php 

sleeping

sleeping

sleeping

sleeping

sleeping

sleeping

sleeping

sleeping

sleeping

sleeping

sleeping

It's this ok? no table created or nothing i can see.

Any idea?

**Comment by ErikBorra** [comment]
We haven't used the capturing of Klout scores in a while, so I have no recent experiences with it. 

Don't forget to define the querybins for which it should capture klout scores in https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/capture/klout/capture.php#L15

Let me know your experiences.

**Comment by psegovias** [comment]
Notice: Use of undefined constant TEST - assumed 'TEST' in /home/xxx/public_html/dashboard/capture/klout/capture.php on line 15
sleeping


PHPMYADMIN:
![captura de pantalla 2015-05-11 a las 10 38 07](https://cloud.githubusercontent.com/assets/5105474/7565871/d58ca2ee-f7c9-11e4-9509-914f6996e5b6.png)


What is the correct way to insert the BINMAE on capture.php?

**Comment by ErikBorra** [comment]
Seems like you didn't put your binname 'TEST' in quotes in the array?

**Comment by psegovias** [comment]
Now run OK :+1:  

But, its normal a loop and get inserting in table the same values every second?

**Comment by psegovias** [comment]
What about this?

https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/capture/klout/capture.php#L93-L126

**Comment by ErikBorra** [comment]
It should only redo the same user once per month, as per https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/capture/klout/capture.php#L50

https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/capture/klout/capture.php#L93-L126 has some features commented out: Klout also allows one to derive the most important topics per person, etcetera. We've commented this out as this resulted in too many extra requests to the Klout API. Feel free to uncomment it :)

**Comment by psegovias** [comment]
Thanks Erik! Works great!
