### ISSUE TITLE
Timezone in analysis interface does not reflect timezone in config.php

### ISSUE THREAD

**Issue by FlxVctr** [digitalmethodsinitiative/dmi-tcat#118]
My timezone is set in config.php to "Australia/Brisbane". This is reflected in the database as well as the times shown in the graphics in the analysis interface. But the caption still says they would be in GMT.
![2015-05-11 at 2 55 pm](https://cloud.githubusercontent.com/assets/8951994/7558708/e006ca78-f7ed-11e4-9a5c-614f9bc035e2.png)

**Comment by ErikBorra** [comment]
Thanks for pointing this out. We will fix this soon!
