### ISSUE TITLE
Silly Questions from a 'Newbie'

### ISSUE THREAD

**Issue by tomsear** [digitalmethodsinitiative/dmi-tcat#119]
Hi
My apologies if this query appears basic or ignorant.
My name is Tom Sear.
I am a PhD Student at UNSW at ADFA, Australia.
I have a humanities background and no experience in IT.
I am working on a history of the Anzac Commemoration in Australia.
Encouraged by Daryl at QUT and with assistance from my IT team I have run a dmi-tcat query and captured 200,000 tweets on Anzac.
We have created tabular outputs downloaded in excel.
How do i now use the tool that is a 'screenshot' in your FAQ to analyse these tweets.
tom.sear@student.adfa.edu.au
tomsear@gmail.com
Best.
Tom

**Comment by ErikBorra** [comment]
Hi Tom,

welcome to TCAT :) 

All different analyses and data downloads can be done by pointing your browser to the YOUR_TCAT_URL/analysis/index.php. Which FAQ 'screenshot' do you mean? 

Maybe our paper can be of help to you in understanding the system: http://www.emeraldinsight.com/doi/full/10.1108/AJIM-09-2013-0094

Best,

Erik

**Comment by tomsear** [comment]
Hi Erik

Yes has been a truly interesting , and empowering, journey so far. :)

I have to admit I am lost.

I was looking for the figure 3 in that article, and the screenshots of
tools 'tweet statistics and activity metrics' at the bottom of this page
https://github.com/digitalmethodsinitiative/dmi-tcat/wiki

I tried to point the data at that weblink which I couldn't get to work
either.

I must be doing something wrong. I am happy to go back colleagues and
helpers in  IT if this is so obvious I missing something!

Thanks and sorry of being such a bother...

Best.
Tom

**Comment by ErikBorra** [comment]
Hi Tom,

I would start by asking your technical colleagues what the web address is for the analysis interface. There you will find the info from Figure 3, as well as the 'Tweet statistics and activity metrics'.

Best,

Erik

**Comment by ErikBorra** [comment]
Hi Tom,

did you manage to do any analyses with TCAT?

Best,

Erik

**Comment by tomsear** [comment]
Dear Erik

Many thanks for your follow up! Appreciated.

Working with UNSW ADFA IT remotely managed to extract some results. However
not capable of generating complete analysis at that time.

I am just back Australia, and will shortly follow up directly. So I will
let you know how I go definitely, as I may require some additional guidance
to finalize.

Thanks again.

Best.
Tom

**Comment by ErikBorra** [comment]
Hi Tom,

note that we also have a [video tutorial](https://www.youtube.com/watch?v=ex97eoorUeo&list=PLKzQwIKtJvv9lwyYxh4708Nqo6YC6-YH4&index=6) for using the TCAT analytical modules.

Best,

Erik
