### ISSUE TITLE
How to track this?

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#121]
https://twitter.com/search?q=near%3A%22Washington%2C%20DC%22%20within%3A15mi&src=typd

near:"Washington, DC" within:15mi

Any ideas? from search  api or stream api? Can i track without a query keyword?

**Comment by psegovias** [comment]
@ErikBorra Any idea?

**Comment by psegovias** [comment]
Already did it, sorry.

**Comment by ErikBorra** [comment]
Sorry, super busy last few weeks (3 major deadlines). How did you do it?

**Comment by psegovias** [comment]
I still do not do it, but I had not seen the GeoTrack in /capture im installing the GEOS, but i think in a server with CPANEL can be very difficulty.

**Comment by psegovias** [comment]
Well i install the GEOS and geoPHP, but not tracking, any coordinates, any idea?

Im tracking this:

69.059971,55.336702,24.166809,10.963187

**Comment by dentoir** [comment]
Hi @psegovias 

You are not tracking a square from the southwest corner to the northeast corner and are most likely tracking an area which is too big as well. From Kazachstan to Sudan may cover more than 1% Twitter data and in that case Twitter will disallow your query.

Start by trying on a smaller area and remember to use longitude, latitude format if you didn't do this already. This is what Twitter expects..

Good luck!
