### ISSUE TITLE
Change search to track?

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#123]
How can i do it? or viceversa?

**Comment by ErikBorra** [comment]
In mysql, do the following:
```
ALTER TABLE tcat_query_bins SET TYPE = 'track' WHERE querybin = 'querybinname'
```
Replace `querybinname` by the name of your bin. You can also replace `track` for `search`.

**Comment by psegovias** [comment]
Nice!

**Comment by javulja** [comment]
Hy, I'm trying to do the same and I can't do it in mysql. 

`ALTER TABLE tcat_query_bins SET TYPE = 'track' WHERE querybin = 'querybinname'`

Is that exactly what I have to put to change search to track? Tanks!
