### ISSUE TITLE
Can exclude terms on track?

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#124]
I can exclude terms in track? like the search.php?

For months I did not use track, only search...

Can i use?:

Fifa,'Fifa gate' -conmebol -concacaf -uefa

**Comment by psegovias** [comment]
any help?

**Comment by ErikBorra** [comment]
Hi @psegovias, afaik [the streaming API does not allow exclude terms in track](https://dev.twitter.com/streaming/overview/request-parameters#track).

**Comment by psegovias** [comment]
:cry:
