### ISSUE TITLE
http 500 error

### ISSUE THREAD

**Issue by supersambo** [digitalmethodsinitiative/dmi-tcat#126]
Hello,
I'am having some issues with dmi-tcat's web interface, receiving http 500 errors (not seeing anything in firefox). This started when doing a git pull some time ago(about three months or so). However the tracking scripts were doing their job during the period I was not able to access the analysis interface via webbrowser.
I didn't find the time to further investigate or report this in the last months and honestly cannot fully reconstruct which git version I pulled neither which I was using before. So I did a fresh install of dmi-tcat. 

Unfortunately the problem remains and I'am not sure if this is a more general issue with my webserver configuration. The problem is that the apache error log does not provide further information but the access log reports 500 errors.
I read that those errors are often related to ownerships and rights. Here is what `ls -l` returns

    drwxr-xr-x 6 supersambo supersambo  4096 Jun 20 21:19 analysis
    drwxr-xr-x 9 supersambo supersambo   131 Jun 20 21:03 capture
    drwxr-xr-x 2 supersambo supersambo    68 Jun 20 21:03 common
    -rw-r--r-- 1 supersambo supersambo  5061 Jun 20 21:17 config.php
    -rw-r--r-- 1 supersambo supersambo  4843 Jun 20 21:03 config.php.example
    drwxr-xr-x 2 supersambo supersambo    87 Jun 20 21:03 helpers
    drwxr-xr-x 2 supersambo supersambo   115 Jun 20 21:03 import
    -rw-r--r-- 1 supersambo supersambo 10273 Jun 20 21:03 LICENSE
    drwxr-xr-x 2 www-data   supersambo     6 Jun 20 21:20 logs
    drwxr-xr-x 2 www-data   supersambo    28 Jun 29 19:19 proc
    -rw-r--r-- 1 supersambo supersambo   298 Jun 20 21:03 README.md

where `supersambo` is the user running tcat.

Any ideas? I'd really appreciate your help!

Thanks and best regards,
stephan

**Comment by psegovias** [comment]
Same thing happens to me and every time when i get last pull, and i fix it with:

chmod -R 755 folder-of-dmi-tcat/

**Comment by supersambo** [comment]
Hi, 
Thanks for this. I tried this with the user I'm runnig tcat but I get the following error
```
chmod: Beim Setzen der Zugriffsrechte für „dmi-tcat/analysis/cache“: Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für „dmi-tcat/logs“: Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für „dmi-tcat/proc“: Die Operation ist nicht erlaubt
```
(stating that I do not have the rights to change those permissions)
Doing it as root does not solve the issue either. These are the permissions in the analysis folder:
```
drwxr-xr-x 2 www-data   supersambo     6 Jun 20 21:19 cache
drwxr-xr-x 3 supersambo supersambo   149 Jun 20 21:03 common
drwxr-xr-x 3 supersambo supersambo    39 Jun 20 21:03 css
-rwxr-xr-x 1 supersambo supersambo 60695 Jun 20 21:03 index.php
-rwxr-xr-x 1 supersambo supersambo  6957 Jun 20 21:03 mod.berno.mention_graph.php
-rwxr-xr-x 1 supersambo supersambo 24997 Jun 20 21:03 mod.cascade.php
-rwxr-xr-x 1 supersambo supersambo  1844 Jun 20 21:03 mod.export_hashtags.php
-rwxr-xr-x 1 supersambo supersambo  2223 Jun 20 21:03 mod.export_mentions.php
-rwxr-xr-x 1 supersambo supersambo  1507 Jun 20 21:03 mod.export_tweet_ids.php
-rwxr-xr-x 1 supersambo supersambo  4497 Jun 20 21:03 mod.export_tweets_lang.php
-rwxr-xr-x 1 supersambo supersambo 10952 Jun 20 21:03 mod.export_tweets.php
-rwxr-xr-x 1 supersambo supersambo  2702 Jun 20 21:03 mod.export_tweets_sentiment.php
-rwxr-xr-x 1 supersambo supersambo  2291 Jun 20 21:03 mod.export_urls.php
-rwxr-xr-x 1 supersambo supersambo  5662 Jun 20 21:03 mod.hashtag_cooc.php
-rwxr-xr-x 1 supersambo supersambo  6051 Jun 20 21:03 mod.hashtag_cooc_sentiment.php
-rwxr-xr-x 1 supersambo supersambo  4763 Jun 20 21:03 mod.hashtag_user_activity.php
-rwxr-xr-x 1 supersambo supersambo  4286 Jun 20 21:03 mod.hashtag_user.php
-rwxr-xr-x 1 supersambo supersambo 65554 Jun 20 21:03 mod.hashtag_variability.php
-rwxr-xr-x 1 supersambo supersambo  3394 Jun 20 21:03 mod.hosts_hashtags.php
-rwxr-xr-x 1 supersambo supersambo 13990 Jun 20 21:03 mod.interaction_graph.php
-rwxr-xr-x 1 supersambo supersambo  2877 Jun 20 21:03 mod.lang_hashtags.php
-rwxr-xr-x 1 supersambo supersambo  2704 Jun 20 21:03 mod.media_frequency.php
-rwxr-xr-x 1 supersambo supersambo  4017 Jun 20 21:03 mod.mention_graph.php
-rwxr-xr-x 1 supersambo supersambo  6277 Jun 20 21:03 mod.mention_graph_sentiment.php
-rwxr-xr-x 1 supersambo supersambo  3356 Jun 20 21:03 mod.mention_hashtags.php
-rwxr-xr-x 1 supersambo supersambo  9897 Jun 20 21:03 mod.retweets_chain.php
-rwxr-xr-x 1 supersambo supersambo 12750 Jun 20 21:03 mod.retweet_urls.php
-rwxr-xr-x 1 supersambo supersambo 17964 Jun 20 21:03 mod.sankeymaker.php
-rwxr-xr-x 1 supersambo supersambo  2961 Jun 20 21:03 mod.sentiment_cloud.php
-rwxr-xr-x 1 supersambo supersambo  2720 Jun 20 21:03 mod.sources_hashtags.php
-rwxr-xr-x 1 supersambo supersambo  2375 Jun 20 21:03 mod.sources.stats.php
-rwxr-xr-x 1 supersambo supersambo  2375 Jun 20 21:03 mod.sources.stats.wip.php
-rwxr-xr-x 1 supersambo supersambo  6480 Jun 20 21:03 mod.trending.php
-rwxr-xr-x 1 supersambo supersambo  7029 Jun 20 21:03 mod.tweet.stats.php
-rwxr-xr-x 1 supersambo supersambo  3907 Jun 20 21:03 mod.url_hashtags.php
-rwxr-xr-x 1 supersambo supersambo  5023 Jun 20 21:03 mod.url_user.php
-rwxr-xr-x 1 supersambo supersambo  7165 Jun 20 21:03 mod.user.list.php
-rwxr-xr-x 1 supersambo supersambo  6971 Jun 20 21:03 mod.user.stats.php
-rwxr-xr-x 1 supersambo supersambo  3272 Jun 20 21:03 mod.word_frequency.php
-rwxr-xr-x 1 supersambo supersambo  2100 Jun 20 21:03 mod.word_list.php
-rwxr-xr-x 1 supersambo supersambo 73867 Jun 20 21:03 mod.word_variability.php
drwxr-xr-x 3 supersambo supersambo    84 Jun 20 21:03 scripts
-rwxr-xr-x 1 supersambo supersambo   113 Jun 20 21:09 test.php
```
btw `test.php` is a hello world script I created to test things out and it displays without any problems.

Best

**Comment by psegovias** [comment]
chmod: Beim Setzen der Zugriffsrechte für „dmi-tcat/analysis/cache“: Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für „dmi-tcat/logs“: Die Operation ist nicht erlaubt
chmod: Beim Setzen der Zugriffsrechte für „dmi-tcat/proc“: Die Operation ist nicht erlaubt


Those folder must be 777 do it after 755

**Comment by ErikBorra** [comment]
@supersambo apart from the permissions issue, it might be that with a pull request some database updates are required. Before going to http://your_server/analysis, have you gone to http://your_server/capture? When new code has been written, that sometimes does some non-intrusive upgrades to the database (which might be required by http://your_server/analysis). 

If going to http://your_server/capture (and fixing the permissions issue) does not solve the problem, you may consider running /var/www/dmi-tcat/helpers/upgrade.php.

Could you let me know which version of the software you are using (`git rev-parse master`)? That way I can ensure that such database upgrades, which are usually run via http://your_server/capture, are also done via http://your_server/analysis.

**Comment by supersambo** [comment]
Hey Erik, 
thanks a lot but this shouldn't be the problem because I did a totally new install of dmi-tcat after running into this problems. ```git rev-parse master``` returns ```34ed8cd4f12404a0220faa2315f73a69e0ae1a8e```now. ```http://my_server/capture``` throws ```Go away, you evil hacker!```which I assume to be correct.
However I'm still not sure if I managed to fix the permissions. I wasn't able to change ```logs```, ```proc``` and ```analysis/cache``` with supersambo so I had to do it with root. 
now it looks as follows:
```
supersambo@sensamb:~/www$ ls -l dmi-tcat/
insgesamt 36
drwxr-xr-x 6 supersambo supersambo  4096 Jun 20 21:19 analysis
drwxr-xr-x 9 supersambo supersambo   131 Jun 20 21:03 capture
drwxr-xr-x 2 supersambo supersambo    68 Jun 20 21:03 common
-rwxr-xr-x 1 supersambo supersambo  5061 Jun 20 21:17 config.php
-rwxr-xr-x 1 supersambo supersambo  4843 Jun 20 21:03 config.php.example
drwxr-xr-x 2 supersambo supersambo    87 Jun 20 21:03 helpers
drwxr-xr-x 2 supersambo supersambo   115 Jun 20 21:03 import
-rwxr-xr-x 1 supersambo supersambo 10273 Jun 20 21:03 LICENSE
drwxrwxrwx 2 www-data   supersambo     6 Jun 20 21:20 logs
drwxrwxrwx 2 www-data   supersambo    28 Jun 29 19:19 proc
-rwxr-xr-x 1 supersambo supersambo   298 Jun 20 21:03 README.md
```
and 
```
supersambo@sensamb:~/www$ ls -l dmi-tcat/analysis/
insgesamt 476
drwxrwxrwx 2 www-data   supersambo     6 Jun 20 21:19 cache
drwxr-xr-x 3 supersambo supersambo   149 Jun 20 21:03 common
drwxr-xr-x 3 supersambo supersambo    39 Jun 20 21:03 css
-rwxr-xr-x 1 supersambo supersambo 60695 Jun 20 21:03 index.php
-rwxr-xr-x 1 supersambo supersambo  6957 Jun 20 21:03 mod.berno.mention_graph.php
-rwxr-xr-x 1 supersambo supersambo 24997 Jun 20 21:03 mod.cascade.php
-rwxr-xr-x 1 supersambo supersambo  1844 Jun 20 21:03 mod.export_hashtags.php
-rwxr-xr-x 1 supersambo supersambo  2223 Jun 20 21:03 mod.export_mentions.php
-rwxr-xr-x 1 supersambo supersambo  1507 Jun 20 21:03 mod.export_tweet_ids.php
-rwxr-xr-x 1 supersambo supersambo  4497 Jun 20 21:03 mod.export_tweets_lang.php
-rwxr-xr-x 1 supersambo supersambo 10952 Jun 20 21:03 mod.export_tweets.php
-rwxr-xr-x 1 supersambo supersambo  2702 Jun 20 21:03 mod.export_tweets_sentiment.php
-rwxr-xr-x 1 supersambo supersambo  2291 Jun 20 21:03 mod.export_urls.php
-rwxr-xr-x 1 supersambo supersambo  5662 Jun 20 21:03 mod.hashtag_cooc.php
-rwxr-xr-x 1 supersambo supersambo  6051 Jun 20 21:03 mod.hashtag_cooc_sentiment.php
-rwxr-xr-x 1 supersambo supersambo  4763 Jun 20 21:03 mod.hashtag_user_activity.php
-rwxr-xr-x 1 supersambo supersambo  4286 Jun 20 21:03 mod.hashtag_user.php
-rwxr-xr-x 1 supersambo supersambo 65554 Jun 20 21:03 mod.hashtag_variability.php
-rwxr-xr-x 1 supersambo supersambo  3394 Jun 20 21:03 mod.hosts_hashtags.php
-rwxr-xr-x 1 supersambo supersambo 13990 Jun 20 21:03 mod.interaction_graph.php
-rwxr-xr-x 1 supersambo supersambo  2877 Jun 20 21:03 mod.lang_hashtags.php
-rwxr-xr-x 1 supersambo supersambo  2704 Jun 20 21:03 mod.media_frequency.php
-rwxr-xr-x 1 supersambo supersambo  4017 Jun 20 21:03 mod.mention_graph.php
-rwxr-xr-x 1 supersambo supersambo  6277 Jun 20 21:03 mod.mention_graph_sentiment.php
-rwxr-xr-x 1 supersambo supersambo  3356 Jun 20 21:03 mod.mention_hashtags.php
-rwxr-xr-x 1 supersambo supersambo  9897 Jun 20 21:03 mod.retweets_chain.php
-rwxr-xr-x 1 supersambo supersambo 12750 Jun 20 21:03 mod.retweet_urls.php
-rwxr-xr-x 1 supersambo supersambo 17964 Jun 20 21:03 mod.sankeymaker.php
-rwxr-xr-x 1 supersambo supersambo  2961 Jun 20 21:03 mod.sentiment_cloud.php
-rwxr-xr-x 1 supersambo supersambo  2720 Jun 20 21:03 mod.sources_hashtags.php
-rwxr-xr-x 1 supersambo supersambo  2375 Jun 20 21:03 mod.sources.stats.php
-rwxr-xr-x 1 supersambo supersambo  2375 Jun 20 21:03 mod.sources.stats.wip.php
-rwxr-xr-x 1 supersambo supersambo  6480 Jun 20 21:03 mod.trending.php
-rwxr-xr-x 1 supersambo supersambo  7029 Jun 20 21:03 mod.tweet.stats.php
-rwxr-xr-x 1 supersambo supersambo  3907 Jun 20 21:03 mod.url_hashtags.php
-rwxr-xr-x 1 supersambo supersambo  5023 Jun 20 21:03 mod.url_user.php
-rwxr-xr-x 1 supersambo supersambo  7165 Jun 20 21:03 mod.user.list.php
-rwxr-xr-x 1 supersambo supersambo  6971 Jun 20 21:03 mod.user.stats.php
-rwxr-xr-x 1 supersambo supersambo  3272 Jun 20 21:03 mod.word_frequency.php
-rwxr-xr-x 1 supersambo supersambo  2100 Jun 20 21:03 mod.word_list.php
-rwxr-xr-x 1 supersambo supersambo 73867 Jun 20 21:03 mod.word_variability.php
drwxr-xr-x 3 supersambo supersambo    84 Jun 20 21:03 scripts
-rwxr-xr-x 1 supersambo supersambo   113 Jun 20 21:09 test.php
```

Best,
stephan

**Comment by ErikBorra** [comment]
Permissions look as if TCAT should run. Is TCAT gathering data?

Are you still getting a HTTP Status Code 500? If so, make sure the Apache config is correct, as described [here](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Install-Guide#authentication-and-access).

**Comment by buethastum** [comment]
I've started having this issue as well. I hadn't been doing an upgrade or anything (though maybe I tried adding a new query from interface, can't remember precisely), and just suddenly started not seeing anything in the browser when going to /capture and /analysis. I tried upgrading tcat, but it didn't change it. However, when I ran the /commons/upgrade.php script it terminates with this error message:
```
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'twittercapture.naturvin_tweets' doesn't exist' in /var/www/html/dmi-tcat/common/upgrade.php:459
Stack trace:
#0 /var/www/html/dmi-tcat/common/upgrade.php(459): PDOStatement->execute()
#1 /var/www/html/dmi-tcat/common/upgrade.php(538): upgrades(false, true, 0, NULL)
#2 {main}
  thrown in /var/www/html/dmi-tcat/common/upgrade.php on line 459
```

**Comment by ErikBorra** [comment]
Hi @buethastum,

might it be that you have manually droped the 'naturvin' tables (naturvin_tweets, naturvin_mentions, naturvin_hashtags, etcetera), but have not deleted the corresponding entry in the table tcat_query_bins?

Best,

Erik

**Comment by buethastum** [comment]
Hi Erik

Nope. I haven't been touching the database manually. My guess is, though, that maybe something went wrong when setting up the bin through the capture page. I can try and remove the entry from the tcat_query_bins table manually, though, if I can figure out how. 

Best,
Bue

**Comment by ErikBorra** [comment]
Hi Bue,

do the following on the mysql command line:
```select * from tcat_query_bins where querybin = 'naturvin';```
Note the 'id', then do the following:
```delete from tcat_query_bins where id = PUT_ID_HERE```

**Comment by buethastum** [comment]
That made it work, yay! Thanks :)

**Comment by ErikBorra** [comment]
Awesome!
