### ISSUE TITLE
HTTP/1.1 406 Not Acceptable

### ISSUE THREAD

**Issue by oxygala** [digitalmethodsinitiative/dmi-tcat#127]
Hi,

Despite setting up DMI-TCAT succesfully on my Ubuntu 15.04 64 bit, I am not getting any stream in my query bins. After I tried all suggestions given to similar issues here, and I ran php dmitcat_track.php and php controller.php what I have in track.error.log is as below...

2015-07-22 08:54:51	stream stopped - error tmhOAuth::__set_state(array(
   'response' => 
  array (
    'raw' => 'HTTP/1.1 406 Not Acceptable
connection: close

I also tried creating a new Twitter app with different permissions, it did not make a difference.

I would be glad, if you could help. Thank you.

**Comment by dentoir** [comment]
This error will occur when tracking a very large query, which may exceed 1% of total Twitter traffic, for example large world areas or keywords such as: the, like etc.

Can you try to set up a minimal query and see whether that works?

**Comment by oxygala** [comment]
yeah, that was the problem, thanks.
