### ISSUE TITLE
Add timestamp when tweets are inserted on DB

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#130]
How i can do this? i need a timestamp when the tweets are inserted on database, any idea where i must add the code?

**Comment by ErikBorra** [comment]
Only the timestamp at which the tweet was posted is recorded in the database. It is called `created_at`.

**Comment by psegovias** [comment]
Yes i know, but i need to identify when the tweet are inserted to database, created_at only show when the tweet was created.

**Comment by ErikBorra** [comment]
We don't save that information.

**Comment by psegovias** [comment]
how i can save that? its only add a timestamp to insert, but i cant find where i must add it.

**Comment by psegovias** [comment]
@ErikBorra which file and lines, contains the function to insert tweet to database? thanks!

**Comment by ErikBorra** [comment]
Database table is created [here](https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/capture/common/functions.php#L129) (add a custom timestamp) and tweet object is assigned values [here](https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/capture/common/functions.php#L1048) (add a custom timestamp here) which are inserted via [here](https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/capture/common/functions.php#L2144-L2149) (nothing to do).

**Comment by psegovias** [comment]
I do it like this:

ALTER TABLE  `TEST_tweets` ADD  `insertedondb` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL DEFAULT NULL AFTER  `created_at` ;
ALTER TABLE  `TEST_tweets` CHANGE  `insertedondb`  `insertedondb` TIMESTAMP NOT NULL DEFAULT NOW();

**Comment by ErikBorra** [comment]
Looks good for existing bins :)

**Comment by psegovias** [comment]
Yes, and works very well!
