### ISSUE TITLE
new user, localhost

### ISSUE THREAD

**Issue by ossel1** [digitalmethodsinitiative/dmi-tcat#131]
I have installed DMT-TCAT, add query via query manager and database is filling up twitter messages.
However if I run analisys and run update overview, it does not work.
The URL becomes:
http://localhost/dmi-tcat/analysis/index.php?dataset=ISIStest&query=&url_query=&exclude=&from_user_name=&from_source=&startdate=2015-09-07&enddate=2015-09-08&whattodo=&graph_resolution=day&outputformat=csv

What do I need to put in the config php to correct this? replacing localhost with the server ip does not work.

THANKS

**Comment by ErikBorra** [comment]
Hi @ossel1,

it seems you might have misconfigured something in the [apache config](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Install-Guide#authentication-and-access) or [config.php](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Install-Guide#config). In the latter, pay specific attention to your file root (BASE_FILE) and root URL (BASE_URL).

Hope this helps,

Erik

**Comment by ossel1** [comment]
thanks! It did!
