### ISSUE TITLE
insert record when created_at doesnt exist

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#133]
I have this select statement:

SELECT * FROM (
    SELECT COUNT(t.text) as count, COUNT(DISTINCT(t.from_user_id)) as usercount, DATE_FORMAT(t.created_at,'%Y-%m-%d %H:00') datepart 
    FROM TABLE1 t WHERE t.created_at >= '2015-08-12 00:00:00' AND t.created_at <= '2015-08-13 18:30:00' 
    GROUP BY datepart) as t
    UNION ALL
    SELECT * FROM (
    SELECT COUNT(b.id) as count, COUNT(DISTINCT(b.from_user_id)) as usercount, DATE_FORMAT(b.created_at,'%Y-%m-%d %H:00') datepart 
    FROM TABLE2 b WHERE b.created_at >= '2015-08-12 00:00:00' AND b.created_at <= '2015-08-13 18:30:00'  
    GROUP BY datepart) as x GROUP BY datepart

Mysql result are this:

http://i.stack.imgur.com/gGavX.png

Im triying to view with datepart grouped but i cant, any idea what im doing wrong?

TABLE2 only have (id,from_user_id) and all are NULL except 'created_at' in this row i have entire 2015 year by day and hour, same format as TABLE1

**Comment by ErikBorra** [comment]
Dear @psegovias,

this is an SQL query formulation problem and not an issue with TCAT. This is not right place to ask such questions. Please check the mysql documentation on grouping results and joining tables. Hint: you have two different counts and only one group.

Best,

Erik

**Comment by psegovias** [comment]
Ok, sorry :cry: but im not a sql expert that's why i ask here, what do you mean with two diff counts and only one group? can u help me?

**Comment by ErikBorra** [comment]
You'll have to choose whether you want the group to count users or texts. Alternatively you can group by e.g. datepart AND users. E.g. `GROUP BY datepart, usercount`
