### ISSUE TITLE
Rename query bin?

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#134]
Can i do it directly on mysql?

**Comment by ErikBorra** [comment]
It's quite tricky. You'll have to rename all the individual tables e.g. rename_tweets, rename_hashtags, rename_mentions, etc and rename the specific table entry in tcat_query_bins.

**Comment by psegovias** [comment]
i use this:

UPDATE TABLE.tcat_query_bins SET querybin = 'NEWTABLENAME' WHERE  tcat_query_bins.id =1;
RENAME TABLE  CURRENTTABLENAME_withheld TO  NEWTABLENAME_withheld ;
RENAME TABLE  CURRENTTABLENAME_hashtags TO  NEWTABLENAME_hashtags ;
RENAME TABLE  CURRENTTABLENAME_media TO  NEWTABLENAME_media ;
RENAME TABLE  CURRENTTABLENAME_mentions TO  NEWTABLENAME_mentions ;
RENAME TABLE  CURRENTTABLENAME_places TO  NEWTABLENAME_places ;
RENAME TABLE  CURRENTTABLENAME_tweets TO  NEWTABLENAME_tweets ;
RENAME TABLE  CURRENTTABLENAME_urls TO  NEWTABLENAME_urls ;

and work fine, thanks @ErikBorra
