### ISSUE TITLE
DMI-TCAT automatic installation

### ISSUE THREAD

**Issue by dpierdet** [digitalmethodsinitiative/dmi-tcat#137]
Hello there,

Apologies for the nooby questions to come -- I'm an absolute beginner in installing Github repositories on Debian, and have been experiencing a couple of problems. I'm trying to rectify the very first steps of this installation, actually -- as I open my root Terminal on Debian (connected on LAMP, etc), insert the commands you display (curl -s "https://raw.githubusercontent...bash"), my Terminal transforms itself into a constantly scrolling, blank screen. I wonder if this is because my server needs other programs to run with it, such as git bash, or whether I should install TCAT from somewhere else. Does anyone have any thoughts on this?

Thanks in advance!

**Comment by ErikBorra** [comment]
Hi @dpierdet,

when you execute the command, your server will download and install a lot of dependencies. Your terminal will indeed scroll for a while, but it shouldn't be endless and it shouldn't be blank. Did the command finish? Did you succeed to install DMI-TCAT?

Best,

Erik

**Comment by dpierdet** [comment]
Hey Erik,

Thanks for the reply! The command didn't finish, no, and the log file doesn't reveal much, either (it doesn't include recent events -- maybe I haven't got that right, either). I'm attaching a little video I recorded of the whole phenomenon, that make more sense. 
https://youtu.be/2S58u7O3fnw
 
Thanks!

**Comment by keremyildirim** [comment]
Hey,

I have the exact same problem dpierdet mentioned. I just created this account to write this, I  am also a complete noob. I am using free tier ec2 and created a debian instance, logged in, opened the root but when I type the command, I get the exact "Passwords do not match! Please try again" error message, and then a blank screen until I press cntrl+c and quit. Looking forward for your help Erik.

Thanks a lot

**Comment by dentoir** [comment]
Hi everyone,

Thanks for the bug report. This was an error in the documentation. The documentation has been updated to start the script interactively. Hope it works for you now.

**Comment by ErikBorra** [comment]
Hi @dpierdet, @keremyildirim,

have you been able to test the modified command?

Best,

Erik

**Comment by dpierdet** [comment]
Yeeeeees! Thanks a million Erik and dentoir, I appreciate your help immensely!

**Comment by keremyildirim** [comment]
Hi, yeah it works as dpierdet said! Thank you so much!
