### ISSUE TITLE
Fatal error: Cannot redeclare dbconnect()

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#138]
Clean install:

 when i login to /capture i get this:

Fatal error: Cannot redeclare dbconnect() (previously declared in /home/xxx/public_html/xxx/common/functions.php:4) in /home/xxx/public_html/xxx/common/functions.php on line 9

Any ideas?

**Comment by ErikBorra** [comment]
Hi @psegovias,

that's a weird error. Only on line 3 of https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/common/functions.php dbconnect() is defined. Is your output the same as below, when you grep for it?

```
/home/xxx/public_html/xxx/
grep dbconnect * -riH
capture/stream/dmitcat_follow.php:dbconnect();      // connect to database @todo, rewrite mysql calls with pdo
capture/stream/dmitcat_onepercent.php:dbconnect();      // connect to database @todo, rewrite mysql calls with pdo
capture/stream/dmitcat_track.php:dbconnect();      // connect to database @todo, rewrite mysql calls with pdo
common/functions.php:function dbconnect() {
```

Best,

Erik

**Comment by psegovias** [comment]
....grep dbconnect * -riH
capture/stream/dmitcat_follow.php:dbconnect();      // connect to database @todo, rewrite mysql calls with pdo
capture/stream/dmitcat_track.php:dbconnect();      // connect to database @todo, rewrite mysql calls with pdo
capture/stream/dmitcat_onepercent.php:dbconnect();      // connect to database @todo, rewrite mysql calls with pdo
common/functions.php:function dbconnect() {....

**Comment by ErikBorra** [comment]
And when you log in to the web interface of capture, do you still get that error? It doesn't seem to be declared twice ...

**Comment by psegovias** [comment]
That error happen on web interface of capture.

**Comment by ErikBorra** [comment]
Could you attach a screenshot?

**Comment by psegovias** [comment]
![error](https://cloud.githubusercontent.com/assets/5105474/10467603/709d4408-71d9-11e5-99d2-4b1e2463c150.png)

**Comment by ErikBorra** [comment]
And you did a clean install? Unfortunately I cannot replicate this :s

What are the first 10 lines of common/functions.php?

**Comment by psegovias** [comment]
<?php

function dbconnect() {
        global $hostname,$database,$dbuser,$dbpass,$db;
        $db = mysql_connect($hostname,$dbuser,$dbpass) or die("Database error");
        mysql_select_db($database, $db);
        mysql_set_charset('utf8mb4',$db);
        mysql_query("set sql_mode='ALLOW_INVALID_DATES'");
}

**Comment by psegovias** [comment]
i do this: 

clone
create mysql and permission
create proc and logs and analysis/cache
edit config
and then try to enter /capture

**Comment by ErikBorra** [comment]
Weird. Those 10 lines only mention dbconnect once. Maybe try our new [automatic installation script](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Install-Guide)?

**Comment by psegovias** [comment]
Im running centos 6, btw i try a OLD index.php from /capture and no problem, create the tcat_ databases, but i can only login with that index, not the updated one.

**Comment by psegovias** [comment]
I use this one: http://pastebin.com/aZf1aRqa

**Comment by psegovias** [comment]
![errro2](https://cloud.githubusercontent.com/assets/5105474/10468101/f721bee4-71db-11e5-9155-ff1ba225ded3.png)

**Comment by ErikBorra** [comment]
Hi @psegovias,

still not sure why you get the dbconnect() redeclared. The screenshot, however, indicates that you have disabled javascript, is that correct? TCAT requires javascript to render graphs, ask for cut-of options, and to show/hide specific information for specific selections.

Best,

Erik

**Comment by psegovias** [comment]
im not disabled javascript, only remove the line with admin password request (go away evil hacker)

**Comment by psegovias** [comment]
Any idea @ErikBorra ? or miss something on install?

**Comment by psegovias** [comment]
I think this is the problem: 

include_once BASE_FILE . '/common/upgrade.php';

when i committ no error show.

Any ideas?

**Comment by psegovias** [comment]
Why upgrade.php include again this files?


if (php_sapi_name() == 'cli' || php_sapi_name() == 'cgi-fcgi') {
    include_once("../config.php");
    include "functions.php";
    include "../capture/common/functions.php";
}

**Comment by dentoir** [comment]
The upgrade.php is called to check whether or not an upgrade is available or may be required.

In your case, it seems like common/upgrade.php assumes you are running from the command-line, even when you are running on a webserver. It includes common/functions.php for the second time and causes the error.

Can you verify by putting somewhere on top of your capture/index.php this line:

    echo php_sapi_name(); exit();

As this same test is used elsewhere in the code, we should fix it for CentOS.

**Comment by psegovias** [comment]
echo php_sapi_name(); exit();
    cgi-fcgi

**Comment by dentoir** [comment]
This should now be fixed with the latest commit. We have improved CLI environment detection due to php_sapi_name() limitations discussed here: http://php.net/manual/en/function.php-sapi-name.php

**Comment by psegovias** [comment]
Works perfect! 

Thanks guys!
