### ISSUE TITLE
Search sometimes fails to create new bin.

### ISSUE THREAD

**Issue by danielcarter** [digitalmethodsinitiative/dmi-tcat#140]
I'm finding that the search script sometimes fails to complete. This isn't a huge problem except the first time you run a search, it also needs to create the query bin, and if the bin isn't created, you can't access the data through the analysis interface or delete the bin through the capture interface. This is my understanding, at least. 

I've temporarily fixed the issue by moving the following line in search.php to above the search function (search($keywords);):

queryManagerCreateBinFromExistingTables($bin_name, $querybin_id, $type, explode("OR", $keywords));

This creates the bin before the search function can fail.

**Comment by ErikBorra** [comment]
Hi @danielcarter,

thanks for reporting this issue. Your suggested solution is sensible and we will update all those capture scripts accordingly.

Best,

Erik

**Comment by dentoir** [comment]
Thanks for the issue report! I've pushed the fix.
