### ISSUE TITLE
collection stops if time on server drifts out of valid range

### ISSUE THREAD

**Issue by brendam** [digitalmethodsinitiative/dmi-tcat#142]
Using the track option the dmi-tcat server stops gathering data if the server date time gets out of the range that Twitter will accept for authentication.  An error email report would be helpful if this happens (and error email address is set).

**Comment by ErikBorra** [comment]
Hi @brendam,

thanks for this useful suggestion. We will add it to the wish list (but are unfortunately pressed for time before the holiday breaks). We of course do encourage pull requests :)

Best,

ERik

**Comment by hoylen** [comment]
An interim work-around for the time-drift problem would be to run an NTP client on the host -- to ensure the server's clock remains correct.

Do we know why the clock becomes incorrect? With OpenStack/KVM virtual machines, "suspend" or "pause" does different things to the clock. I can't remember which exactly, but with one the clock is correct after resumption and with the other the clock is behind (by the duration it was off-line). If the virtual machine was simply rebooted, it should regain the correct time when it is booted.

Note: the email notification feature would still be a useful feature: for situations where the capturing stops for some other reason.

**Comment by brendam** [comment]
We do run ntp on our servers now. But when i started ntp wasn't being installed and the time on some of the servers had got out of range of Twitter and stopped collecting without us knowing. The request should probably be that dmi-tcat reports if Twitter authorisation fails.

**Comment by ErikBorra** [comment]
This has been fixed in the newer install scripts.
