### ISSUE TITLE
Problem w. dmitcat_track.php and controller.php

### ISSUE THREAD

**Issue by mhockenhull** [digitalmethodsinitiative/dmi-tcat#147]
Dear TCAT-crew, 

I've installed TCAT on my ubuntu server, and have gotten it running (query is tracking tweets). However, per the installation instructions I am trying to run dmitcat_track.php and controller.php. Every time I get the following error messages: 

PHP Warning:  fopen(/var/www/cadm.dk/dmi-tcat-master/proc/controller.lock): failed to open stream:    Permission denied in /var/www/cadm.dk/dmi-tcat-master/capture/common/functions.php on line 428
PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/cadm.dk/dmi-tcat-master/capture/common/functions.php on line 430
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/cadm.dk/dmi-tcat-master/capture/common/functions.php on line 442
PHP Warning:  file_put_contents(/var/www/cadm.dk/dmi-tcat-master/logs/controller.log): failed to open stream: Permission denied in /var/www/cadm.dk/dmi-tcat-master/capture/common/functions.php on line 452

Both proc and logs are set to owner www-data and chmod 755. It's not technically a problem since I'm getting tweets done, but I'd like for the installation to be done properly. Hope you can help!

Best, 
Michael

**Comment by dentoir** [comment]
The problem is likely that your proc and logs directory may not be owned by the same user as the cronjob user. You should either run the cron-job as user www-data, or chmod the proc/ and logs/ directory to the appropriate user.

**Comment by mhockenhull** [comment]
Thanks for the reply. 

Hmm, both the cronjob and proc/ + logs/ are owned by www-data. 

But the message doesn't occur in relation to the cronjob, but when I run controller.php and dmitcat_track.php from the command line, to test them. And when running them I am using `sudo -H -u www-data php dmitcat_track.php` to make sure they run as www-data. I have also tried running `php dmitcat_track.php` with my own user and with sudo, in which case nothing happens.

**Comment by dentoir** [comment]
That looks like the right invocation and the right user. Perhaps you have run the controller.php and dmi_track.php in the past under a different user (such as root or any other) and the lockfiles have been created under that user and can no longer be deleted now?

Can you see if a file called /var/www/cadm.dk/dmi-tcat-master/proc/controller.lock already exists, and if so, who owns it?

Deleting the files under proc/ (and afterwards restarting your tracking process) should be safe.

**Comment by mhockenhull** [comment]
controller.lock did exist, but was owned by my user (but not www-data). I have run the scripts in the past as sudo, if that makes a difference. I deleted all the files from proc, and re-ran the php scripts. Now the proc files are owned by www-data. But I still got the same error messages when running the scripts: 

```
michh@ethoslab:/var/www/cadm.dk/dmi-tcat-master/capture/stream$ php controller.php
PHP Warning:  fopen(/var/www/cadm.dk/dmi-tcat-master/proc/controller.lock): failed to open stream: Permission denied in /var/www/cadm.dk/dmi-tcat-master/capture/common/functions.php on line 428
PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/cadm.dk/dmi-tcat-master/capture/common/functions.php on line 430
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/cadm.dk/dmi-tcat-master/capture/common/functions.php on line 442
```

and

```
michh@ethoslab:/var/www/cadm.dk/dmi-tcat-master/capture/stream$ php dmitcat_track.php
PHP Warning:  fopen(/var/www/cadm.dk/dmi-tcat-master/proc/track.lock): failed to open stream: Permission denied in /var/www/cadm.dk/dmi-tcat-master/capture/common/functions.php on line 428
PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/cadm.dk/dmi-tcat-master/capture/common/functions.php on line 430
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/cadm.dk/dmi-tcat-master/capture/common/functions.php on line 442
´´´

**Comment by dentoir** [comment]
Hi @mhockenhull 

Sorry this ticket slipped from my attention. SInce your proc/ directory is owned by www-data, you should either use sudo if you want to run from the command-line, or change the ownership/permissions of your proc/ directory so both you and the user can write to the same directory. For example, to make them part of the same Unix group.

The best/simplest procedure is to have the shell user and the crontab user to be always the same user and own the proc/ and logs/ directory, while the webserver user (usually www-data) should own analysis/cache to write its files.

**Comment by mhockenhull** [comment]
No worries at all. :)
Now my setup has www-data owning the proc/, logs/ and analysis/cache as you said, and also running controller.php in the crontab. It seems like everything is running, so I think the issue can be closed. 

Thank you for the help!
