### ISSUE TITLE
Mention Network Export is not formatted as directed graph

### ISSUE THREAD

**Issue by seakha** [digitalmethodsinitiative/dmi-tcat#157]
Under Network Exports, social graph by mentions claims that it produces directed graph; however, the exported .gdf file is undirected. The 'directed BOOLEAN' column is missing in the output file.

**Comment by dentoir** [comment]
Hi @seakha 

The directed attribute is set in the edgedef section, not the nodedef section. I believe this is correct, as per the GUESS specification?

http://graphexploration.cond.org/manual.html

**Comment by dentoir** [comment]
I think the current definition structure is correct, therefore I am closing this issue.
