### ISSUE TITLE
1% limit with two (or more) DMI-Tcats

### ISSUE THREAD

**Issue by jaruizso** [digitalmethodsinitiative/dmi-tcat#158]
Hi,

I am aware of 1% Twitter limitation. My question, which I could not find at the Twitter documentation, is that if that limitation is per app, or per Twitter user.

For example, I have running two servers, in each one of them I installed DMI-Tcat, and each one of them making use of different Twitter app, but from the same account (mine). In one of them I have 3 keywords not very highly used. In the other server I have one keyword which is highly used and I get tons of data. In the case that server one, or server two, hits the 1%, it also delimitates the other one?

And a second question related. This also happens with rate limits?

Many thanks for the help, and great work!
Javier

**Comment by ErikBorra** [comment]
AFAIK as long as you use different IP addresses you can use the same user (albeit with different keys).

Would love to hear other people's reactions

**Comment by Spanishwalker** [comment]
What I notice is that having two servers does not work very well. When one hits a rate limit, the other one stops gathering data, and I have to reactivate it again.

Any ideas?

**Comment by ErikBorra** [comment]
We have 5 machines with 7 IP addresses running on 2 user accounts and 9 keys for track and follow. We do not have that experience.

**Comment by Spanishwalker** [comment]
Thats interesting.... Maybe the problem is not in the rate limit, but somewhere else.

I run the next command, and thats the outcome:
tail -20 /var/www/dmi-tcat/logs/controller.log

2016-02-26 17:01:18     received instruction to execute 'reload' for script track
2016-02-26 17:01:18     received instruction to execute 'reload' for script track
2016-02-26 17:01:18     received instruction to execute 'reload' for script track
2016-02-26 17:01:18     received instruction to execute 'reload' for script track
2016-02-26 17:01:18     received instruction to execute 'reload' for script track
2016-02-26 17:01:18     received instruction to execute 'reload' for script track
2016-02-26 17:01:18     script track was not running - starting
2016-03-01 16:48:44     received instruction to execute 'reload' for script track
2016-03-01 16:48:44     received instruction to execute 'reload' for script track


And the following one:


admin@ip-172-31-26-254:~$ tail -n 15 /etc/crontab
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user  command
17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly
25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#

# Run DMI-TCAT URL expander every hour
0 *     * * *   jaruizso   (cd /var/www/dmi-tcat/helpers; sh urlexpand.sh)

# Run TCAT controller every minute
* *     * * *   jaruizso   (cd /var/www/dmi-tcat/capture/stream/; php controller.php)


Next I do the following command:

admin@ip-172-31-26-254:~$ tail -n 50 /var/www/dmi-tcat/logs/track.error.log
    'headers' => 
    array (
      'Host' => 'stream.twitter.com',
      'Authorization' => 'OAuth oauth_consumer_key="4H0Jws92sjTGb1cexIzQ9Np37", oauth_nonce="c3e748da0f210eb8109934ecceae4c17", oauth_signature="seaK1v2pXXlBwehuVfyqY1rCO8Y%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1456850924", oauth_token="170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5", oauth_version="1.0"',
    ),
    'with_user' => true,
    'multipart' => false,
    'method' => 'POST',
    'without_bearer' => false,
    'url' => 'https://stream.twitter.com/1.1/statuses/filter.json',
    'oauth1_params' => 
    array (
      'oauth_consumer_key' => '4H0Jws92sjTGb1cexIzQ9Np37',
      'oauth_nonce' => 'c3e748da0f210eb8109934ecceae4c17',
      'oauth_signature' => 'seaK1v2pXXlBwehuVfyqY1rCO8Y%3D',
      'oauth_signature_method' => 'HMAC-SHA1',
      'oauth_timestamp' => '1456850924',
      'oauth_token' => '170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5',
      'oauth_version' => '1.0',
    ),
    'prepared_params' => 
    array (
      'track' => 'troika%2CTTIP%2Cdraghi%2Csoteu%2CSchengen%2Ceurovision%2Cbrexit',
    ),
    'basestring_params' => 'oauth_consumer_key=4H0Jws92sjTGb1cexIzQ9Np37&oauth_nonce=c3e748da0f210eb8109934ecceae4c17&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1456850924&oauth_token=170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5&oauth_version=1.0&track=troika%2CTTIP%2Cdraghi%2Csoteu%2CSchengen%2Ceurovision%2Cbrexit',
    'postfields' => 'track=troika%2CTTIP%2Cdraghi%2Csoteu%2CSchengen%2Ceurovision%2Cbrexit',
    'basestring' => 'POST&https%3A%2F%2Fstream.twitter.com%2F1.1%2Fstatuses%2Ffilter.json&oauth_consumer_key%3D4H0Jws92sjTGb1cexIzQ9Np37%26oauth_nonce%3Dc3e748da0f210eb8109934ecceae4c17%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1456850924%26oauth_token%3D170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5%26oauth_version%3D1.0%26track%3Dtroika%252CTTIP%252Cdraghi%252Csoteu%252CSchengen%252Ceurovision%252Cbrexit',
    'signing_key' => 'AoP9efOJxeR9yQzXFmRiI35QG3gdudeOmg39L8TPc9G9jG8vHv&MMzbKTscH4xAIH9RDHd0V6SwQ1Hq71erjbyuWj0dZhLuX',
  ),
   'metrics' => 
  array (
    'start' => 1456850924,
    'interval_start' => 1457466627,
    'messages' => 492138,
    'last_messages' => 492133,
    'bytes' => 2300391168,
    'last_bytes' => 2300359582,
    'mps' => 1.5,
    'bps' => 6609.6000000000004,
  ),
))
2016-03-08 19:50:33     processing buffer before exit
2016-03-09 09:58:26     running php version 5.6.17-0+deb8u1 in mode cli with extensions Core,date,ereg,libxml,openssl,pcre,zlib,bcmath,bz2,calendar,ctype,dba,dom,hash,fileinfo,filter,ftp,gettext,SPL,iconv,mbstring,pcntl,session,posix,Reflection,standard,shmop,SimpleXML,soap,sockets,Phar,exif,sysvmsg,sysvsem,sysvshm,tokenizer,wddx,xml,xmlreader,xmlwriter,zip,PDO,curl,geos,json,mysql,mysqli,pdo_mysql,readline,mhash,Zend OPcache (ini file: /etc/php5/cli/php.ini)
2016-03-09 09:58:26     installing term signal handler for this script
2016-03-09 09:58:26     geoPHP library is fully functional
2016-03-09 09:58:26     started script track with pid 19434
2016-03-09 09:58:26     connecting to API socket
2016-03-09 09:58:26     connecting - query array (
  'track' => 'troika,TTIP,draghi,soteu,Schengen',
)


I think that is all information I can provide. Any ideas why it happens? Why time to time it stops gathering data, and I need to run cd /var/www/dmi-tcat/capture/stream/; sudo -u jaruizso php controller.php ?

**Comment by dentoir** [comment]
From your controller.log file, it seems it is still not running controller.php every minute, so if you lose your connection to Twitter, it will not automatically restart it.

We'll need more lines to see why your track process stopped

` tail -n 100 /var/www/dmi-tcat/logs/track.error.log`

**Comment by Spanishwalker** [comment]
mmm... thats something new. I thought the amazon servers where online almost entirely all the time. Is there any way to know if they are down?

admin@ip-172-31-26-254:~$ tail -n 100 /var/www/dmi-tcat/logs/track.error.log
Accept-Encoding: deflate, gzip
Host: stream.twitter.com
Authorization: OAuth oauth_consumer_key="4H0Jws92sjTGb1cexIzQ9Np37", oauth_nonce="c3e748da0f210eb8109934ecceae4c17", oauth_signature="seaK1v2pXXlBwehuVfyqY1rCO8Y%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1456850924", oauth_token="170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5", oauth_version="1.0"
Content-Length: 69
Content-Type: application/x-www-form-urlencoded

',
    ),
    'error' => '',
    'errno' => 0,
  ),
   'buffer' => '',
   'config' => 
  array (
    'user_agent' => 'tmhOAuth 0.8.3+SSL - //github.com/themattharris/tmhOAuth',
    'host' => 'stream.twitter.com',
    'consumer_key' => '4H0Jws92sjTGb1cexIzQ9Np37',
    'consumer_secret' => 'AoP9efOJxeR9yQzXFmRiI35QG3gdudeOmg39L8TPc9G9jG8vHv',
    'token' => '170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5',
    'secret' => 'MMzbKTscH4xAIH9RDHd0V6SwQ1Hq71erjbyuWj0dZhLuX',
    'bearer' => '',
    'oauth_version' => '1.0',
    'oauth_signature_method' => 'HMAC-SHA1',
    'curl_http_version' => 2,
    'curl_connecttimeout' => 30,
    'curl_timeout' => 10,
    'curl_ssl_verifyhost' => 2,
    'curl_ssl_verifypeer' => true,
    'use_ssl' => true,
    'curl_cainfo' => '/var/www/dmi-tcat/capture/common/tmhOAuth/cacert.pem',
    'curl_capath' => '/var/www/dmi-tcat/capture/common/tmhOAuth',
    'curl_followlocation' => false,
    'curl_proxy' => false,
    'curl_proxyuserpwd' => false,
    'curl_encoding' => '',
    'is_streaming' => true,
    'streaming_eol' => '
',
    'streaming_metrics_interval' => 10,
    'as_header' => true,
    'force_nonce' => false,
    'force_timestamp' => false,
    'streaming_callback' => 'tracker_streamCallback',
  ),
   'request_settings' => 
  array (
    'params' => 
    array (
      'track' => 'troika,TTIP,draghi,soteu,Schengen,eurovision,brexit',
    ),
    'headers' => 
    array (
      'Host' => 'stream.twitter.com',
      'Authorization' => 'OAuth oauth_consumer_key="4H0Jws92sjTGb1cexIzQ9Np37", oauth_nonce="c3e748da0f210eb8109934ecceae4c17", oauth_signature="seaK1v2pXXlBwehuVfyqY1rCO8Y%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1456850924", oauth_token="170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5", oauth_version="1.0"',
    ),
    'with_user' => true,
    'multipart' => false,
    'method' => 'POST',
    'without_bearer' => false,
    'url' => 'https://stream.twitter.com/1.1/statuses/filter.json',
    'oauth1_params' => 
    array (
      'oauth_consumer_key' => '4H0Jws92sjTGb1cexIzQ9Np37',
      'oauth_nonce' => 'c3e748da0f210eb8109934ecceae4c17',
      'oauth_signature' => 'seaK1v2pXXlBwehuVfyqY1rCO8Y%3D',
      'oauth_signature_method' => 'HMAC-SHA1',
      'oauth_timestamp' => '1456850924',
      'oauth_token' => '170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5',
      'oauth_version' => '1.0',
    ),
    'prepared_params' => 
    array (
      'track' => 'troika%2CTTIP%2Cdraghi%2Csoteu%2CSchengen%2Ceurovision%2Cbrexit',
    ),
    'basestring_params' => 'oauth_consumer_key=4H0Jws92sjTGb1cexIzQ9Np37&oauth_nonce=c3e748da0f210eb8109934ecceae4c17&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1456850924&oauth_token=170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5&oauth_version=1.0&track=troika%2CTTIP%2Cdraghi%2Csoteu%2CSchengen%2Ceurovision%2Cbrexit',
    'postfields' => 'track=troika%2CTTIP%2Cdraghi%2Csoteu%2CSchengen%2Ceurovision%2Cbrexit',
    'basestring' => 'POST&https%3A%2F%2Fstream.twitter.com%2F1.1%2Fstatuses%2Ffilter.json&oauth_consumer_key%3D4H0Jws92sjTGb1cexIzQ9Np37%26oauth_nonce%3Dc3e748da0f210eb8109934ecceae4c17%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1456850924%26oauth_token%3D170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5%26oauth_version%3D1.0%26track%3Dtroika%252CTTIP%252Cdraghi%252Csoteu%252CSchengen%252Ceurovision%252Cbrexit',
    'signing_key' => 'AoP9efOJxeR9yQzXFmRiI35QG3gdudeOmg39L8TPc9G9jG8vHv&MMzbKTscH4xAIH9RDHd0V6SwQ1Hq71erjbyuWj0dZhLuX',
  ),
   'metrics' => 
  array (
    'start' => 1456850924,
    'interval_start' => 1457466627,
    'messages' => 492138,
    'last_messages' => 492133,
    'bytes' => 2300391168,
    'last_bytes' => 2300359582,
    'mps' => 1.5,
    'bps' => 6609.6000000000004,
  ),
))
2016-03-08 19:50:33     processing buffer before exit
2016-03-09 09:58:26     running php version 5.6.17-0+deb8u1 in mode cli with extensions Core,date,ereg,libxml,openssl,pcre,zlib,bcmath,bz2,calendar,ctype,dba,dom,hash,fileinfo,filter,ftp,gettext,SPL,iconv,mbstring,pcntl,session,posix,Reflection,standard,shmop,SimpleXML,soap,sockets,Phar,exif,sysvmsg,sysvsem,sysvshm,tokenizer,wddx,xml,xmlreader,xmlwriter,zip,PDO,curl,geos,json,mysql,mysqli,pdo_mysql,readline,mhash,Zend OPcache (ini file: /etc/php5/cli/php.ini)
2016-03-09 09:58:26     installing term signal handler for this script
2016-03-09 09:58:26     geoPHP library is fully functional
2016-03-09 09:58:26     started script track with pid 19434
2016-03-09 09:58:26     connecting to API socket
2016-03-09 09:58:26     connecting - query array (
  'track' => 'troika,TTIP,draghi,soteu,Schengen',
)
admin@ip-172-31-26-25

**Comment by Spanishwalker** [comment]
It just happened again. Stopped gathering data, and I had to restart the cronjob manually. Thats the info before starting again the cronjob:

admin@ip-172-31-26-254:~$ tail -n 100 /var/www/dmi-tcat/logs/track.error.log
      array (
      ),
      'primary_port' => 443,
      'local_ip' => '172.31.26.254',
      'local_port' => 47011,
      'request_header' => 'POST /1.1/statuses/filter.json HTTP/1.1
User-Agent: tmhOAuth 0.8.3+SSL - //github.com/themattharris/tmhOAuth
Accept: */*
Accept-Encoding: deflate, gzip
Host: stream.twitter.com
Authorization: OAuth oauth_consumer_key="4H0Jws92sjTGb1cexIzQ9Np37", oauth_nonce="3925920be3ca59eeb88437835c372fc2", oauth_signature="GEYfcsMNMdJD03Mh3SjekdocqJA%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1457517506", oauth_token="170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5", oauth_version="1.0"
Content-Length: 47
Content-Type: application/x-www-form-urlencoded

',
    ),
    'error' => '',
    'errno' => 0,
  ),
   'buffer' => '',
   'config' => 
  array (
    'user_agent' => 'tmhOAuth 0.8.3+SSL - //github.com/themattharris/tmhOAuth',
    'host' => 'stream.twitter.com',
    'consumer_key' => '4H0Jws92sjTGb1cexIzQ9Np37',
    'consumer_secret' => 'AoP9efOJxeR9yQzXFmRiI35QG3gdudeOmg39L8TPc9G9jG8vHv',
    'token' => '170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5',
    'secret' => 'MMzbKTscH4xAIH9RDHd0V6SwQ1Hq71erjbyuWj0dZhLuX',
    'bearer' => '',
    'oauth_version' => '1.0',
    'oauth_signature_method' => 'HMAC-SHA1',
    'curl_http_version' => 2,
    'curl_connecttimeout' => 30,
    'curl_timeout' => 10,
    'curl_ssl_verifyhost' => 2,
    'curl_ssl_verifypeer' => true,
    'use_ssl' => true,
    'curl_cainfo' => '/var/www/dmi-tcat/capture/common/tmhOAuth/cacert.pem',
    'curl_capath' => '/var/www/dmi-tcat/capture/common/tmhOAuth',
    'curl_followlocation' => false,
    'curl_proxy' => false,
    'curl_proxyuserpwd' => false,
    'curl_encoding' => '',
    'is_streaming' => true,
    'streaming_eol' => '
',
    'streaming_metrics_interval' => 10,
    'as_header' => true,
    'force_nonce' => false,
    'force_timestamp' => false,
    'streaming_callback' => 'tracker_streamCallback',
  ),
   'request_settings' => 
  array (
    'params' => 
    array (
      'track' => 'troika,TTIP,draghi,soteu,Schengen',
    ),
    'headers' => 
    array (
      'Host' => 'stream.twitter.com',
      'Authorization' => 'OAuth oauth_consumer_key="4H0Jws92sjTGb1cexIzQ9Np37", oauth_nonce="3925920be3ca59eeb88437835c372fc2", oauth_signature="GEYfcsMNMdJD03Mh3SjekdocqJA%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1457517506", oauth_token="170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5", oauth_version="1.0"',
    ),
    'with_user' => true,
    'multipart' => false,
    'method' => 'POST',
    'without_bearer' => false,
    'url' => 'https://stream.twitter.com/1.1/statuses/filter.json',
    'oauth1_params' => 
    array (
      'oauth_consumer_key' => '4H0Jws92sjTGb1cexIzQ9Np37',
      'oauth_nonce' => '3925920be3ca59eeb88437835c372fc2',
      'oauth_signature' => 'GEYfcsMNMdJD03Mh3SjekdocqJA%3D',
      'oauth_signature_method' => 'HMAC-SHA1',
      'oauth_timestamp' => '1457517506',
      'oauth_token' => '170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5',
      'oauth_version' => '1.0',
    ),
    'prepared_params' => 
    array (
      'track' => 'troika%2CTTIP%2Cdraghi%2Csoteu%2CSchengen',
    ),
    'basestring_params' => 'oauth_consumer_key=4H0Jws92sjTGb1cexIzQ9Np37&oauth_nonce=3925920be3ca59eeb88437835c372fc2&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1457517506&oauth_token=170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5&oauth_version=1.0&track=troika%2CTTIP%2Cdraghi%2Csoteu%2CSchengen',
    'postfields' => 'track=troika%2CTTIP%2Cdraghi%2Csoteu%2CSchengen',
    'basestring' => 'POST&https%3A%2F%2Fstream.twitter.com%2F1.1%2Fstatuses%2Ffilter.json&oauth_consumer_key%3D4H0Jws92sjTGb1cexIzQ9Np37%26oauth_nonce%3D3925920be3ca59eeb88437835c372fc2%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1457517506%26oauth_token%3D170303282-KvynOiyM3QjmezpxCxa3Q3ejDUx4rpdVu2MsZIh5%26oauth_version%3D1.0%26track%3Dtroika%252CTTIP%252Cdraghi%252Csoteu%252CSchengen',
    'signing_key' => 'AoP9efOJxeR9yQzXFmRiI35QG3gdudeOmg39L8TPc9G9jG8vHv&MMzbKTscH4xAIH9RDHd0V6SwQ1Hq71erjbyuWj0dZhLuX',
  ),
   'metrics' => 
  array (
    'start' => 1457517506,
    'interval_start' => 1457547936,
    'messages' => 9829,
    'last_messages' => 9829,
    'bytes' => 42200049,
    'last_bytes' => 42200049,
    'mps' => 1.2,
    'bps' => 6530.8000000000002,
  ),
))
2016-03-09 18:25:37     processing buffer before exit



And this one just in case....
admin@ip-172-31-26-254:~$ tail -40 /var/www/dmi-tcat/logs/controller.log        
2016-02-26 17:01:18     received instruction to execute 'reload' for script track
2016-02-26 17:01:18     received instruction to execute 'reload' for script track
2016-02-26 17:01:18     received instruction to execute 'reload' for script track
2016-02-26 17:01:18     received instruction to execute 'reload' for script track
2016-02-26 17:01:18     received instruction to execute 'reload' for script track
2016-02-26 17:01:18     received instruction to execute 'reload' for script track
2016-02-26 17:01:18     script track was not running - starting
2016-03-01 16:48:44     received instruction to execute 'reload' for script track
2016-03-01 16:48:44     received instruction to execute 'reload' for script track
2016-03-01 16:48:44     received instruction to execute 'reload' for script track
2016-03-01 16:48:44     received instruction to execute 'reload' for script track
2016-03-01 16:48:44     received instruction to execute 'reload' for script track
2016-03-01 16:48:44     script track was not running - starting
2016-03-09 09:58:26     received instruction to execute 'reload' for script track
2016-03-09 09:58:26     received instruction to execute 'reload' for script track
2016-03-09 09:58:26     received instruction to execute 'reload' for script track
2016-03-09 09:58:26     received instruction to execute 'reload' for script track
2016-03-09 09:58:26     script track was not running - starting



And finally this one:
admin@ip-172-31-26-254:~$ tail -n 30 /etc/crontab                               
# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user  command
17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly
25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#

# Run DMI-TCAT URL expander every hour
0 *     * * *   jaruizso   (cd /var/www/dmi-tcat/helpers; sh urlexpand.sh)

# Run TCAT controller every minute
* *     * * *   jaruizso   (cd /var/www/dmi-tcat/capture/stream/; php controller.php)

**Comment by dentoir** [comment]
Your Amazon server is not down, but it loses it's connection to Twitter. Reason unknown here. It  is an issue we sometimes encounter too, but the controller (through cron) should simply reconnect within a minute. This is not happening for you, so it looks like a cron thing. You can use the following command to check if cron is running.

`systemctl status cron`

**Comment by Spanishwalker** [comment]
It says:

admin@ip-172-31-26-254:~$ systemctl status cron
Failed to get D-Bus connection: No such file or directory

**Comment by dentoir** [comment]
Hi @Spanishwalker 

That's strange. Can you give us the output of the following commands?

`pgrep cron`

And

`uname -a`

And

`cat /etc/issue`

And finally:

`dpkg -l | grep systemd`

**Comment by Spanishwalker** [comment]
Here we go. Hope it helps!

admin@ip-172-31-26-254:~$ pgrep cron
319

admin@ip-172-31-26-254:~$ uname -a
Linux ip-172-31-26-254 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux

admin@ip-172-31-26-254:~$ cat /etc/issue
Debian GNU/Linux 8 \n \l

admin@ip-172-31-26-254:~$ dpkg -l | grep systemd
ii  libsystemd0:amd64              215-17+deb8u3             amd64        systemd utility library
ii  systemd                        215-17+deb8u3             amd64        system and service manager
ii  systemd-sysv                   215-17+deb8u3             amd64        system and service manager - SysV links

**Comment by jaruizso** [comment]
Is there any solution? Its a bit annoying to check every day if the app is running, and I am missing a lot of data...

**Comment by ErikBorra** [comment]
Hi @jaruizso,

a) you have many disconnects
b) your crontab is not able to start the controller 

as for a) I have no clue why that happens so regularly. It might be because of an unstable connection (iirc some Amazon instances do not guarantee 100% uptime).

as for b) you try to run a command as user jaruizso from with the crontab of user admin. Two questions: 
1) what user has write access to/var/www/dmi-tcat/proc and /var/www/dmi-tcat/logs? Run the commands `ls /var/www/dmi-tcat/proc; ls /var/www/dmi-tcat/logs` and make sure that they are either 'admin' or 'jaruizso'. 
2) If the user for 1) is admin, remove the 'jaruizso' part from the crontab. If the user for 1) is 'jaruizso', remove the dmi-tcat lines from the crontab for admin, and make a crontab for jaruizso `crontab -u jaruizso -e` according to the [install instructions](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Install-Guide#install-crontab).

Hope this helps.

Best,

Erik

**Comment by jaruizso** [comment]
It seems it is solved. I just restarted the server, and now it seems gathering data for some weeks already without interruption.

**Comment by ErikBorra** [comment]
Hi Jaruizso,

great to hear that everything works fine now. Can you tell us how you resolved the issue?

Best,

Erik

**Comment by jaruizso** [comment]
I did nothing special. I went to Amazon EC2 website and stopped the server, waited some time (20 minutes) and I initiated the server again. Magic happened.

**Comment by ErikBorra** [comment]
Magic, don't you love it? ;)
