### ISSUE TITLE
Deleting bin with shared phrase deletes phrase from tcat_query_phrases

### ISSUE THREAD

**Issue by brendam** [digitalmethodsinitiative/dmi-tcat#159]
I guess not many people do this in real life, I've just found it during some testing. 

If I create a new bin with the same phrase as I've used in an old bin, it reuses the same id for that phrase (which is what I'd expect). If I then delete the new bin, it deletes the phrase from the `tcat_query_phrases` table even though it is still in use in the other bin. This leaves that bin with no phrases associated with it, even though all the tweets collected for it are still in the database as is the `tcat_query_bins_phrases` record for that phrase.

**Comment by dentoir** [comment]
Thank you for reporting this bug, I'll get fixing it today.

**Comment by dentoir** [comment]
This bug is now assumed to have been fixed in the current version.

**Comment by brendam** [comment]
it works correctly here now, thanks @dentoir
