### ISSUE TITLE
queries

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#161]
Hi,

I am relativley new to TCAT. I have been used to use standard booleans for searching Twitter, and using asterixes to find variations of terms. E.g. trump* will find tweets containing the word trump but also trump2016, trumpforpresident, etc. And *trump will also find tweets containing #trump, etc.  In TCAT this seems not to be the case? You can only search for exact words?

Arnout

**Comment by ErikBorra** [comment]
Dear Arnout,

that is correct. Please have a look at the documentation of the track API as provided by Twitter (and linked to from the capture interface of DMI-TCAT).

Best,

Erik

**Comment by arnoutponsioen** [comment]
Dag Erik

Ja, die heb ik bekeken en daar kon ik dat inderdaad ook niet terugvinden. Misschien was er toch een oplossing voor, vandaar mijn vraag. Wel jammer toch?

Is het voor jou handiger om via github vragen te stellen? Anders vervuilt je mailbox zo… En hoe houd je het allemaal behapbaar qua tijd. Komen er veel vragen binnen of ben ik de enige?

Met groet,

Arnout Ponsioen

DUiDT
06-81452987

Van: Erik Borra [mailto:notifications@github.com]
Verzonden: donderdag 17 maart 2016 10:11
Aan: digitalmethodsinitiative/dmi-tcat <dmi-tcat@noreply.github.com>
CC: Arnout Ponsioen <arnout@duidt.nl>
Onderwerp: Re: [dmi-tcat] queries (#161)


Dear Arnout,

that is correct. Please have a look at the documentation of the track API as provided by Twitter (and linked to from the capture interface of DMI-TCAT).

Best,

Erik

**Comment by ErikBorra** [comment]
Graag vragen via Github, dan kunnen anderen ook nog antwoorden op dezelfde vragen vinden.

Jij stelt wel heel veel vragen :p

**Comment by arnoutponsioen** [comment]
Sorry, had several problems installing TCAT. It now works fine... Have many more questions though...
