### ISSUE TITLE
Uninstall and reinstall TCAT on Ubuntu

### ISSUE THREAD

**Issue by dormeir99o** [digitalmethodsinitiative/dmi-tcat#162]
What's the best way to uninstall and reinstall the app? Is there a certain order for things?

**Comment by ErikBorra** [comment]
To remove dmi-tcat you should do the following:
* remove the folder where dmi-tcat is installed, e.g. `rm -rf /var/www/dmi-tcat`
* remove the dmi-tcat database. Login to mysql and run `drop table twittercapture`
* clean up your crontab. As the user under which dmi-tcat is running, do `crontab -e` on the command line and remove the lines with controller.php and the urlexpander.

Then, you can just run the automatic installation script again.

**Comment by ErikBorra** [comment]
@dentoir This information should also be provided in the FAQ.
