### ISSUE TITLE
boot script

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#163]
Hi,

Tried to find a script (to be placed in /etc/init.d (?) to automatically start tcat when at server boot. In my case, tweets are not collected after the server booted. Only after using php dmitcat_track.php tweets are coming in. Anybody written such a boot-script, or other solutions preventing a necessary manual start?

Arnout

**Comment by ErikBorra** [comment]
Hi Arnout,

the script will start automatically if you have set up the [crontab](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Install-Guide#install-crontab) (should have been done automatically with the automated installer).

Best,

Erik

**Comment by arnoutponsioen** [comment]
Ok. just checked crontab file. It contains only lines with #
Just added the line: cd /var/www/dmi-tcat/capture/stream/; php controller.php

Will that suffice?

Arnout

**Comment by ErikBorra** [comment]
If you have used the default installation locations you should add the following line:
`* * * * * (cd /var/www/dmi-tcat/capture/stream/; php controller.php)`

**Comment by arnoutponsioen** [comment]
with all the asterixes?

**Comment by ErikBorra** [comment]
yes, yes.

**Comment by arnoutponsioen** [comment]
You are a wizard Erik!
Server boots and tweets are coming in!

**Comment by ErikBorra** [comment]
Great!
