### ISSUE TITLE
Automated install scripts saying "It does not look like you are running Ubuntu", on Ubuntu Xenial Xerus 16.04

### ISSUE THREAD

**Issue by dormeir99o** [digitalmethodsinitiative/dmi-tcat#165]
As you can see Below, the automated install script doesn't recognize my Ubuntu 16.04 as Ubuntu.
Strangelty enough, the Debian scripts does work for my Ubunto (also below).
should I install with the Debian scripts?

curl -s "https://raw.githubusercontent.com/digitalmethodsinitiative/dmi-tcat/master/helpers/tcat-deploy-ubuntu.sh" -o /root/tcat-deploy-ubuntu.sh ; /bin/bash /root/tcat-deploy-ubuntu.sh

Welcome to the DMI TCAT installation script
===========================================

It does not look like you are running Ubuntu. This is an Ubuntu installation script. Exiting.
root@TCAT:~#
root@TCAT:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu Xenial Xerus (development branch)
Release:        16.04
Codename:       xenial

root@TCAT:~# curl -s "https://raw.githubusercontent.com/digitalmethodsinitiative/dmi-tcat/master/helpers/tcat-deploy-debian.sh" -o /root/tcat-deploy-debian.sh ; /bin/bash /root/tcat-deploy-debian.sh

Welcome to the DMI TCAT installation script
===========================================

Before installation, you will to fill in some information about your server configuration.

Server name for TCAT:

**Comment by ErikBorra** [comment]
This issue has been addressed via updates to the installer script.
