### ISSUE TITLE
import json

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#166]
Hi,

Just tried the import function of json dump, but got all kinds of errors.
The actual .json file is in /var/www/dmi-tcat/import

root@server:/var/www/dmi-tcat/import# php import-jsondump.php                                                                                                                      
The query bin 'energietransitiexxx' already exists. Are you sure you want to add tweets to 'energietransitiexxx'? (yes/no)                                                         
yes                                                                                                                                                                                
processing ../import/test.json                                                                                                                                                     
PHP Warning:  Invalid argument supplied for foreach() in /var/www/dmi-tcat/capture/common/functions.php on line 1129                                                               
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/dmi-tcat/capture/common/functions.php on line 1140                                        
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/dmi-tcat/capture/common/functions.php on line 1143                                        
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/dmi-tcat/capture/common/functions.php on line 1144                                        
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual th
at corresponds to your MariaDB server version for the right syntax to use near ')' at line 1' in /var/www/dmi-tcat/capture/common/functions.php:1274                               
Stack trace:                                                                                                                                                                       
#0 /var/www/dmi-tcat/capture/common/functions.php(1274): PDOStatement->execute()                                                                                                   
#1 /var/www/dmi-tcat/import/import-jsondump.php(68): Tweet->isInBin('energietransiti...')                                                                                          
#2 /var/www/dmi-tcat/import/import-jsondump.php(44): process_json_file_timeline('../import/test....', Object(PDO))                                                                 
#3 {main}                                                                                                                                                                          
  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 1274   

The import-jsnondump.php file has been changed according the instruction. 

// specify the name of the bin here 
$bin_name = 'energietransitiexxx';
// specify dir with the user timelines (json)
$dir = '../import';
// set type of dump ('import follow' or 'import track')
$type = 'import track';
// if 'import track', specify keywords for which data was captured
$queries = array('energietransitie');

Any suggestions?

Arnout

**Comment by arnoutponsioen** [comment]
Must be related to the json file itself? field names?

**Comment by ErikBorra** [comment]
Your JSON is probably not in the same format as the Twitter API. If you exported the data from gnip, use the import-gnip.php script.

**Comment by ErikBorra** [comment]
As you explained to me via email you have a CSV file and not a JSON file. The import will not work unless you a) make a script which maps the CSV fields to the dmi-tcat database script or b) extract the IDs and use the ids/lookup.php script.
