### ISSUE TITLE
twittercapture.tcat_controller_tasklist table missing after new install

### ISSUE THREAD

**Issue by brendam** [digitalmethodsinitiative/dmi-tcat#169]
When I do a new install and then run upgrade.php before creating any bins I get an error saying that the twittercapture.tcat_controller_tasklist table doesn't exist. After I create a bin the error doesn't happen even if the bin is removed. The database is created by loading the capture page.

```
 php upgrade.php
2016-03-23 15:18:09	Running in interactive mode
2016-03-23 15:18:09	Executing global upgrade
2016-03-23 15:18:09	Restarting active capture role: track
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'twittercapture.tcat_controller_tasklist' doesn't exist' in /var/www/dmi-tcat/common/upgrade.php:653
Stack trace:
#0 /var/www/dmi-tcat/common/upgrade.php(653): PDOStatement->execute()
#1 {main}
  thrown in /var/www/dmi-tcat/common/upgrade.php on line 653
```

**Comment by ErikBorra** [comment]
Hi Brenda,

there is no need to run upgrade.php after a new install. A new installation will always have the latest code changes. It is peculiar though that the upgrade script removes that table.

Best,

Erik

**Comment by hoylen** [comment]
I think it is due to the table not being there at all, until someone visits the TCAT Web pages for the first time.

**Comment by brendam** [comment]
@hoylen is right, the problem is that it is missing and that causes the upgrade.php to fail. Visiting the pages isn't enough, I found I had to create a bin to get the table created. 

I think this has been introduced recently because the script I've been using has alway done the unnecessary upgrade during setup. I think it was there in case you had restored an older database to the server.

**Comment by brendam** [comment]
I do get asked to upgrade the database after a fresh install of the latest TCAT: 

```Your database must be updated before some new TCAT features can be used. Follow the documentation and run the command-line script common/upgrade.php from your shell.```

the upgrade changes the database character set from utf8 to utf8mb4 - not sure why it isn't created with this character set?

**Comment by hoylen** [comment]
For what it is worth, the SQL command in the latest install script says:

    CREATE DATABASE IF NOT EXISTS twittercapture
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

Not sure if that is a new thing, or something else is overriding the default character set of the database.

**Comment by brendam** [comment]
At this stage I'm not using the install script. The database is created by loading one of the webpages in my case.

**Comment by ErikBorra** [comment]
Hi @brendam, @hoylen,

thanks for your valuable comments. Due to the Easter break, however, we'll only be able to follow up on it next week. I hope this doesn't cause any inconvenience.

Best,

Erik

**Comment by brendam** [comment]
@ErikBorra I hope you all have a good Easter :)

**Comment by dentoir** [comment]
Hi @brendam 

I don't understand, if you are installing TCAT manually from the Wiki instructions you are also creating the twittercapture database by executing the SQL yourself, like so?

`CREATE DATABASE IF NOT EXISTS twittercapture DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;`

Visiting the capture/ page should normally create the tcat_* tables, but we can additionally call those functions in the upgrade.php script.

**Comment by brendam** [comment]
I'm using an ansible script based on an earlier shell script which in turn was based on the old wiki instructions it does the install and configuration and the rest of our server setup. 

My ansible script does not create any tables, it uses the old approach of visiting the capture/ page to create them instead. But doing that does not create the ```tcat_controller_tasklist``` table.

I plan to change to using the new shell script from ansible once it is ready so this problem will go away, but maybe the capture page should create that new table if it doesn't exist?

**Comment by dentoir** [comment]
Sound sensible, implemented in the latest commit.
