### ISSUE TITLE
Can BASE_FILE be replaced by __DIR__?

### ISSUE THREAD

**Issue by hoylen** [digitalmethodsinitiative/dmi-tcat#170]
The PHP code uses the value of `BASE_FILE` (defined in _config.php_ as "/var/www/dmi-tcat/").

Can I change the code to replace that with `__DIR__` (PHP's built-in value for the directory of the current PHP source file) with appropriate concatenation with "/.." and "/../.." depending on which PHP file is concerned?

This was originally motivated by making it possible for the _export.php_ and _import.php_ scripts to be run from any current working directory. But eliminating the need for BASE_FILE means one-less-thing that can go wrong.

I've also noticed that some code requires BASE_FILE to end with a slash, but other places assume it does not end with a slash (but the code still works).

```php
require_once BASE_FILE . 'analysis/common/functions.php';
require_once(BASE_FILE . '/analysis/common/config.php');
```

The later produces "/var/www/dmi-tcat//analysis.common.config.php" (containing two slashes in a row) which is ugly but still works.

This will be cleaned up in the process.

**Comment by dentoir** [comment]
We would need to take care not to simply move files around in the directory tree after such a change, but it still seems sensible.

However, the analysis/cache write-directory is an additional customizable path set by $resultsdir, which is used in the analysis/* modules and also by import.php and export.php

We want export.php and import.php to be able to run from any location I think, like it currently is. So we want to use something like this (untested suggestion)?

`realpath('../analysis/$resultsdir')`

**Comment by hoylen** [comment]
> We would need to take care not to simply move files around in the directory tree 

Yes, obviously moving the PHP files around would break things. But that is no different from the current situation, where they would break if moved; since imports are currently referenced relative to `BASE_FILE`.

> We want export.php and import.php to be able to run from any location I think, like it currently is.

The current export.php and import.php scripts can't be run from any location: which is why I started looking at this: to make it possible for them to be run from any working directory.

> realpath

I tried using `realpath`. If I remember correctly, the problem is that it only works with existing files. So it is not useful for expanding out pathnames for files that you are going to create (i.e. files which don't exist yet).

**Comment by dentoir** [comment]
Ah, sorry, you are correct. It seems you can only run the controller from the local directory too. So your suggestion would improve things.

**Comment by hoylen** [comment]
Ok. I've made these changes:
- Changed references to `BASE_FILE` to be relative to `__DIR__`.
- Removed `BASE_FILE` from the _config.php_ file (since it is no longer being used).
- Removed setting up `BASE_FILE` by the _tact-linux-install.sh_ script since it is no longer in the _config.php_ file.
- Changed the various `include`, `include_once`, `require`, `require_once` statements to reference the target file relative to `__DIR__` instead of a path relative to the current working directory.
    - Change all those statements to consistently not have parenthesis around the file name (e.g. `require_once __DIR__ . '/../../config.php;` instead of `require_once(__DIR__ . '/../../config.php';`) since they are statements rather than function calls. That is, there were some places that had `require_once(...);` and some places that had `require_once ...;`, but now they all consistently follow the second form without the parenthesis.
    - Made them all consistently expect `__DIR__` to not end with a slash.
    - Made them consistently uses single quotes around the file path (instead of some using single quotes and some using double quotes).
    - The only file I didn't make such a change is _capture/common/geoPHP/geoPHP.inc_, since that appears to be a third party library. So code that references that library might only run properly if the current working directory is in a certain directory. I did see some "cd" commands in some of the PHP files, so maybe that has already been taken care of? There are things going on that I don't fully understand.
    - Try running some `grep -R` searches to find those statements and see what has been done.

I've done a small amount of testing and it appears to work:
- it installs
- a keyword query bin can be created
- it captures tweets (note: the `capture.php` script can be from any working directory: no "cd" required in the crontab)
- the URL expansion can be run (note: the `urlexpand.sh` command can now run from any current working directory: no "cd" required in the crontab)
- the analysis page comes up.

Do you have a test plan or procedure to test if everything is still working? I think these changes need more testing before we can be confident nothing has been broken by them.

If you want to try it out, get it from the "BASE_FILE" branch on my clone of the repository on GitHub: https://github.com/hoylen/dmi-tcat/tree/BASE_FILE

1. Download the modified _helpers/tcat-install-linux.sh from_ that branch. That version of the install script no longer configures the `BASE_FILE` in _config.php_ and has a new undocumented debug mode for testing these changes.
2. Run it in the debug mode (with the -D option). In debug mode, the installer will clone the full repository from my GitHub repository and then checkout the "BASE_FILE" branch (instead of using the "master" branch from DMI's GitHub repository).

    _Actually, this might be a useful feature, if you want to start tagging releases and have the install script download specific releases instead of whatever is at the HEAD of the master branch. Though it would be nice to find a way to do this without having to clone the entire repository (which I had to do to get the git checkout command to work)._

        sudo ./tcat-install-linux.sh -D

P.S. I've also updated the Installation Guide wiki page to describe the new install script. But it seems strange that I could go in and edit it without any special authorisation.

**Comment by ErikBorra** [comment]
@hoylen,

your work is awesome and well appreciated! Thanks :) 

Unfortunately we'll have to defer testing to after the weekend. Currently we have no unit testing or so. If you have any ideas on how to improve this, please let us know. 

As for the wiki, thanks so much for providing a very clear and concise installation manual and making appropriate other changes. Github does have an option to restrict editing only to members who are allowed to push code changes. We do like the open nature of wikis though (especially considering your contributions ;)) and will leave it open to edit for everybody as long as it goes well. This does mean that we have to regularly check https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/_history for changes :)

Best,

Erik

**Comment by hoylen** [comment]
You're welcome.

No hurry on the testing. I'll leave that branch there until you tell me it is ready to submit a pull-request for it.

I currently don't have a complete grasp of the breadth and depth of what TCAT does, or the expected results, so I don't really know what needs to be tested. That information is probably in your head: what to do to exercise every piece of functionality.

Since right now all the functions are accessed via a Web browser, a starting point could be a human-readable document that lists what to do (click on and type in) and what is expected to happen. It is a lot of work to write such a document, but it might be something you think about as you do testing on this set of changes. Maybe write down some notes, or take a screencast of what you do as you are doing it. The extreme way is to automate the browser with tools like Selenium, but that is even more work to create and maintain!

The other thing that makes testing hard is that the actual results depends on the tweets captured. Ideally, we have a test harness that simulates the Twitter API, but provides deterministic tweets for testing. But again, building one of those is also a lot of work. Something to dream about.

**Comment by hoylen** [comment]
I forgot to mention, when testing please give special attention to lines 447 and 483 in _capture/common/functions.php_.

This is what they are now:

    $gitcmd = 'git --git-dir ' . realpath(__DIR__ . '/../..') .  '/.git log --pretty=oneline -n 1';
    $gitcmd = 'git --git-dir ' . realpath(__DIR__ . '/../..') . '/.git rev-parse --abbrev-ref HEAD';

Because they used to be:

    $gitcmd = 'git --git-dir ' . BASE_FILE . '.git log --pretty=oneline -n 1';
    $gitcmd = 'git --git-dir ' . BASE_FILE . '.git rev-parse --abbrev-ref HEAD';

Which would have expanded out `$gitcmd` to be "`git --git-dir /var/www/dmi-tcat/.git ...`" and it seems strange for that to be referencing the hidden ".git" directory. Remember that BASE_FILE used to have a "/" at the end. I've preserved the original result, but it seems incorrect.

**Comment by dentoir** [comment]
I'm testing this now. I'm writing some notes down for future reference. I'm taking the functional approach here: does it work as expected? Another approach is unit testing, which is more fine-grained but takes more time to implement and often requires existing functions to be rewritten. My documentation is markdown (though the extension is .txt as github restricts the extensions it accepts). We can put such a document in the repository, ofcourse:

[tcat_testing.md.txt](https://github.com/digitalmethodsinitiative/dmi-tcat/files/208450/tcat_testing.md.txt)

**Comment by dentoir** [comment]
Hi @hoylen 
> Which would have expanded out $gitcmd to be "git --git-dir /var/www/dmi-tcat/.git ..." and it seems strange for that to be referencing the hidden ".git" directory

I get an error message when I run the command without pointing to the .git hidden directory.

```
$ git --git-dir /var/www/dmi-tcat log --pretty=oneline -n 1
fatal: Not a git repository: '/var/www/dmi-tcat/'

versus

$ git --git-dir /var/www/dmi-tcat/.git log --pretty=oneline -n 1
a6fa23623939348f7e50c02abac029e9ba9cc053 Fixed some usage of __DIR__.
```

So I believe the invocation is correct? But there appears to be a newer option called -C, which allows a command like this:

`git -C /var/www/dmi-tcat log --pretty=oneline -n 1`

So we we probably want the latter one.

**Comment by dentoir** [comment]
Hi @hoylen 

I've tested your branch and couldn't find any problem with it. If you submit a pull request we can pull it into master.

Thank you,

Emile

**Comment by hoylen** [comment]
Pull request submitted.

With the "git log" command, I too found that `--git-dir` option didn't work as expected, but the `-C` option does work.
I'll leave it to you to change it to use `-C`, if you want.

Thanks.

**Comment by dentoir** [comment]
Alright, closing this issue!
