### ISSUE TITLE
Add a link from capture pages to the analysis pages

### ISSUE THREAD

**Issue by hoylen** [digitalmethodsinitiative/dmi-tcat#171]
To make it easier to use, can a hyperlink be added to the capture page to navigate to the analysis page?

It seems strange there is a link to go from the analysis page to the capture page, but not the other way around. Especially when all users logged into the capture page (i.e. admin) can access both pages; but not all users logged into the analysis page (i.e. admin or tcat) is permitted to access the capture page.

**Comment by ErikBorra** [comment]
This could be easily added by adding something like this to analysis/index.php 
```if (isset($_SERVER['PHP_AUTH_USER']) && $_SERVER['PHP_AUTH_USER'] == 'admin') { // display link here}```
