### ISSUE TITLE
getBinType incorrectly treats query bin names case-insensitively

### ISSUE THREAD

**Issue by hoylen** [digitalmethodsinitiative/dmi-tcat#174]
The `getBinType` function in _capture/common/functions.php_ seems to treat its argument, the query bin name, case insensitively.

This causes problems with the _export.php_ script, which relies on it returning _false_ to indicate an unknown query bin name has been specified on the command line. If a query bin's name has been specified with the wrong case, it is not identified as an error but the code later on fails when no table names are found with that case. Table names are case senstitive.

The `getBinType` function should treat the query bin name as case sensitive.

**Comment by dentoir** [comment]
Thanks, this bug is fixed in the latest commmit.
