### ISSUE TITLE
Install script inefficiently clones the entire git repository

### ISSUE THREAD

**Issue by hoylen** [digitalmethodsinitiative/dmi-tcat#175]
The TCAT install script clones the **entire** git repository when it really only needs one version of the files.

It currently says:

    git clone https://github.com/digitalmethodsinitiative/dmi-tcat.git "$TCAT_DIR"

Should that be changed to just create a shallow copy?

    git clone --depth 1 https://github.com/digitalmethodsinitiative/dmi-tcat.git "$TCAT_DIR"

**Comment by ErikBorra** [comment]
Sounds like a great idea. Do you also know of the top of your head the command to use afterwards if you do want the full history?

**Comment by hoylen** [comment]
No, not off the top of my head... but the answer is only a Web-search away.

http://stackoverflow.com/questions/6941889/is-it-safe-to-shallow-clone-with-depth-1-create-commits-and-pull-updates-aga says:

> The depth can later be changed with the `git-fetch --depth` switch, or full history restored with `--unshallow`.

**Comment by ErikBorra** [comment]
Thanks. I, too, am a big fan of Let Me Google That For You ;)

Now that we know the answer, let's just go for a default shallow copy.

**Comment by hoylen** [comment]
Done. It is now included in [pull-request #172](https://github.com/digitalmethodsinitiative/dmi-tcat/pull/172).

**Comment by hoylen** [comment]
Closing issue since the change has been pulled in.
