### ISSUE TITLE
Can't create bin with exact phrase using quote marks

### ISSUE THREAD

**Issue by nikhuji** [digitalmethodsinitiative/dmi-tcat#176]
I can't create a query with an exact phrase enclosed in quote marks - either or double or single.
When I try to track the phrase 'climate change' or "climate change" I get the error message: bin names can only consist of alpha-numeric characters and underscores

My tcat is updated to the most recent version. Everything else seems fine.
Thanks for your attention
Nik

**Comment by ErikBorra** [comment]
Hi Nik,

are you sure that you have entered those phrases in the right input box? Try setting the bin name to climate_change and the phrases to track to 'climate change'.

Best,

Erik

**Comment by nikhuji** [comment]
Hi
No, I had the right phrases in the right boxes. 
However, I also had a space in the bin name - that was what the error was about, and not the phrases.
My bad. Sorry.
Nik


Nicholas John 
Department of Communication 
The Hebrew University of Jerusalem 
T +972 54 7906073 
@nicholasajohn <applewebdata://CB1A74E0-BBF6-4EE1-B7B4-AFE4F5DA4313/%E2%80%9Chttp://www.twitter.com/nicholasajohn%E2%80%9D> 
nicholasjohn.huji.ac.il <applewebdata://CB1A74E0-BBF6-4EE1-B7B4-AFE4F5DA4313/%E2%80%9Chttp://nicholasjohn.huji.ac.il/%E2%80%9D>

**Comment by ErikBorra** [comment]
Great to hear that the problem has been solved. I'll open a new issue to address the space problem in bin names.

**Comment by dentoir** [comment]
This is implemented now in the capture panel, on querybin creation. Should we give the user explicit feedback about the translation? He or she will recognize the bin name from the overview and I think a querybin name should only be specified afterwards in the command-line scripts (such as search.php, export, import etc.).

**Comment by ErikBorra** [comment]
Good point about the command line scripts. Probably we should mention in both the documentation and as a comment in each of those scripts that bin names cannot contain spaces and can only consists of alpha-numeric characters en underscores.
