### ISSUE TITLE
Cant download "Export all tweets from selection"

### ISSUE THREAD

**Issue by jaruizso** [digitalmethodsinitiative/dmi-tcat#178]
Hi guys!

I have a little problem, and I could not find it in the other issues. The problem is that I cannot download the option of "Export all tweets from selection". The application seems to stop, and I can't load the next page where I can download the file.

I am talking about a big dataset (a bit more than 1M tweets), so I understand it can take some time to process it. Specially when the server its a small one (Amazon micro). Actually, it happens with other requests, such as networks, etc. It takes some minutes. But the difference is that in all of them, after taking some time, they go to the next page where I can download the file.

The message I get, after the loading bar of my browser stops is that the server does not respond or is busy. It happens only after a minute or so only with "export all tweets from selection". I tried with smaller samples of the same dataset, reducing the startdate and enddate. Like that it works. It takes a bit more of time, but I can download the file. However I only can get few days, instead of all the dataset.

Any idea why? or any idea if I can download the cvs of the dataset in any other way?

Thanks in advance!

**Comment by ErikBorra** [comment]
Hi @jaruizso,

it may be related to a couple of things. First, there are the memory and time limits of PHP, which you can set configure in dmi-tcat's config.php. Have a look at your php error logs to see whether an error is raised when trying to export all the tweets.

Second, it may be related to specific browsers. E.g. recent versions of Firefox have a fixed timeout set after which the browser will stop waiting for output. Nevertheless, in such a case, the PHP process will most likely continue to run and generate the file in dmi-tcat/analysis/cache. Have a look with `ls -ctla | head` to see whether the file is present. (You can of course also try another browser such as Chrome).

Best,

Erik

**Comment by jaruizso** [comment]
I tried using Chrome (I was using Safari), and the problem persists: Cant download all or really big parts of the dataset.

On the other hand, I tried the first option, but could not get any result. Could you elaborate a bit how to configure get access to the error logs and how to configure config.php?

**Comment by ErikBorra** [comment]
Try to Google for [ubuntu php error log] and [php time_limit] and [php memory_limit] respectively.

**Comment by ErikBorra** [comment]
Any success?

**Comment by jaruizso** [comment]
Hi,

Thanks for following up. Well, I tried as you suggested but I am not very familiar. I tried to locate php.ini, but its empty. I also tried to locate config.php with /var/log/apache2/error.log but it says I have no permission. So I tried to use my username with admin (sudo) but nothing either, can't locate it.

I did not uptake the TCAT either, but this could solve the problem?

**Comment by ErikBorra** [comment]
Hi @jaruizso,

do you know somebody who is experienced in managing linux machines? If so, it's easiest to ask him/her to help you. If not, please let us know which OS you are using (e.g. Ubuntu or Debian) and whether you are running this on a self-managed PC or server, or on a cloud service like Amazon EC2.

Best,

Erik

**Comment by jaruizso** [comment]
I will try to seek help...let see

Meanwhile, its the Debian version 8.0 I am using. I installed with automatic installation on an Amazon EC2, the micro one :)

**Comment by dentoir** [comment]
Yes, please ask help, this really looks like a server problem. Also, realise this t2.micro is quite a small VPS to run TCAT on, comparable to the Raspberry PI. Your system is quite likely to run our of memory in such a configuration.

**Comment by ErikBorra** [comment]
Any update on this @jaruizso ?
