### ISSUE TITLE
DMI-TCAT in a Docker container

### ISSUE THREAD

**Issue by theneva** [digitalmethodsinitiative/dmi-tcat#184]
Hello, there!

My university uses DMI-TCAT for research and education, so thanks for building this application!

We needed more than one installation on the same host, so I built a [Docker](http://docker.com/) image for DMI-TCAT. The image is reusable (to an extent) through loading a few of `config.php`'s values from environment variables. In other words, it is possible to `docker pull` the image and run it multiple times with different environment variables and port bindings.

I don't know this project very well, however, so I would love some feedback from you. Have I done anything weird? The repo is available at https://github.com/theneva/dmi-tcat-docker.

Any thoughts are welcome! Of course, just let me know if you wish to take ownership of the repo and [Dockerhub image](https://hub.docker.com/r/theneva/dmi-tcat/). It's hackish right now, though: For example, the HTTP Basic login info cannot be changed without building the image. I'm still working on it!

**Comment by theneva** [comment]
As a side note, it would be A+ if the default config.php example script looked for environment variables. That way I wouldn't have to keep a copy of it in the container repo! [The Twelve-Factor app](http://12factor.net/) and all that. 😃

**Comment by ErikBorra** [comment]
Hi @theneva,

thanks for pointing us this fork! We will try to take a look at it and comment on it in the next few days.

Best,

Erik

**Comment by ErikBorra** [comment]
Note, btw, that we also have a [one-line installation script](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Installation-Guide#automated-installation) for Ubuntu and Debian. What would be the added value of a Docker image? (As of yet I have no experience with Docker images.)

**Comment by dentoir** [comment]
Hi @theneva 

This is an interesting project. I wasn't familiar with Docker until I checked it out this morning.

Is your primary purpose for using docker an authentication lockout (to be able to have different groups of researcher see only their own bins), or are you trying to achieve multiple capture roles at the same time. If so, I think you will run into the problem of having multiple outgoing connections to the Twitter API using the same source IP address. Twitter will disconnect those connections. (We have working code to implement multiple capture roles at the same time using socat tunnels, but it is not documented yet. Let us know if you are interested).

Like @ErikBorra suggested, one way to keep this Docker image synchronized with progress made on TCAT and any possibly new dependencies, would be to use the auto-installer from within Docker itself. I think this should work, you can run it fully in batch mode, passing environmental variables in a quite similar manner as docker allows.

Best,

Emile

**Comment by ErikBorra** [comment]
Hi @theneva,

any update on this?

Best,

Erik

**Comment by theneva** [comment]
Sorry sorry sorry @ErikBorra. I got super busy finishing my master thesis, but I'm back in business now.

I began writing a reply, but ended up with an unfinished list of issues I found with the install script instead. I'll look at it later this week, and submit new issues as appropriate…

This one can be ignored until I've finished that. Sorry again for my lack of response!

**Comment by ErikBorra** [comment]
Awesome, looking forward to your response.

**Comment by ErikBorra** [comment]
Any update on this @theneva?

**Comment by theneva** [comment]
@ErikBorra: late again… Finally done with things, so I'll have another go this week.

**Comment by theneva** [comment]
So, a lot of things have changed since I last tried this. A new problem of missing `lsb_release` in the standard Ubuntu Docker images made this even harder to do properly 😃

The good news are that it looks like a few of the problems I encountered earlier have been resolved in the meantime.

My main issue of not being able to set the various parameters like keys at runtime persists, though, and I don't think this can be done by running the install script as I build the image. Back to the drawing board, I'll post here when I get anywhere.

**Comment by dentoir** [comment]
Hi @theneva 

In the meantime, keys can now be set in the install script, as can a lot of other things by using a configuration file and passing the -c option.

**Comment by ErikBorra** [comment]
Hi @theneva, 

closing this issue as there has been no update for quite a while. Feel free to reopen.

Best,

Erik

**Comment by thierrymarianne** [comment]
FYI, I've written few instructions in `bash` 
 - to build an `Docker` image and
 - to run a container from this image

Some volumes are mounted when running the container 
 - to ease the development of  the `dmi-tcat` codebase (`/src`) from the host,
 while interpreting it from within the container
 - to debug the application (`xdebug` extension for PHP has been configured)
 - to keep the database files available even after the container has been stopped (`/volumes/mysql`)

The one-line installation script works perfectly well but its execution implies having all the dependencies installed on the host. Provided one would already be running versions of PHP / MySQL, which are not officially supported from a host machine, having the application running in relative isolation might be of use to some  (above all to be able to rely on the version of PHP and other dependencies, for which the application has been battle-tested against).

https://github.com/thierrymarianne/dmi-tcat
