### ISSUE TITLE
DMI-TCAT Not reading tweets though total showing in dataset

### ISSUE THREAD

**Issue by thmunson** [digitalmethodsinitiative/dmi-tcat#185]
DMI-TCAT is not recognizing the tweets that have been archived. For example, I have 13,000+ tweets in a dataset (and that number appears in the pull-down menu), but the graph shows 0 tweets. When I export the dataset, no tweets appear in the file.

I'm running TCAT on Ubuntu on Amazon EC2. 

Thanks!
Bill

**Comment by ErikBorra** [comment]
Have you set the start and end date properly in the analysis interface?

**Comment by thmunson** [comment]
Thanks for getting back. From a screen shot I had taken, I think that may be the issue. Now, however, I'm getting a "could not connect" error, though my instance says it is running. Very odd.

**Comment by thmunson** [comment]
I uninstalled TCAT and am now trying to install it on an Amazon Linux instance but get an error when adding the line: sudo apt-get install curl. Error reads: sudo: apt-get: command not found

**Comment by dentoir** [comment]
Hi @thmunson 

I strongly recommend using either a Ubuntu or a Debian image on Amazon. Amazon Linux would require you to manually install TCAT (using the Wiki instructions).

On a sidenode, I benchmarked TCAT on Amazon Linux (about a year ago) and surprisingly Debian/Ubuntu outperformed it (yes, on Amazon's own infrastructure).

**Comment by thmunson** [comment]
Thanks, @dentoir.
 
I was able to locate a Debian instance via the Amazon AMI. I had to run 

`udo apt-get update && sudo apt-get install php5-curl`

so I could use curl.

The install went through just fine.

The install issue was with the date range. 

Thanks for all your help!

Bill
