### ISSUE TITLE
TCAT instance will no longer load 

### ISSUE THREAD

**Issue by ibrahimtaoube** [digitalmethodsinitiative/dmi-tcat#186]
The tcat instance will just display "144.6.237.40 is currently unable to handle this request.". I have checked the access_log and it displays the following error. Is there a way to resolve this issue and rescue my instance?

Thank you!

`PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /var/www/html/dmi-tcat/capture/common/functions.php:11\nStack trace:\n#0 /var/www/html/dmi-tcat/capture/common/functions.php(11): PDO->__construct('mysql:host=loca...', 'twittercapture', 'twittercapture', Array)\n#1 /var/www/html/dmi-tcat/capture/common/functions.php(238): pdo_connect()\n#2 /var/www/html/dmi-tcat/capture/index.php(12): create_admin()\n#3 {main}\n  thrown in /var/www/html/dmi-tcat/capture/common/functions.php on line 11`

**Comment by dentoir** [comment]
TCAT can no longer connect to your MySQL server, says the error message. Did you do any reconfiguration of update on your system? I'm not sure what environment you are working in? In a lot of Linux environments you can find MySQL server error messages in /var/log/mysql/error.log
Are you capable of manually loging into your MySQL server using the command-line or phpmyadmin?

**Comment by ErikBorra** [comment]
Hi @ibrahimtaoube,

any updates on this?

Best,

Erik

**Comment by ibrahimtaoube** [comment]
I haven't been able to reproduce the issue anymore.
