### ISSUE TITLE
Automating tweet exports and purging

### ISSUE THREAD

**Issue by hoylen** [digitalmethodsinitiative/dmi-tcat#189]
We need to implement a way to automate the process of extracting tweets etc. from TCAT. That is, without needing a human to manually click on links in a Web browser. The goal is to regularly pull out the capture tweets and then to remove them from the database: to backup the captured data in TSV format for processing, and to keep the database from growing too large.

What do you think is the best approach to implement this?

Some possible options:
- Implementing a RESTful HTTP API.
- Implementing a command line program to export tweets:
    - Implemented as a Python program;
    - Implemented as a PHP program;
    - Modifying the existing PHP scripts to be dual mode scripts: that can be invoked either from the command line or from a HTTP request (some of the PHP scripts already do this, even if it is to just print out a message when run from the command line);
   - Implemented as a shell script (the attached
[tweet-export.txt](https://github.com/digitalmethodsinitiative/dmi-tcat/files/256062/tweet-export.txt) is an experimental shell script along these lines, but it uses fragile HTML screen-scraping); or
- Some other approach.

Other issues:

- The size of the exported file could be a problem. So we will probably also need some way to determine the available date range of the query bin, so the extraction process can perform multiple tweet exports over the date range (e.g. perform a separate export for each day).

- A machine readable approach to list all the available query bins would be nice too. That way, we can implement an export-all-tweets-from-all-query-bins function without needing to manually identify the names of the query bins.

- How do the files that get generated in $TCAT_DIR/analysis/cache/ get deleted. If they don't get cleaned up, we are going to run out of disk space. Maybe there is a way to stream the output (over HTTP or to a Unix pipe) so it doesn't have to be written to disk, or can be written to a different directory (e.g. to an NFS  mounted external storage).

- It would also be good to be able to "purge" the already captured tweets from the database. And to be able to automate that operation. Right now, a work around could be to delete the query bin and recreate it.

What do you think is the best approach for adding such functionality to TCAT, so that it fits into the overall design? Already it uses PHP, Python and Bash scripts in different ways.

**Comment by dentoir** [comment]
Hi @hoylen,

The discussion surrounding automated (API based) interfacing to TCAT is certainly relevant, but properly implementing it will require some major refactoring of the source code, regardless of the method we decide to use.

There are at least four big projects on the medium-term wishlist for TCAT improvement:

* Implementing PHP 7 support
* Implementing ACL for more complex user management, possible using Oauth
* REST-like, API based access to TCAT
* Exporting all TCAT captured data as JSON for further processing, or
even storing TCAT data itself (in JSON) in a NoSQL or Postgres database.

At the same time, there are many other small improvements we would like to make. At the moment, we simply do not have the budget, nor the manpower to do it all.

Unless we get extra funding and/or manpower from somewhere, it is not likely we will be able to work on most of the items on the list before the end of the  summer. At the Digital Methods Initiative, we have the [Summer School](https://wiki.digitalmethods.net/Dmi/SummerSchool2016) coming up which will require our full attention.

I think adding a new option to mod.export_tweets.php (and, to be consistent, to all comparable modules), allowing the TSV/CSV files to be fpassthru'd() to the browser/curl immediatly, would take care of the  problem of having to scrape HTML. You would simply need to strip the first line of the TSV result to append the data. Additionally, adding a truncate bin option in capture/ could be useful to avoid having to delete and  re-create bins.

If I'd want to implement a regular, automatic export to TSV format, I'd  probably access the mod.exports_tweets.php every midnight remotely, and  query tweets from exactly the previous day. The rule of the thumb is: 1 million tweets take up approximately 1 gigabyte of diskspace, including indexes.

To automatically clean-up the dmi-tcat cache files, the follow command can  be placed in the crontab of the appropriate user. It removes all files older than 7 days. We may want to document that.

find /var/www/dmi-tcat/analysis/cache -mtime +7 -exec rm -f {} \;

Thanks for your useful suggestions and solutions. We hope that our current time-constraints will not limit your use of TCAT. We of course welcome further suggestions and pull requests :)

**Comment by hoylen** [comment]
Ok. I'll have a look at modifying _mod.export_tweets.php_, without doing "major refactoring".

> Additionally, adding a truncate bin option in capture/ could be useful to avoid having to delete and re-create bins.

Would that option simply need to delete all rows from the 7 query bin tables, or does it need to do more than that? I suspect it needs to update the capture period, or would deleting all the rows do that?

> To automatically clean-up the dmi-tcat cache files, the follow command can be placed in the crontab...

I think we should add that to the _tcat-install-linux.sh_ script. Though I think 7 days is too long (especially if there are many exports and the disk is small): 5-10 minutes sounds more reasonable - assuming users downloaded the data immediately after asking for it.

But if _export_tweets.php_ wrote the CSV/TSV directly to the HTTP response, there would be no need to have cache files. Is there a reason why cache files were used?

**Comment by hoylen** [comment]
I've got it to export without needing to write to a file in the _capture/cache_ directory (in pull request #190).

Should I try and change all the other analysis functions to do the same? If that could be done, I assume there won't be a need for a cache directory, and so a _cron_ job to regularly clean it out won't be needed.

_P.S. I'm now tackling the purge tweets functionality. Any documentation on the database design? I want to purge all the tweets in a specified time period. That way an external process can export-and-purge on a regular basis. A simple "purge every tweet" risks loosing any new tweets that might arrive while the operation is running._

**Comment by hoylen** [comment]
Proposed API in pull request #205.

Tweets can be purged: all or restricted to a given time period. But I haven't touched any of the export functions, which can only export all tweets.

Ideally, you want to nominate the time period for exporting. So what gets purged is exactly the same as what was exported. This is only a problem if exporting/purging a running query bin. Currently, there is a race condition, since you don't know exactly when the exporting actually starts of finishes. So new tweets which arrive after exporting started will either be lost (if everything is purged) or duplicated (if purging up to a fixed time before the export started).

Large export files can still be a problem. But this is no longer a problem for the server (since after pull request #190 the data is written directly to the HTTP response instead of into a cache file). And if it is a problem for the client, more frequent exporting+purging will mean each individual export is smaller.

**Comment by hoylen** [comment]
Feature request has been satisfied by the pull request being accepted. Closing issue.

The direct export (i.e. without first writing to a file in the cache directory) has only been used for the seven "Tweet exports" (i.e. those links named "download"). The same approach can be used for the other export functions (i.e. those links named "launch"). If that is done, I suspect the cache directory is no longer needed (and users don't need to worry about cleaning it out to avoid running out of disk space). But I won't be making those changes, since I don't really know if there are any side effects or reasons for the cache directory.
