### ISSUE TITLE
MySQL Configuration Issue - MySQL server has gone away

### ISSUE THREAD

**Issue by ibrahimtaoube** [digitalmethodsinitiative/dmi-tcat#192]
Hi,

I reported in another issue that my MySQL issue was resolved by me updating the following settings in the my.cnf to the following 

sort_buffer_size = 2M
max_allowed_packet = 256M
myisam_sort_buffer_size = 64M

However, I was running another instance today the with the same MySQL settings above and I got the following error displayed in the error_log. It would be appreciated if you can offer any advice about what my MySQL settings should be to avoid the following error? What MySQL settings have you used in the past to eliminate this issue?

`[Wed May 18 03:26:56 2016] [error] [client 202.7.176.94] PHP Warning:  PDOStatement::execute(): MySQL server has gone away in /var/www/html/dmi-tcat/capture/common/functions.php on line 280, referer: http://137.92.59.246/dmi-tcat/capture/
[Wed May 18 03:26:56 2016] [error] [client 202.7.176.94] PHP Warning:  PDOStatement::execute(): Error reading result set's header in /var/www/html/dmi-tcat/capture/common/functions.php on line 280, referer: http://137.92.59.246/dmi-tcat/capture/
[Wed May 18 03:26:56 2016] [error] [client 202.7.176.94] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/html/dmi-tcat/capture/common/functions.php:280\nStack trace:\n#0 /var/www/html/dmi-tcat/capture/common/functions.php(280): PDOStatement->execute()\n#1 /var/www/html/dmi-tcat/capture/index.php(12): create_admin()\n#2 {main}\n  thrown in /var/www/html/dmi-tcat/capture/common/functions.php on line 280, referer: http://137.92.59.246/dmi-tcat/capture/
[Wed May 18 04:30:43 2016] [error] [client 202.7.176.94] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 145 Table './twittercapture/test_tweets' is marked as crashed and should be repaired' in /var/www/html/dmi-tcat/capture/query_manager.php:724\nStack trace:\n#0 /var/www/html/dm`

**Comment by ErikBorra** [comment]
Hi @ibrahimtaoube,

you have a crashed mysql table. We only get this when we have an unexpected power outage. In any case, you should log into your mysql console and run the following command: `mysql repair test_tweets`. When that's finished, and if no other tables are crashed, everything should be back to normal.

Best,

Erik

**Comment by ibrahimtaoube** [comment]
Hi,

So, there are no settings I can change in the MySQL config that will avoid
this issue? So its not related to MySQL being able to handle the twitter
data coming in?

Thanks for the help

On Wednesday, 18 May 2016, Erik Borra <notifications@github.com> wrote:

> Hi @ibrahimtaoube <https://github.com/ibrahimtaoube>,
>
> you have a crashed mysql table. We only get this when we have an
> unexpected power outage. In any case, you should log into your mysql
> console and run the following command: mysql repair test_tweets. When
> that's finished, and if no other tables are crashed, everything should be
> back to normal.
>
> Best,
>
> Erik
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalmethodsinitiative/dmi-tcat/issues/192#issuecomment-219969732>
>


-- 
Ibrahim Taoube | Senior Tester | Intersect
ibrahim@intersect.org.au | 0415664758
Level 12, 309 Kent St, Sydney NSW 2000, Australia

**Comment by ErikBorra** [comment]
We recommend using the script available on http://mysqltuner.com to tweak your mysql config, and to set both the sort_buffer_size and myisam_sort_buffer_size as big as possible.

Crashed tables will not be avoided by this (but a table will only crash when TCAT tries to write something to a table and if you have a power outage at the same time).

**Comment by ibrahimtaoube** [comment]
Hi,

Ok thank you. So pretty much this issue is unavoidable?, no specific MySQL
settings will entirely eliminate this issue giving its related to something
external to those settings?

Appreciate the help.

On Wednesday, 18 May 2016, Erik Borra <notifications@github.com> wrote:

> We recommend using the script available on http://mysqltuner.com to tweak
> your mysql config, and to set both the sort_buffer_size and
> myisam_sort_buffer_size as big as possible.
>
> Crashed tables will not be avoided by this (but a table will only crash
> when TCAT tries to write something to a table and if you have a power
> outage at the same time).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalmethodsinitiative/dmi-tcat/issues/192#issuecomment-219993212>
>


-- 
Ibrahim Taoube | Senior Tester | Intersect
ibrahim@intersect.org.au | 0415664758
Level 12, 309 Kent St, Sydney NSW 2000, Australia

**Comment by ErikBorra** [comment]
correct.

**Comment by ibrahimtaoube** [comment]
Hi,

I have talked to our system administrators and they have assured me the virtual machine will never lose power. 
I have looked at the mysql log and found the following. This error is displayed from the time the app is storing tweets. Is there any other log that might be useful to diagnose this issue? I know you can repair the table but the clients using this app want to ensure that mysql never goes down for their research. Or is this mysql error a known issue in TCAT?

Thank you for the jelp

2016-05-18T03:27:17.102762Z 42 [ERROR] /usr/sbin/mysqld: Incorrect key file for table './twittercapture/test_tweets.MYI'; try to repair it
2016-05-18T03:27:17.102822Z 42 [ERROR] /usr/sbin/mysqld: Incorrect key file for table './twittercapture/test_tweets.MYI'; try to repair it

**Comment by ErikBorra** [comment]
Hi @ibrahimtaoube,

your key file is corrupt, try to repair it with `repair table test_tweets` from the mysql cli. We have never heard about crashes without power outages or running out of disk space. Also, make sure your tmp location for mysql is sufficiently big.

Best,

Erik

**Comment by ElCep** [comment]
Hi, 
For me `repair table ` doesn't work ... so a would try to re-install dmi-tcat. Is there a way to save tables and import them in the fresh install app ? Because I don't know if I can dump all tables without 'tcat_*` tables?
thank you 

Etienne

**Comment by ErikBorra** [comment]
Hi @ElCep,

why does a repair table not work? If a table is crashed, there is no way to save and import them.

Best,

Erik

**Comment by brendam** [comment]
I had two crashed tables after an outage last Friday. I'm using the Australian Nectar (http://nectar.org.au) cloud server instances and apparently the node my server instance was on had a hardware problem and  was restarted. In the end I used `mysqlcheck -u root -p --auto-repair --check --all-databases` to recover the crashed tables and check all the rest.

**Comment by ibrahimtaoube** [comment]
So I have set the following MySQL variables to the following values and it seems to have solved the issue.


max_allowed_packet = 128M
myisam_sort_buffer_size = 256M
key_buffer_size = 128M
tmp_table_size = 64M
max_heap_table_size = 64M
join_buffer_size = 2M
