### ISSUE TITLE
Handling of $ signs

### ISSUE THREAD

**Issue by theoaraujo** [digitalmethodsinitiative/dmi-tcat#199]
Hi all,

It seems that query bins using the $ sign to tweets associated with stock information (e.g., $nke) do not work? I have now two bins, one with (1) nke as a query, and another with (2) $nke, and tweets containing $nke appear in the query bin 1, bur not 2?

Should I be using any additional characters to build the query? 

Thanks,
Theo

**Comment by kevinbsc** [comment]
Any solutions on this issue?

**Comment by dentoir** [comment]
This should now be fixed in master, please re-open if you still experience a problem!
