### ISSUE TITLE
¿How does it work one percent sample?

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#200]
Can i track some query and get one percent sample? or its random sample?

Regards!

**Comment by ErikBorra** [comment]
Hi Patricio, 

You can either use track and get all tweets for a (set of) keywords, or you can use one percent and get a random 1% sample of tweets. Take a look at the documentation for more info.

Best,

Erik

Op 30 mei 2016 22:02 schreef Patricio Segovia <notifications@github.com>:

Can i track some query and get one percent sample? or its random sample?

Regards!
