### ISSUE TITLE
Unknown SSL protocol error in connection to stream.twitter.com:443

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#201]
From today i get this error when i try to run s track query.

```
    'error' => 'Unknown SSL protocol error in connection to stream.twitter.com:443 ',
    'errno' => 35,

```

any idea how to fix it?

Regards!

**Comment by ErikBorra** [comment]
Hi @psegovias,

could it be an error 135 as specified [here](https://dev.twitter.com/overview/api/response-codes)? That is, is the time of your machine in sync with Twitter's time?

Best,

Erik

**Comment by dentoir** [comment]
Any update on this?

**Comment by psegovias** [comment]
Sorry for not answer, maybe was the time, cuz in my country we made a time change.
