### ISSUE TITLE
Query bin active - but only data from 8 days 

### ISSUE THREAD

**Issue by ampossel** [digitalmethodsinitiative/dmi-tcat#202]
Hi there,

In the capture section it looks like my query bin is still running until now "2016-04-20 19:50:00 - now".
But if I look at the analysis section, data is only shown from 20-4-2016 until 27-4-2016 (one week). How is this possible?

Thanks for the help in advance!

**Comment by ampossel** [comment]
Extra information:

You currently have 7 query bins and are tracking 302 out of 5000 possible user ids.

Your latest rate limit hit was on 2016-03-07 23:03:26

My datasets in total only contain 4700 tweets, so it can't be the limit rate?

**Comment by ampossel** [comment]
Anyone, please? It's for my masters thesis

**Comment by jaruizso** [comment]
Hi there! Can you include some captures?

**Comment by ampossel** [comment]
Thanks for responding Javier!

I was trying to capture tweets from politicians in the Netherlands and Belgium, from april the 20th until now. Unfortunately, I saw in the 'analysis' part of DMI-TCAT that I only captured 8 days of tweets.. 


<img width="947" alt="dmitcat3" src="https://cloud.githubusercontent.com/assets/15876206/15805805/ba5d78a0-2b34-11e6-91be-5e2bb4423ace.png">
<img width="903" alt="dmitcat1" src="https://cloud.githubusercontent.com/assets/15876206/15805807/c4cdb32c-2b34-11e6-8928-afd7e5d7da2a.png">

**Comment by ampossel** [comment]
I tried to create another bin with the same ID users (politicians), but it's not capturing anything

<img width="942" alt="dmitcat4" src="https://cloud.githubusercontent.com/assets/15876206/15805816/17d639cc-2b35-11e6-95b1-94766ff6c02d.png">

**Comment by ErikBorra** [comment]
Hi @ampossel,

what does your follow log say?

Best,

Erik

**Comment by dentoir** [comment]
Hi @ampossel 

Do you have the log output, otherwise we can't help you.

**Comment by dentoir** [comment]
I'm assuming the problem has been resolved for now, please re-open if it is not the case.
