### ISSUE TITLE
Auto-installer needs to install ntpdate

### ISSUE THREAD

**Issue by dentoir** [digitalmethodsinitiative/dmi-tcat#204]
Twitter returns a crypted 401 Authorization Denied whenever the TCAT system clocktime is out-of-sync with the Twitter servers, around 5-10 minutes will be enough.

The auto-installer should install and configure ntp so this will not occur.

Also, add this as a FAQ to the Wiki.

**Comment by hoylen** [comment]
My installations of Ubuntu 15.10 has _systemd_, and its `timedatectl` command indicates that network time synchronisation is already running. I suspect _systemd_ comes with its own NTP client and it is enabled by default.

**Comment by dentoir** [comment]
We can assume our auto-installations are correct. I've updated the documention, section 'common problems'.
