### ISSUE TITLE
autoupdate code

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#207]
Hi,

just read the documentation how to set autoupdate. I added the following lines to my config.php:

define('AUTOUPDATE_ENABLED', true);
define('AUTOUPDATE_LEVEL', 'expensive');

I also tried 'trivial' unsuccesfully and keep getting the following message: "A newer version of TCAT is available, containing important updates. You are strongly recommended to upgrade via git pull. Please read the documentation for details. [ commit #32e3ae5... - Execute set time_zone after initialising MySQL connection ]"

Is there any time-interval for updating in the background? Or should I activate the update process with some code line?

Any suggestions?

**Comment by dentoir** [comment]
Can you look into your logs/ directory and see if there is a file called upgrade.error.log there, it should contain information on your upgrade process.

If it not there, can you dump a portion of your controller.log file?

**Comment by ErikBorra** [comment]
Any update on this?

**Comment by arnoutponsioen** [comment]
Reinstalled DMI-TCAT. Now seems to work fine.
