### ISSUE TITLE
PD0Exception when importing json (fixed)

### ISSUE THREAD

**Issue by fubespu** [digitalmethodsinitiative/dmi-tcat#208]
Hi guys, 

I tried to import two big json files (~5GB) with the import-jsondump.php script. It starts just fine, then I got the following error: 

_PHP Notice:  Undefined index: id_str in /var/www/dmi-tcat/capture/common/functions.php on line 1334
PHP Notice:  Undefined index: created_at in /var/www/dmi-tcat/capture/common/functions.php on line 1335
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1336
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1337
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1338
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1339
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1340
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1341
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1342
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1343
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1344
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1345
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1346
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1347
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1348
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1349
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1350
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1354
PHP Notice:  Undefined index: source in /var/www/dmi-tcat/capture/common/functions.php on line 1355
PHP Notice:  Undefined index: user in /var/www/dmi-tcat/capture/common/functions.php on line 1356
PHP Notice:  Undefined index: geo in /var/www/dmi-tcat/capture/common/functions.php on line 1359
PHP Notice:  Undefined index: text in /var/www/dmi-tcat/capture/common/functions.php on line 1366
PHP Notice:  Undefined index: retweet_count in /var/www/dmi-tcat/capture/common/functions.php on line 1372
PHP Notice:  Undefined index: favorite_count in /var/www/dmi-tcat/capture/common/functions.php on line 1373
PHP Notice:  Undefined index: in_reply_to_user_id_str in /var/www/dmi-tcat/capture/common/functions.php on line 1374
PHP Notice:  Undefined index: in_reply_to_screen_name in /var/www/dmi-tcat/capture/common/functions.php on line 1375
PHP Notice:  Undefined index: in_reply_to_status_id_str in /var/www/dmi-tcat/capture/common/functions.php on line 1376
PHP Notice:  Undefined index: lang in /var/www/dmi-tcat/capture/common/functions.php on line 1382
PHP Notice:  Undefined index: truncated in /var/www/dmi-tcat/capture/common/functions.php on line 1390
PHP Notice:  Undefined index: entities in /var/www/dmi-tcat/capture/common/functions.php on line 1414
PHP Warning:  Invalid argument supplied for foreach() in /var/www/dmi-tcat/capture/common/functions.php on line 1414
PHP Notice:  Undefined index: entities in /var/www/dmi-tcat/capture/common/functions.php on line 1471
PHP Notice:  Undefined index: entities in /var/www/dmi-tcat/capture/common/functions.php on line 1472
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1' in /var/www/dmi-tcat/capture/common/functions.php:1559
Stack trace:
#0 /var/www/dmi-tcat/capture/common/functions.php(1559): PDOStatement->execute()
#1 /var/www/dmi-tcat/import/import-jsondump.php(69): Tweet->isInBin('data')
#2 /var/www/dmi-tcat/import/import-jsondump.php(45): process_json_file_timeline('/media/lab/Disc...', Object(PDO))
#3 {main}
  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 1559_

I checked the query bin on the web interface and it imported about 11.514 Tweets (there should be far more).

Any clue on how to fix this ?. Thanks in advance !.

PS: I'm not that advanced programmer or so... just using this software for research purposes.

**Comment by fubespu** [comment]
No solution for this ?.

**Comment by fubespu** [comment]
Just find out that you updated the functions.php !

https://github.com/digitalmethodsinitiative/dmi-tcat/commit/8d872acb32f0d7315eb84f84eb0c962a07a4723d

I'll tell you if it fixed my problem.

However, thank you thank you thank you ! ;-)

**Comment by fubespu** [comment]
Ok, it dind't fix it.

**Comment by ErikBorra** [comment]
Hi @fubespu,

it seems that the JSON is not fully correct. E.g. quite a few times, the user is missing. Where did you get that JSON?

Best,

Erik

**Comment by fubespu** [comment]
Hi @ErikBorra, 

the JSON was obtained using a Python script (stream listener). During caption it gave me errors randomly, which made the script stop... I just had to restart it a few times. Any chance to fix this ?.

Thank you,

Fab.

**Comment by ErikBorra** [comment]
Hi Fab,

I'd write try/catch (or if/then) statements around the lines in /var/www/dmi-tcat/capture/common/functions.php that are giving you errors. Then, instead of trying to write the incomplete tweets to the database, store the id_str for each of those tweets in a file (one line per id). Then feed that file to /var/www/dmi-tcat/capture/lookup/lookup.php to reretrieve those tweets via the Twitter API.

Best,

Erik

**Comment by fubespu** [comment]
Hi Erik,

I'll try that this afternoon, as soon as I get home :). 

Thank you very much,

I'll keep you updated.

Fab.

**Comment by fubespu** [comment]
Hi again Erik,

when running the lookup.php script in capture/ids/ it gives follow error:

_PHP Fatal error:  Allowed memory size of -2147483648 bytes exhausted (tried to allocate 3733992516 bytes) in /var/www/dmi-tcat/capture/ids/lookup.php on line 32_

My guess is that it's related to the size of the JSON file I'm trying to import (~4GB). I set the server memory to unlimited but the error persits (now giving an other memory size limit).

Maybe configure the json-dump.php script as streamer, so it doesn't read the file as a block, would help ?.
Or just ignore the uncompleted tweets ?. 

Thanks.

**Comment by ErikBorra** [comment]
Hi @fubespu,

you should parse out _only_ the ID of the tweets that give you errors on the json import script. Those should be in a file with one ID per line (and nothing else). That file can be feed to lookup.php

Best,

Erik

**Comment by fubespu** [comment]
Dear @ErikBorra, 

first of all, let my apologize for my late response. I've been trying to solve this problem in different ways for the past month. Now, I'm really messed up... and quite desperate.

There a some things that don't work for me in your suggested solution.

1. The "id_str" isn't recognized by parse-csv.php or lookup, nor in csv file or in flat txt. The expected format is http://twitter.com/sunit/status/129951691670949888 which is not present in a json dump. Ok, I could reconstruct it with the ID and the SCREEN_NAME parameters... but, honestly, I don't know how to do that. Moreover, I'm afraid that that procedure would bias the data (no RT, and other info would be stored). 
2. I can't locate the exact tweets that are incomplete. 
3. I noticed that the import-jsondump.php script stops the time it finds an incomplete tweet... My question is: Can't it just skip that tweet and forward with the next one ?.

Thank you for your time, 
Waiting for your answer.

**Comment by dentoir** [comment]
Hi @fubespu 

Could you send use the first few lines on which your JSON import chokes (and a few okay lines). For example: it looks like the 11515th tweet in the JSON file caused problems. If created_at is missing, I assume your JSON is malformed though. A quick fix would be to edit import-jsondump.php like so:
```
            try {
                $t->fromJSON($tweet);
            } catch (Exception $e) {}
```

Yes, we could edit the script to record errors and do some accounting of them.

**Comment by fubespu** [comment]
Hi @dentoir,

My *.json capture has 64716 lines (which means it has the same number of tweets), but it only captures the first 23128. So, assuming the jsondump script reads line per line starting from line one, this means that the first "incomplete/broken" tweet is number 23129. 
Unfortunately, I can't copy the whole Tweet into here... (it's far too large...). I'm interested in the solution you proposed. 

But for now, can you tell me how to edit the scrip to record errors and incomplete tweets ?, so that we can exactly locate which tweets are missing. 

Thank you very much for your time and patience. 

Fab.

**Comment by fubespu** [comment]
btw,

I tried the try function in the import-jsondump.php but it didn't work... still stops while reading the incomplete tweet. It's very probable that I didn't use it properly.

Here's what I did:
Edited line 68:
`            $t->fromJSON($tweet);` 
to that what you mentioned.

Thank you again,

PS: If you want, send me your email via private messege and I'll send you the json file I'm using. Maybe that would be the fastest way to solve this problem and edit the script for preventing this from happening in the future to other users when importing json files captured by stream listener to DMI-TCAT.

**Comment by dentoir** [comment]
Hi @fubespu 

We've been on holiday, and catching up on existing issues now. To make the import script more resilient, can you edit the following line in the same import-jsondump.php file (you can keep the modification you already made in-place). Find the IF code block beginning with the line containing `if (!$t->isInBin($bin_name)) {` and put it in try/catch like this:

```
      try {
            if (!$t->isInBin($bin_name)) {
                $tweetQueue->push($t, $bin_name);
                if ($tweetQueue->length() > 100) {
                    $tweetQueue->insertDB();
                }

                $all_users[] = $t->from_user_id;
                $all_tweet_ids[] = $t->id;

                $tweets_processed++;
            }
      } catch (Exception $e) {}
```

By comparing the number of tweets imported with the known number of tweets in your JSON file, you can find out how many tweets were 'malformed'.

**Comment by fubespu** [comment]
Hi @dentoir and @ErikBorra, 

I'v being testing the new script this week and it works flawlessly, you guys just make my day ! :). Next drinks are on me ! (no kidding, send me your PayPal via PM :dancers: )

PD: adding the print "." between the } and } catch would be a nice idea, so the user doesn't think the script stuck somewhere :).
