### ISSUE TITLE
domain/analysis/ not responding

### ISSUE THREAD

**Issue by jaruizso** [digitalmethodsinitiative/dmi-tcat#209]
Hi there,

I am having an issue the last days when I try t log in into domain/analysis/. It is just not responding. Does not give an error or something. It it just the white page "waiting for server to respond" (according to what Chrome says). In the tab instead of "DMI Twitter Capturing and Analysis Toolset (DMI-TCAT)", it shows "reading-list://"

/capture/ works well. it loads and collects data.

I dont know if that might be because size of the database (more than 10M) tweets, or server extremely busy (i am hitting constant rate limits, so a huge quantity of data being collected), or lack of ram (server has 3,75 GB). However, checking the monitoring tools that Amazon EC2 provides, the server does not seem extremely overloaded.

Many thanks for the help!
Javier

**Comment by ErikBorra** [comment]
Hi Javier,

could you visit the analysis page again and then send the last 100 lines of your php error log?

Thanks,

Erik

**Comment by jaruizso** [comment]
Hi Eirk,

Thanks for following. My believe is that I run out of memory. My server in amazon has 3,75 Gb of ram, and the dataset contains around 15M tweets. If I open ip/analysis now,  it works properly because it opens only a day (yesterday) and the number of tweets in the last days has been much less. However, if I change the sample to the entire dataset, or where the number of tweets was very high, then it is not responding. 



root@ip-172-31-16-34:/home/admin# sudo cat /var/log/apache2/error.log
[Thu Jul 07 06:25:05.697672 2016] [mpm_prefork:notice] [pid 424] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Thu Jul 07 06:25:05.697694 2016] [core:notice] [pid 424] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jul 07 10:05:38.253280 2016] [:error] [pid 25437] [client 192.76.8.13:65005] PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/dmi-tcat/analysis/common/functions.php on line 849
[Thu Jul 07 10:05:52.002220 2016] [:error] [pid 25437] [client 192.76.8.13:65005] PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/dmi-tcat/analysis/common/functions.php on line 849
[Thu Jul 07 10:06:05.334251 2016] [:error] [pid 25437] [client 192.76.8.13:65005] PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/dmi-tcat/analysis/common/functions.php on line 849
[Thu Jul 07 10:06:14.454135 2016] [:error] [pid 25437] [client 192.76.8.13:65005] PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/dmi-tcat/analysis/common/functions.php on line 849
[Thu Jul 07 10:06:32.610264 2016] [:error] [pid 25437] [client 192.76.8.13:65005] PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/dmi-tcat/analysis/common/functions.php on line 849
[Thu Jul 07 10:07:50.862966 2016] [:error] [pid 25444] [client 192.76.8.13:65021] PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/dmi-tcat/analysis/common/functions.php on line 849
[Thu Jul 07 10:11:03.091827 2016] [:error] [pid 25444] [client 192.76.8.13:65021] PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/dmi-tcat/analysis/common/functions.php on line 849
[Thu Jul 07 10:15:17.914879 2016] [:error] [pid 25444] [client 192.76.8.13:65021] PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/dmi-tcat/analysis/common/functions.php on line 849
[Thu Jul 07 10:18:03.567680 2016] [:error] [pid 25444] [client 192.76.8.13:65021] PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/dmi-tcat/analysis/common/functions.php on line 849

**Comment by ErikBorra** [comment]
Hi @jaruizso,

The only information that is loaded/calculated on the first page of analysis is the number of tweets per data set, and the number of tweets per 'interval' given a specific data set (and possibly queries within that data set). It seems unlikely that PHP will run out of memory, unless you have specified that PHP can only use a limited amount of RAM. Rather, I think that you are running into a timeout, either from PHP, or from your browser. 

Above you have pasted the output of one of TCAT's error logs. Try to locate the error log of PHP itself and see if that indicates whether PHP has not been assigned enough RAM (through `ini_set('memory_limit',VALUE);`) or whether PHP runs into its maximum execution time (set via `ini_set(max_execution_time, SECONDS);`). Both can be increased in tcat/config.php

Hope this helps,

Erik

**Comment by dentoir** [comment]
Hi @jaruizso 

Any progress on this?

**Comment by jaruizso** [comment]
Hi there. Yes. Sorry. 

Problem solved. I just changed instance to a bigger one (with 30GB of ram) and now it process everything. Takes a bit of time, but works.
