### ISSUE TITLE
update overview results in "This site can’t be reached" error

### ISSUE THREAD

**Issue by thmunson** [digitalmethodsinitiative/dmi-tcat#210]
Hello,

I've installed DMI-TCAT on an ubuntu machine and the archive and analysis pages load and archive properly. But, when I click the "update overview" and "update graph" buttons I get a "This site can’t be reached" Error.

Trying to download tweets throws the same error message.

But, when I use the browser refresh, the page loads fine.

Thoughts?

Thanks!
Bill

**Comment by ErikBorra** [comment]
Seems like a misconfiguration in config.php. Double check that BASE_URL and ANALYSIS_URL are defined well.

**Comment by thmunson** [comment]
@ErikBorra Thanks for getting back!

Can you explain how I might check the config file? Is there a way to download it to my computer? 

And what would it look like to be defined well?

Thanks!

Bill

**Comment by ErikBorra** [comment]
Open /var/www/dmi-tcat/config.php with a text editor and make sure the values are set as follows:

```
/*
 * URL root in which dmi-tcats resides
 */
define('BASE_URL', 'http://example.com/dmi-tcat/');

/*
 * URL root in which analysis resides
 */
define('ANALYSIS_URL', BASE_URL . 'analysis/');
```

Where of course example.com/dmi-tcat is replaced by your domain or IP-address and the web folder in which you have installed tcat. Hope that helps.

Best,

Erik

**Comment by thmunson** [comment]
Hey Erik,

Sorry for the delay getting back -- I was offline for the holiday weekend here in the US.

Anyways, success! For some reason when my student set up DMI-TCAT, she entered the wrong base URL. I added the correct one and it all works now. 

Thanks for your help.

Bill

**Comment by thmunson** [comment]
Hey Erik,

So, I think I was a bit premature in my last post. Though the update button is working, but when I try to download tweets I get the following kind of error message:

The requested URL /analysis/cache/Climate_Change-20160705-20160705--------hashtag--48d5f3736a.csv was not found on this server.

Do I need to change that URL in any other location?

Thanks,
Bill

**Comment by ErikBorra** [comment]
Hi @thmunson,

could you send me what you have filled in for 
```
/*
 * URL root in which dmi-tcats resides
 */
define('BASE_URL', 'http://example.com/dmi-tcat/');

/*
 * URL root in which analysis resides
 */
define('ANALYSIS_URL', BASE_URL . 'analysis/');
```

Thanks,

Erik

**Comment by thmunson** [comment]
Hi Erik,

Sorry for the delay getting back. Here is the portion of the code you asked for:

/*
 * URL root in which dmi-tcats resides
 */
define('BASE_URL', 'http://52.42.61.186/');

/*
 * URL root in which analysis resides
 */
define('ANALYSIS_URL', BASE_URL . 'analysis/');

Right now I can access the capture and analysis pages and can update to the proper archives and graphs, but when I try to export, the files are empty. I am able to see the export file name. No data appears, however.

I should say that I did have to start and restart the Amazon instance because it basically slowed to a standstill. I did update the Public_IP to the one that I have listed here in the config file. The tweet totals do appear in the proper places so I don't think I lost any data (or, at least I hope I didn't!).

Thanks,
Bill

**Comment by ErikBorra** [comment]
Hi Bill,

if you can see the tweet totals increase you will not have lost any data. 

It seems that the directory "/var/www/dmi-tcat/analysis/cache" does not exist or is not writeable. Try the following from the command line: `sudo mkdir /var/www/dmi-tcat/analysis/cache; sudo chown www-data /var/www/dmi-tcat/analysis/cache; sudo chmod 755 /var/www/dmi-tcat/analysis/cache;`

Then, try to export a data set again

Best,

Erik

**Comment by thmunson** [comment]
Hi Erik,

Okay, that's a relief.

I took a look at the directory via my FTP client and I did see the cache folder, so I only used the latter two commands. 

I retried and it did create a file. Interestingly, however, the new file is not in the cache folder with the older files I had generated.

Thanks, again, for your help.

Bill

**Comment by ErikBorra** [comment]
Hi Bill,

the old files couldn't be generated because the permissions on the folder were not correct. This is not a problem at all, you can just redo those analyses and the files will be generated and made available for download in the cache folder. 

Best,

ERik

**Comment by thmunson** [comment]
Hi Erik,

I'm sorry, I wasn't clear. Prior to the issues I was having with the slow server I was able to create files. I see those files in the cache folder. After I stopped and restarted the the instance, I was no longer able to create files. The new ones that I just created are not appearing in the cache folder. Does is matter that they are not showing up?

Thanks,
Bill

**Comment by ErikBorra** [comment]
Hi Bill,

you say that TCAT did generate a file, but that it does not appear in the cache directory. Where then does it appear? How do you know that a file was generated?

Best,

Erik

**Comment by brendam** [comment]
I think the latest version streams some reports instead of putting them in the cache directory for download?

**Comment by ErikBorra** [comment]
@brendam: thanks! You are completely right, that was implemented by @hoylen recently!

@thmunson if you get results: don't worry, everything is fine :)

**Comment by thmunson** [comment]
@brendam @ErikBorra Okay, thank you! Yes, I'm getting results that I open in OpenOffice and Gephi. So, all is good.
