### ISSUE TITLE
could not capture tweets.

### ISSUE THREAD

**Issue by shivadcedtu** [digitalmethodsinitiative/dmi-tcat#215]
i have install DMI-TCAT in my system(ubuntu-14.04) .The system could not capture tweets.

**Comment by shivadcedtu** [comment]
![screenshot from 2016-08-05 13 41 29](https://cloud.githubusercontent.com/assets/20823490/17430660/297f0060-5b13-11e6-806c-bdb940221ae3.png)

**Comment by shivadcedtu** [comment]
![screenshot from 2016-08-05 13 41 29](https://cloud.githubusercontent.com/assets/20823490/17431063/90a56a2a-5b15-11e6-9812-0e8062ee17c4.png)

**Comment by shivadcedtu** [comment]
![screenshot from 2016-08-05 14 05 21](https://cloud.githubusercontent.com/assets/20823490/17431090/beca3be2-5b15-11e6-8876-336a2ca8a6b7.png)

**Comment by shivadcedtu** [comment]
error log :2016-08-04 09:57:06	connecting to API socket
2016-08-04 09:57:06	connecting - query array (
  'track' => 'GST',
)
2016-08-04 09:57:08	stream stopped - error tmhOAuth::__set_state(array(
   'response' => 
  array (
    'raw' => 'HTTP/1.1 401 Authorization Required
cache-control: must-revalidate,no-cache,no-store
connection: close
content-length: 266
content-type: text/html
date: Thu, 04 Aug 2016 09:57:05 GMT
server: tsa



  'streaming_metrics_interval' => 10,
    'as_header' => true,
    'force_nonce' => false,
    'force_timestamp' => false,
    'streaming_callback' => 'tracker_streamCallback',
  ),
   'request_settings' => 
  array (
    'params' => 
    array (
      'track' => 'apple,gst',
    ),
    'headers' => 
    array (
      'Host' => 'stream.twitter.com',
      'Authorization' => 'OAuth oauth_consumer_key="rmUvl0HYrj1BB9C7wWC9TVNfh", oauth_nonce="bbb0048f6713b404b4fedb5e38bd45ea", oauth_signature="R05MWbSeA2yuEEhNEXBW9%2B7x6Gc%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1470386644", oauth_token="KyJhDVpLME5wpIRgNTF5hm09wAL34ZisOJT1y1lY", oauth_version="1.0"',
    ),
    'with_user' => true,
    'multipart' => false,
    'method' => 'POST',
    'without_bearer' => false,
    'url' => 'https://stream.twitter.com/1.1/statuses/filter.json',
    'oauth1_params' => 
    array (
      'oauth_consumer_key' => 'rmUvl0HYrj1BB9C7wWC9TVNfh',
      'oauth_nonce' => 'bbb0048f6713b404b4fedb5e38bd45ea',
      'oauth_signature' => 'R05MWbSeA2yuEEhNEXBW9%2B7x6Gc%3D',
      'oauth_signature_method' => 'HMAC-SHA1',
      'oauth_timestamp' => '1470386644',
      'oauth_token' => 'KyJhDVpLME5wpIRgNTF5hm09wAL34ZisOJT1y1lY',
      'oauth_version' => '1.0',
    ),
    'prepared_params' => 
    array (
      'track' => 'apple%2Cgst',
    ),
    'basestring_params' => 'oauth_consumer_key=rmUvl0HYrj1BB9C7wWC9TVNfh&oauth_nonce=bbb0048f6713b404b4fedb5e38bd45ea&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1470386644&oauth_token=KyJhDVpLME5wpIRgNTF5hm09wAL34ZisOJT1y1lY&oauth_version=1.0&track=apple%2Cgst',
    'postfields' => 'track=apple%2Cgst',
    'basestring' => 'POST&https%3A%2F%2Fstream.twitter.com%2F1.1%2Fstatuses%2Ffilter.json&oauth_consumer_key%3DrmUvl0HYrj1BB9C7wWC9TVNfh%26oauth_nonce%3Dbbb0048f6713b404b4fedb5e38bd45ea%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1470386644%26oauth_token%3DKyJhDVpLME5wpIRgNTF5hm09wAL34ZisOJT1y1lY%26oauth_version%3D1.0%26track%3Dapple%252Cgst',
    'signing_key' => 'kqlX109zRZviXlyqtAx0RzP7Bkz6A45ZypfQ6KKVqDbyFC61Dq&XpcSMml9f7qmmwJFrPBcElCScNfe1Mc6D8NluX7lFVSjG',
  ),
   'metrics' => 
  array (
    'start' => 1470386644,
    'interval_start' => 1470386644,
    'messages' => 0,
    'last_messages' => 0,
    'bytes' => 0,
    'last_bytes' => 0,
  ),
))
2016-08-05 08:44:06	processing buffer before exit

**Comment by ErikBorra** [comment]
Hi,

either your API keys are incorrect, or the time of your server is off w.r.t. Twitter's time (see also this [issue](https://github.com/digitalmethodsinitiative/dmi-tcat/issues/142)).

Best,

Erik

**Comment by shivadcedtu** [comment]
Thank you Erik,
the issue has been solved.
