### ISSUE TITLE
import tweet-urls

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#217]
Small question about the import tutorial for tweet-urls.

1. It says that lookup.php should be configured for the bin and cvs-file to be used.
I want to use an new empty bin for storing the import-results. But when I try to create a new bin, a have to define one or more search terms. I cannot leave it empty. Should I just define a very strange search-query (like "#$%^&*()") to prevent TCAT from retrieving new tweets in the bin that should only contain tweets coming from import-results loopup-,php excecution?

**Comment by dentoir** [comment]
Hi @arnoutponsioen 

You shouldn't create a bin using the user interface at all. Just enter the new (non-existing) bin name in the lookup.php script and the bin should be created automatically for you!

Best,

Emile

**Comment by arnoutponsioen** [comment]
Hi Emile

I just did that, but still get an errors…

[cid:image001.png@01D217E8.9DAB81C0]

Settings in lookup.php:

// DEFINE LOOKUP PARAMETERS HERE
$bin_name = 'testimport';            // name of the bin
$idfile = 'testimport.csv';              // path to the input file name. the file must contain only a tweet ID on every line
Met groet,

File ‘testimport.csv’ is in the ids directory.
The .csv file is attached.

Arnout Ponsioen

DUiDT
06-81452987

Van: dentoir [mailto:notifications@github.com]
Verzonden: maandag 5 september 2016 15:41
Aan: digitalmethodsinitiative/dmi-tcat <dmi-tcat@noreply.github.com>
CC: Arnout Ponsioen <arnout@duidt.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [digitalmethodsinitiative/dmi-tcat] import tweet-urls (#217)


Hi @arnoutponsioen<https://github.com/arnoutponsioen>

You shouldn't create a bin using the user interface at all. Just enter the new (non-existing) bin name in the lookup.php script and the bin should be created automatically for you!

Best,

Emile

**Comment by ErikBorra** [comment]
Related to #218
