### ISSUE TITLE
importing tweet-urls via lookup.php

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#218]
Hi,

I have another question for importing using lookup.php.

- i have uploaded a csv file (testimport.csv) containing only tweet-urls on every line, in the capture/ids directory. The csv-file looks like this;

https://twitter.com/egtewinkel/status/765116264759095300
https://twitter.com/kwarkrutte/status/764057201652604929
https://twitter.com/luchillen/status/764030082650341377
etc.

- I created a bin called 'testimport'
- I adjusted lookup.php:
$bin_name = 'testimport';            // name of the bin
$idfile = 'testimport.csv';              // path to the input file name. the file must contain only a tweet ID on every line

When executing lookup.php, the sreen stayes empty and no tweets seem to be imported in the bin.
When executing it from command line I get the following errors:

![image](https://cloud.githubusercontent.com/assets/17899995/17777170/c1acc9fc-655f-11e6-804d-5592326b6ab7.png)

I have also saved the urls in a plain .txt file, both give the the same problems.

Any suggestions?

**Comment by dentoir** [comment]
Hi @arnoutponsioen 

Could you retry this in a setup where you have not yet created the bin through the user interface?

Best,

Emile

**Comment by arnoutponsioen** [comment]
Hi Emile

I just removed the bin 'testimport' from the admin-page and rerun the lookup.php script. I still get the same error. 

Any idea? Seems to be a 'syntax error or access violation' (it specifies 1064)? Do I need to specify logins or keys anywhere in the lookup-script? Or is the csv-file not OK? I use Twitter-urls (zie above?).

Arnout


Arnout

**Comment by ErikBorra** [comment]
Hi @arnoutponsioen,

the lookup.php script expects only ids (so not URLs), one per line. You can parse IDs from a CSV file by using the parse-csv.php script. Then feed the output from parse-csv.ph to lookup.php

Best,

Erik
