### ISSUE TITLE
Loading analysis page very slow

### ISSUE THREAD

**Issue by brendam** [digitalmethodsinitiative/dmi-tcat#219]
I'm testing the latest Launchpod DMI-TCAT deploy. Lauchpod uses CENTOS, so this problem may be related to that. On a server which is being used to track 'the' for load testing, 15 million tweets have been collected. The capture page loads quickly, but the analysis page is very slow. This is the apache access_log: (note that it took from 3:51 to 4:03 for the page to appear)

```
xxx.xxx.xxx.xxx - admin [22/Aug/2016:03:51:42 +0000] "GET /dmi-tcat/analysis/ HTTP/1.1" 200 19064 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
xxx.xxx.xxx.xxx - admin [22/Aug/2016:03:51:42 +0000] "GET /dmi-tcat/analysis/ HTTP/1.1" 200 46635 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
xxx.xxx.xxx.xxx - admin [22/Aug/2016:04:03:33 +0000] "GET /dmi-tcat/analysis/ajax.serverload.php HTTP/1.1" 200 - "http://yyy.yyy.yyy.yyy/dmi-tcat/analysis/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
xxx.xxx.xxx.xxx - admin [22/Aug/2016:04:03:37 +0000] "GET /dmi-tcat/analysis/ajax.serverload.php HTTP/1.1" 200 - "http://yyy.yyy.yyy.yyy/dmi-tcat/analysis/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
xxx.xxx.xxx.xxx - admin [22/Aug/2016:04:03:39 +0000] "GET /dmi-tcat/analysis/ajax.serverload.php HTTP/1.1" 200 - "http://yyy.yyy.yyy.yyy/dmi-tcat/analysis/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
```

This was with the tracking turned off. Is there anything I should check to try to speed this up?

**Comment by brendam** [comment]
Selecting a much small time slice (1 hour) loads quickly.

**Comment by brendam** [comment]
Wondering if when loading the analysis page restricting the default 1 day to a selection of the most recent say 100,000 tweets and putting that date range into the selection fields might keep performance better? That would put time values not just dates in the selection fields.

**Comment by ErikBorra** [comment]
Hi @brendam,

thanks for bringing this issue to our attention. We are considering to reimplement the retrieval of dataset (sizes) and line graphs - used for the analysis page, by using the new bin-phrases table. 

Best,

Erik

**Comment by ErikBorra** [comment]
This is related to #206.

**Comment by frederickjansen** [comment]
We're running into the same issue with 1% collection. Even with 32GB RAM and the recommended MySQL optimizations, loading the analysis page is pretty slow. Any queries that go beyond the default 1-day time-slice are pretty much impossible to run.
For the first problem it would be great if analysis/index.php wouldn't execute its ~5 queries immediately when loading the page, but rather load the HTML first and only then get the data asynchronously.
Not sure how you would fix the second problem beyond re-architecting the application. I have a gut feeling that MySQL isn't the best solution once you reach +50 million tweets.
