### ISSUE TITLE
favorite_count, retweet_count columns show "0"

### ISSUE THREAD

**Issue by andersoloflarsson** [digitalmethodsinitiative/dmi-tcat#222]
Dear developers,

First of all, thank you for this excellent software. I am however having some problems with the columns for favorite_count and retweet_count. When selecting "Export all tweets from selection", these columns show "0" for all tweets gathered - even for those tweets that clearly have favorites and retweets as visible on Twitter.com. 

I would appreciate any assistance you can provide me with regarding this matter.

Best,
Anders

**Comment by ErikBorra** [comment]
Hi Anders,

thanks for your kind words. favorite_count and retweet_count will always be empty when using 'track'. TCAT gets the tweets the moment they are sent by the user. At that time, no other user can have favorited or retweeted it.

Best,

Erik

**Comment by andersoloflarsson** [comment]
Ah, makes sense. Thank you for the reply.
