### ISSUE TITLE
stock ticker symbol

### ISSUE THREAD

**Issue by kevinbsc** [digitalmethodsinitiative/dmi-tcat#227]
I am curious about collecting tweets using stock ticker symbol (e.g., $aapl).
I tried the following keywords:

$aapl, $goog

Strangely, no tweets are collected. Any suggestions?

**Comment by dentoir** [comment]
We have a fix for this bug, it should be merged today ;-)

**Comment by dentoir** [comment]
This should now be fixed in master.

**Comment by kevinbsc** [comment]
Thanks!

**Comment by kevinbsc** [comment]
Is there an easy way to just upgrade the changed file (functions.php)?
or would the automatic update (trivial) does the job? 
Thanks.
