### ISSUE TITLE
Capture of Retweets after fresh install not possible

### ISSUE THREAD

**Issue by holnburger** [digitalmethodsinitiative/dmi-tcat#229]
I set up a fresh EC2 instance and installed the latest dmi-tcat by using the install script. After setting everything up I wanted to capture different user timelines so I edited to timeline.php and ran it afterwards.

Now I get the following error:
PHP Notice:  Undefined index: text in /var/www/dmi-tcat/capture/common/functions.php on line 1394
.PHP Notice:  Undefined index: text in /var/www/dmi-tcat/capture/common/functions.php on line 1394
....PHP Notice:  Undefined index: text in /var/www/dmi-tcat/capture/common/functions.php on line 1394
and so on.

Line 1394 in the functions.php is "              */
              $store_text = "RT @" . $data["retweeted_status"]["user"]["screen_name"] . ": " . $data["retweeted_status"]["text"];
          }"

After exporting the tweets it looks like that it didn't got the retweets.
78033095532xx9392,147xx0372,"2016-09-26 08:59:32",xxx,"RT @xx:",none,,,,0,9,0,de,,,,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","xxx",,,xx,"xxx",1,"xxx",http://t.co/MGGvjxjoiX,http://pbs.twimg.com/profile_images/xx/xx_normal.jpg,,,de,408,xx,96,21,90,,"2015-05-21 14:xx:xx"

It worked perfectly well last week and after setting up another two fresh instances and DMI-TCAT installations the problem still occurs.

**Comment by dentoir** [comment]
Hi @holnburger 

Thank you for the bug report. The issue you describe indeed pertained to the timeline.php script.
This issue should now have been fixed in master; ccould you update and try again?

**Comment by holnburger** [comment]
Thank you for that quick reply.
I just tested it and now it's working fine again, thank you!
