### ISSUE TITLE
Following users after capturing their timeline not possible

### ISSUE THREAD

**Issue by holnburger** [digitalmethodsinitiative/dmi-tcat#231]
I captured the timelines of about 330 users by editing /capture/user/timeline.php and running it afterwards. 
I also changed the following line to the type=follow to continue tracking future tweets of users in this bin:
$type = 'follow'; // specify 'timeline' if you want this to be a standalone bin, or 'follow' if you want to be able to continue tracking these users later on via BASE_URL/capture/index.php

Unfortunately, this doesn't seem to work. When I open BASE_URL/capture/index.php there is a link to follow users of that bin but it doesn't do anything (see screenshot). 
<img width="1066" alt="bildschirmfoto 2016-09-29 um 15 45 12" src="https://cloud.githubusercontent.com/assets/22478441/18956689/9d7dcc34-865c-11e6-8161-f67462666435.png">

When I click on "modify users" I can paste my user ids but they won't show up in the bin and won't be tracked.

Right now I'm using two separate bins, one with the timeline (3200 Tweets) and the other one for tracking, but I would prefer to have both in one bin.

**Comment by ErikBorra** [comment]
Hi @holnburger,

have you set up your server as a track or a follow machine? Have a look at the installation instructions [here](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Installation-Guide#config) for more info. 'Live' following will only work if you have set up the machine as a follow machine and are not running any track queries.

Best,

Erik

**Comment by holnburger** [comment]
Hi @ErikBorra,

it is set up as a follow machine. 
Let me explain what I wanted to do and what I failed to do, maybe that'll make it clearer.

I have about 330 user-IDs that I want to follow, but I also want their last 3200 tweets in my database to take a look into the "past" of said users. 
So I edited the capture/user/timeline.php and pasted the user-IDs at $user_ids = array('xx,xx'), also I edited the $type = 'follow' in said timeline.php.

Thereby I expected to first capture the timelines of that users and afterwards following them and capturing future tweets of that users in the same bin.
Unfortunately, that didn't work as expected. I could only capture the timelines of that users but couldn't follow them afterwards. To be able to follow them I had to make a new querybin (as you see in the screenshot) via /capture/index.php 

So right now I have two separate bins, one with the timeline (3200 tweets) and one for following them. 
I thought it could be possible to first do the capturing of the timelines and following them afterwards.

**Comment by dentoir** [comment]
Hi @holnburger 

This was a bug. It should be fixed now in master, thank for reporthing this. There is still a another issue which we need to address: you will not see the start- or end-time of user tweets after you have ran the timeline.php script. I have code to fix this but this needs to be tested a bit more.

**Comment by dentoir** [comment]
Hi @holnburger 

If you wouldn't mind, you can checkout the dentoir branch https://github.com/digitalmethodsinitiative/dmi-tcat/tree/dentoir

It is exactly the same branch as master, except it sets the proper start- or end-times for the custom CLI capture scripts, including by user id. From inside your filetree, use:

`git checkout dentoir`

**Comment by ErikBorra** [comment]
Ho @holnburger,

were you able to test @dentoir's fix?

Best,

Erik
