### ISSUE TITLE
parse-csv

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#234]
Still trying to import a bunch or twitter-urls into DMI-TCAT, but unsuccesfully.
As far as I understand the brief instruction, I first have to parse the urls to ID using parse-csv.php. Then use lookup.php import into DMI-TCAT

I have made and Excel-file The file contains a column for tweet-urls ('URL') and one dates ('DATE'). I have filled two rows with tweet-urls and dates and saved it as as CSV. 

But when executing parse-csv.php I get the error:
"Your data file does not look like a CSV file. Does it have a header line? Exiting."

Can anybody suggest how to markup the csv file correctly?
And is my two-step approach (URL-> ID using parse-csv.php and then import into TCAT using lookup.php) correctly?

Thanks!

Arnout

**Comment by ErikBorra** [comment]
Hi @arnoutponsioen,

the file should be in plain text, not an Excel file. Have you saved as CSV from Excel? Could you send an example file?

Best,

Erik

**Comment by arnoutponsioen** [comment]
Yes, I saved as a CSV file from Excel. 
[testimport4.xlsx](https://github.com/digitalmethodsinitiative/dmi-tcat/files/508301/testimport4.xlsx)
CSV nor TXT is allowed to upload here. So I upload a PPTX file and pasted the tekst from the csv file:

Goal is to import the tweet-urls to dmi-tcat. Hope you can help me with that!

URL;date
https://www.twitter.com/arnoutponsioen/status/781568421309870081;16-1-2016
https://twitter.com/arnoutponsioen/status/781555001156132864;16-3-2016

**Comment by ErikBorra** [comment]
Hi @arnoutponsioen,

it won't work with Excel. Only CSV / plain-text. Nothing we can or will do about that.

Note, btw, that your example lines are semi-colon separated, and not comma separated.

Best,

Erik

**Comment by arnoutponsioen** [comment]
Hi Erik,

Yes, I understand that it won't work with excel. I just added the file as an example... I used a csv file with the text as pasted in the message. You say I must use comma separated markup? That would work? I think I tried that too, but no success. 

And is the header-line OK? (URL, Date). Or does it not make any difference?

Last: could you be so kind to send/provide me a txt file that should work or does work with your installation?? So I can follow the markup you use.

Thanks!

**Comment by ErikBorra** [comment]
Hi Arnout,

no header. Just in the following format (as stated in the script itself):
```
https://www.twitter.com/arnoutponsioen/status/781568421309870081,16-1-2016
https://twitter.com/arnoutponsioen/status/781555001156132864,16-3-2016
```

**Comment by arnoutponsioen** [comment]
WOW! seems to work. Keep you posted!

**Comment by arnoutponsioen** [comment]
Mmm... seems to only retrieve the ID of one URL (instead of 2)...

**Comment by ErikBorra** [comment]
Try using a header row.
