### ISSUE TITLE
admin screen kind of closed?

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#235]
Sorry for posting even more questions today... Importing tweets using lookup.php seems to work fine now. Thanks for the great help @ekborra!

But accessed TCAT via the browser, and selected admin. I found out that I can't see the query bins anymore nor add new query bins. The only message I get is:

"You currently have 5 query bins and are tracking 5 out of 400 possible phrases."

Any suggestion how to access the query bins?

Arnout

**Comment by ErikBorra** [comment]
You'd have to check your PHP error logs to see what's going on.

**Comment by arnoutponsioen** [comment]
Just checked but not sure what to look for...  two log-files: controller.log track.error.log...
Any clue/suggestion?

**Comment by arnoutponsioen** [comment]
A lot of information, statusupdates etc. in each...

**Comment by ErikBorra** [comment]
Copy and paste the output of `sudo tail -n 50 /var/log/apache2/error.log` here plz.

**Comment by arnoutponsioen** [comment]
Can it has anything to do with unsuccesfull autoupdate?
Here a screenshot form my terminal using your code:

![Uploading error log TCAT.PNG…]()

**Comment by ErikBorra** [comment]
Two things: 
* one of your bin names starts with a dash (-). This will lead to problems as table names should not contain dashes. I cannot help you with this remotely. Please find somebody knowledgeable of linux/apache/mysql to help you out and rename the mysql tables.
* it seems you are running MariaDB as your MySQL flavor. This is weird, as (the) TCAT (installer) requires MyISAM. Again, I cannot help you with this remotely. Please find somebody knowledgeable  of linux/apache/mysql to help you out reconfigure your MySQL database to MyISAM.

**Comment by arnoutponsioen** [comment]
Hi Erik. Thanks for looking into that!

I use Debian 8. During installation of Debian I think I checked the option to install MariaDB. I will reinstall using Ubuntu server 15.10 today to see if that makes a difference.

I did not know that using dashes could cause problems in the database.

**Comment by arnoutponsioen** [comment]
During installtation of Ubuntu server you get some options of software to install. Can you indicate what to install and what not te prevent conflicts with packages installed by the TCAT installer?

![image](https://cloud.githubusercontent.com/assets/17899995/19103815/85848e20-8ad9-11e6-99b7-425c74a31223.png)

**Comment by ErikBorra** [comment]
Hi Arnout,

OpenSSH is the only requisite. The TCAT installer will select and install the right versions of Apache and MySQL (and other required packages) for you.

Best,

Erik
