### ISSUE TITLE
imported tweets dated two hours earlier?

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#236]
Hi,

I am currently testing importing tweets using parse-csv.php and lookup.php based on tweet-urls.
That works fine (thanks @ErikBorra for helping me out).

But... when I look closely at the time stamps of imported tweets in TCAT, I find a two hour difference between the time stamp of imported tweets in TCAT, and the time stamps of tweets when you accessed manually in the browser. Eg. https://twitter.com/GoensEls/status/782513615370846210 is dated Oct 2, 11:32 (as can ben seen using a browser), but imported in TCAT it is dated on Oct, 9.32 (two hours earlier).

This time difference also accurs when tracking tweets with TCAT.

Any idea why this time difference is accuring and what to do about it?

**Comment by arnoutponsioen** [comment]
I think it has to do with timezone settings in config.php. Timezone is set to 'UTC', but in Holland it actually is UTC+2h. Can I change that? Config.php also says: do not change!

**Comment by ErikBorra** [comment]
Hi @arnoutponsioen,

this is something we are still working on in issue #197. @dentoir, could you provide a status update?

Best,

Erik

**Comment by dentoir** [comment]
Hi @arnoutponsioen 

The timestamps you see from tweets which you imported or tracked are currently _always_ in UTC. You will solely see UTC timestamps in the front-end panel and also in the export files. This explains the time difference of two hours, which is correct. There is no support yet unfortunately for using a different timezone on the visualization or the export side. This used to exist, but caused a bug. (Issue #197 fixed previous problems surrounding this.). Until we implement this again, you will need to be aware of this, and/or use some date transformation in Excel and other chained tools.
