### ISSUE TITLE
Remove bins from command line

### ISSUE THREAD

**Issue by johannessweater** [digitalmethodsinitiative/dmi-tcat#237]
Hi! I realized today I hit the storage limit on my Amazon instance and now I get an error when I try to access the TCAT interface. I know I have some pretty sizeable bins that can be deleted. (Though unfortunately, there is one still running that I would like to stop and download. Otherwise, I would just kill the instance.) Is there a way of deleting bins manually through the command line to free up space?

(I already scoured these issues for help: https://github.com/digitalmethodsinitiative/dmi-tcat/issues/191 and https://github.com/digitalmethodsinitiative/dmi-tcat/issues/189)

Thank you!

**Comment by dentoir** [comment]
Hi @johannessweater 

I think the command-line version of the API allows you to purge bins, but not completely delete them. Isn't it possible to stop your track script (disable cron etc.), then free up a bit of space (clear caches etc.). The capture panel interface does not by itself need disk space to function so I think your OS is behaving unexpectedly. This is really the only robust approach to solve your problem.
