### ISSUE TITLE
Don't use distinct on primary keys

### ISSUE THREAD

**Issue by frederickjansen** [digitalmethodsinitiative/dmi-tcat#238]
I thought MySQL would be smart enough to optimize this, but dropping the distinct selection on a primary key still gives me significant speed ups. This should not affect the query results.

For example:
```
SELECT SQL_NO_CACHE count(distinct(t.id)) as count FROM tcat_bin_tweets t  WHERE  t.created_at >= '2016-10-08 00:00:00' AND t.created_at <= '2016-10-10 00:00:00'
Query took 24 seconds.

SELECT SQL_NO_CACHE count(t.id) as count FROM tcat_bin_tweets t  WHERE  t.created_at >= '2016-10-08 00:00:00' AND t.created_at <= '2016-10-10 00:00:00'
Query took 15 seconds.
```

**Comment by dentoir** [comment]
Hi @frederickjansen 

Interesting! I'll try to test this today.

**Comment by frederickjansen** [comment]
For the record, this only works when list of results is already unique. I missed the join on "// count tweets containing links", so I reverted that change. I think the other ones are fine, but please double check.

Thanks!

**Comment by dentoir** [comment]
Hi @frederickjansen 

I tested it, dropped an additonal distinct on select elsewhere, and it all seems to work. Thanks for the contribution.
