### ISSUE TITLE
difference between network exports TCAT

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#241]
Hi all,

TCAT offers several exports of networks. Could you explain the difference between by export of social graph 'by mentions' and 'in-reply-to status'?\

Do I understand correctly:
- 'by mention' only looks at the text of the tweet (if it includes another account or not)
- 'by in-reply-to status' only looks only at meta-information of the tweets, not at the text of the tweet? 

Use-cases:
1. Using the twitter-website: opening a tweet, click 'reply to' -> Twitter offers a textbox already containing the account that posted the tweet and accounts bening mentioned in the tweet -> add some text and post as a new tweet
1. Using the twitter-website: writing a new tweet and include another account

Can you explain how these tweets will be included in both types network exports?

Thanks!

Arnout

**Comment by ErikBorra** [comment]
Hi Arnout,
 
'by mention' indeed only looks at the text of a tweet and parses out all '@mentions'. If 'person_who_tweets' writes a tweet and includes '@person_mentioned' those two persons will be linked in the network.

'by in-reply-to status' indeed looks at the meta-information of the tweets. In the network two persons will be connected if the tweet button 'reply' was used.

Best,

Erik

**Comment by arnoutponsioen** [comment]
Thanks eric!
And how does it treat 'quotes' and retweets?
Arnout
