### ISSUE TITLE
importing tweets from a csv table

### ISSUE THREAD

**Issue by oxygala** [digitalmethodsinitiative/dmi-tcat#245]
Hi,

I have a csv file full of old tweets that I collected years ago using some other methods (like saving as html and parsing). I need to include them to my current research, however some of the users locked and deleted their accounts I cannot import their tweets via parse-csv.php. 

Is there a way to import these to my database on DMI-TCAT, other than manually editing the database?

Thanks.

**Comment by ErikBorra** [comment]
Hi @oxygala,

there is no generic way to import custom tweet collections. You can write your own parser or edit the database manually.

Best,

Erik
