### ISSUE TITLE
Adding additional keys

### ISSUE THREAD

**Issue by imtechnology** [digitalmethodsinitiative/dmi-tcat#246]
Hi,

I was wondering if someone would be willing to provide a few further instructions about how to add additional keys in the config. I occasionally hit the rate limit and would like to add some additional ones, but I'm not too sure how to add them to the config file. 

Any advice very much appreciated.

Thanks,
Ed.

**Comment by dentoir** [comment]
Are you hitting rate limits in the tracking query, or any of the command-line scripts (such as lookup by id, et cetera.)?

Multi-key setup is only supported for the command-line scripts. Keys will be rotated. You can simply add them to the array variable $twitter_keys in config.key. To avoid rate limit occurances while tracking keywords, you may wish to split your queries into multiple bins and run those bins on separate servers.
