### ISSUE TITLE
Line breaks stopping the data collection?

### ISSUE THREAD

**Issue by theoaraujo** [digitalmethodsinitiative/dmi-tcat#250]
Hi guys, adding a line break in a query seems to stop the data collection. The line break seems to get passed to the URL for accessing the API, and that stops the whole process. I know it's not how a query should be created, but it might be an idea to have a way to handle this error?

**Comment by ErikBorra** [comment]
Thanks!

We should make a validator for both bin names and queries. Will be fixed soon.

**Comment by dentoir** [comment]
Hi @theoaraujo 

Before the Summer I worked a bit on the validation code, but I am not sure whether we addressed this. Question: how did you manage to insert line breaks into the bin names or queries? I can't manage it. Were you using the CLI scripts? Are you on the PHP 7 branch?

Best,

Emile

**Comment by theoaraujo** [comment]
Hi @dentoir 

Thanks for working on this! Adding line breaks was possible on when selecting modify phrases (after a bin was created). I only have DMI-TCAT now installed for items in production so I can't take the risk of testing it again. If this is not happening anymore when you modify phrases, then the issue can be closed, I think!

Cheers,
Theo

**Comment by dentoir** [comment]
Thanks, this should be fixed now in both master and php7
