### ISSUE TITLE
Deleting bins creates an issue with query manager

### ISSUE THREAD

**Issue by theoaraujo** [digitalmethodsinitiative/dmi-tcat#251]
Hi all,

It seems that deleting a query bin creates an issue with the query manager (the /capture/index.php URL goes offline), and looking at the logs I see that there are issues with DMI trying to update SQL tables that do not exist anymore (and getting PHP/Apache errors).

I've managed to restore access to the query manager by recreating (empty) tables in the SQL database with the name of the old query bins (that had been deleted).

Thanks,
Theo

**Comment by ErikBorra** [comment]
Thanks for submitting this issue. 

Sounds like the reference to the table in tcat_query_bins has not been deleted at the right time. Also, there might still be references to the querybin_id in tcat_query_bins_{phrases,users}.

We'll look into it on Friday.

**Comment by theoaraujo** [comment]
Thanks Erik! By the way, I am using DMI-TCAT in a UvA course with two groups of students in Communication Science and it's being quite useful for teaching purposes!

**Comment by ErikBorra** [comment]
Awesome! Let's meet up :) What about lunch tomorrow? 

You know about our video tutorial, right? After watching https://www.youtube.com/watch?v=ex97eoorUeo most students get a good hang of it.

**Comment by theoaraujo** [comment]
Hi Erik, another learning that I had this week - deleting a query bin that has line breaks makes it almost impossible to recover the data collection (I could not troubleshoot fully, but one of the tables of the query that got deleted did not completely get deleted, and corrupted the database).

**Comment by dentoir** [comment]
Related to #250
