### ISSUE TITLE
Rate limits export estimation

### ISSUE THREAD

**Issue by jaruizso** [digitalmethodsinitiative/dmi-tcat#252]
Hi guys

I have a question regarding the export of rate limits. In one of my datasets I have:

2016-08-28, 0.03
2016-08-29, 0.27
2016-08-30, 0
2016-08-31, 0
2016-09-01, 0
2016-09-02, 0
2016-09-03, 3.22

What means the decimals? That 0.03, or 0.27, of a tweet was not collected...?

In addition, I see that there are a lot of "potential gaps" in the data spreadsheet:

"2016-11-14 16:25:38","2016-11-14 16:36:01"
"2016-11-14 16:36:29","2016-11-14 16:47:01"
"2016-11-26 04:29:44","2016-11-26 04:40:01"
"2016-11-26 06:07:44","2016-11-26 06:18:01"

What is the reason for it, and what it implies? I am using amazon server EC2, and in theory everything should work just fine. Actually everything seems fine so far.

**Comment by dentoir** [comment]
Hi @jaruizso,

Try to match the gaps to the files in your logs/ directory, such as controller.error.log and track.error.klog.
From your dump it looks like the there has been an interruption for about 10 minutes, which _could_ indicate there simply weren't any tweets matching your queries during that time window. The controller distrusts this. This 'distrust' time window is configurable in config.php.

The ratelimit table is a best-effort estimate of the total number of tweets for the selected bin, which are considered to have been missing for the time interval (can be a small figure or zero, though it can also be a huge number if your server is heavily ratelimited).

From the source code, the mathematical formula applied is: total nr. of rate limited tweets during interval * (measured key word/phrase matches for the bin / total measured word/phrase matches).

**Comment by jaruizso** [comment]
Thanks for your answer. 

In my case, and regarding the issue of interruptions, there were not tweets matching the query, so all its in place.

You can close the issue :)
