### ISSUE TITLE
Go away you Evil hacker

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#255]
When accessing /capture I got this message: 'Go away you evil hacker!'
Accessing /analysis works wwithout problems.
Any suggestion what to do pass this message?

**Comment by ErikBorra** [comment]
Remove your cookies and then (re-)login as admin.

**Comment by augeas** [comment]
Might I suggest replacing this with a more polite and informative error message. It's not particularly helpful if one is debugging Apache authentication, and not really appropriate for user-facing code. A capture only user should not be referred to as an "evil hacker" with no other information given.

**Comment by dentoir** [comment]
Message rewritten
