### ISSUE TITLE
Twitter stops using "@" for mentions to other users.

### ISSUE THREAD

**Issue by jaruizso** [digitalmethodsinitiative/dmi-tcat#259]
Hi all,

After months of testing, it seems Twitter is finally implementing a new design for replies. Usernames will not count anymore as characters of the tweet, and therefore users have more space. However, it seems that with this change the @ symbol disappears, making harder to track conversations and mentions. Find more info in the following [link](http://www.theverge.com/2017/3/30/15115290/twitter-replies-redesign-character-limit). Personally I dislike the change.

I don't know if you had a discussion about that, and the implications it might have/cause to TCAT, or research based on Twitter in general. Will the API still include mentions as of today? Is TCAT ready to handle the changes?

**Comment by dentoir** [comment]
I think on the level of the API nothing will change. The following tweet for example https://twitter.com/john33lfc/status/847717760381485056 contains a mention of two users, without them being in the text. But on our server, tracking key word 'brexit', did capture the two mentions.

It is worth noticing the API currently gets to see the full tweet text in the fashion you would expect from the 'old days', with the usernames prepending the tweets text. This is how the tweet text will be stored in TCAT.

There an open issue relating to the maximum database storage character limit in TCAT, which nearly only affects Japanese, Korean and Chinese tweets: https://github.com/digitalmethodsinitiative/dmi-tcat/issues/228
