### ISSUE TITLE
Lacking mentions in "to_user_name" column

### ISSUE THREAD

**Issue by jaruizso** [digitalmethodsinitiative/dmi-tcat#262]
Following my last issue about "in_reply_to_status_id" #257 , I just noticed another little problem. I am trying to create a mentions network with the following structure. I make use of the following columns:

from_user_name --- to_user_name

The problem I observed is that even if a user in _from_user_name_ column mentions more than one user in the tweet (text column), in the _to_user_name_ column only appears the first one. For example:

**text:** @user2 @user3 @user4  Schengen sofort aussetzen.Grenzkontrollen einführen Abschiebe-Züge bereitstellen Gesindel zurückjagen

from_user_name --- to_user_name
User1                                User2

This happens independently if its a mention _(to_user_name_) or a reply _(in_reply_to_status_id_). It might happen that a user replies to more than one user.

Second, according to #241, TCAT export for mentions network parse all the @mentions in the text. But then if _in_reply_to_status_ network option looks at the metadata, it will only create single pairs, since only one user id is at the _in_reply_to_status_id_ column.

**Comment by dentoir** [comment]
Hi @jaruizso 

The mentions are stored in an external table bin_name_mentions. It can contain multiple user names per tweet. The export graph module uses a JOIN on this table to produce the data. The to_user_name column is actually the user name of the user which the tweet _replies_ to (which is always a single user). It maps to the Twitter API result field `in_reply_to_user_id_str`

Hope this helps.

Cheers,

Emile
