### ISSUE TITLE
Add additional admin users

### ISSUE THREAD

**Issue by MarkEEaton** [digitalmethodsinitiative/dmi-tcat#263]
I am trying to add additional admin users. I used the automated installation, then changed config.php to include additional admins, like this:

`define('ADMIN_USER', serialize(array('admin', 'secondadmin', 'thirdadmin')));`

then assigned passwords:

`$ sudo htpasswd /etc/apache2/tcat.htpasswd secondadmin`
`$ sudo htpasswd /etc/apache2/tcat.htpasswd thirdadmin`

But I seem to be missing something still. What else do I need to do to make this work?

Thanks for any suggestions.

**Comment by dentoir** [comment]
I think you're almost there. You'll need to edit the apache2 configuration file for the TCAT site and edit the 'Require user' line. 

`Require user admin secondadmin thirdadmin`

etc.

The file is usually called /etc/apache2/sites-available/tcat.conf

**Comment by MarkEEaton** [comment]
Perfect. Thank you. That was what was needed!
