### ISSUE TITLE
Installation problem in Ubuntu 15.10

### ISSUE THREAD

**Issue by Acelerado** [digitalmethodsinitiative/dmi-tcat#264]
Hi! I'm hoping to use DMI-TCAT for a research project with my students this semester but we have been stuck dealing with an installation problem. We would really appreciate if someone can help us. 
This is the error we get during installation (it's a translation from Spanish so it might vary):

W: Failed to fetch http://ppa.launchpad.net/lucid-bleed/ppa/ubuntu/dists/wily/main/binary-i386/Packages 404  Not Found

E: Some index files failed to download, they have been ignored, or old ones used instead.

tcat-install-linux.sh: command failed: install aborted

**Comment by dentoir** [comment]
Hi @Acelerado 

This is a warning/error from the Ubuntu package application. Are you able to install any other new packages on the machine (using apt-get install, i.e.: apt-get install vim).
It may be your machine references some none-existing repositories and the install script aborts.

Cheers,

Emile

**Comment by Acelerado** [comment]
Hi Emile, and many thanks for answering. I can install other packages indeed. Would you suggest another way we may try?
best,
Carlos

**Comment by dentoir** [comment]
Hi @Acelerado ,

Could you change the first line of the installer script into the following?

`#!/bin/bash -x`

This should help debugging the installation. Every command will be echod back to the terminal. Please send us the full log (excluding any passwords obviously) and we may be able to figure out what is going wrong.

**Comment by Acelerado** [comment]
Many thanks for your help @dentoir !! It worked out with Debian.

cheers,
C
