### ISSUE TITLE
Lookup.php stopped working

### ISSUE THREAD

**Issue by johannessweater** [digitalmethodsinitiative/dmi-tcat#265]
Hi -- I've been using lookup.php successfully. But this morning I started getting this message:

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '??7' at line 1' in /var/www/dmi-tcat/capture/ids/lookup.php:60
Stack trace:
#0 /var/www/dmi-tcat/capture/ids/lookup.php(60): PDOStatement->execute()
#1 {main}
  thrown in /var/www/dmi-tcat/capture/ids/lookup.php on line 60

I've tried reinstalling TCAT on a new server, but get the same result. Is anyone else running into this problem?

**Comment by dentoir** [comment]
Looks like something input related. Verify your input file contains only numbers. To debug the issue, add the following line of code *above* line 60:
`echo "$query\n";`
You should see all SQL queries, and the final one should be the failing query.

**Comment by dentoir** [comment]
This does not appear to be a bug.
