### ISSUE TITLE
Dmi-tcat not retrieving tweets with specific stardate

### ISSUE THREAD

**Issue by PaulaMoya** [digitalmethodsinitiative/dmi-tcat#267]
Hi. When i create the dataset i have more than 10.300 tweets, but when i try to limit the search by start and end date it retrieves 0. What can i do? Is it an installation problem? Thank youuu

**Comment by dentoir** [comment]
Hi @PaulaMoya,

Are you sure you used the format: YYYY-MM-DD HH:MM:SS (year:month:day hour:minute:seconds) with full digits? TCAT requires this exact format. Could you provide a screen shot of your query?

Best,

Emile
