### ISSUE TITLE
Most tweets not being fetched by lookup.php

### ISSUE THREAD

**Issue by thevarunfactor** [digitalmethodsinitiative/dmi-tcat#270]
The lookup.php script doesn't fetch most of the tweets. Error logs are empty. I know these tweets exist (user hasn't removed them, protected them etc) because I can see these tweets in Twitter's advanced search results. These are the results TCAT is giving me: 

Total number of tweets in your ID file:                                       37265
Number of new tweets inserted into the bin:                                     199
Number of tweets skipped because they already existed in bin:                     0
Number of tweets skipped because they are no longer accessible:               37066

I'm running TCAT on Raspbian Jessie OS, on a Raspberry Pi. 
How can I remedy this? Thanks for your time and help.

**Comment by dentoir** [comment]
Hi @thevarunfactor 

That is strange. Sounds like the ids are not read properly, even though they may be counted correctly. I'm just guessing, but are the line-endings of the file all in the same format (\n). Is there something around line 199/200 which is different from the earlier lines? Are there any hidden spaces?

If this turns up nothing, we'd need to debug the output of the Twitter API response. In line 156 of the lookup.php script, you could add the following line
`print_r($data);`

The script will now output a _lot_ of text. Pressing cntrl-c is probably a good idear and send us a final fragment, say 200 lines (remove any authentication tokens which may be inside it).

**Comment by thevarunfactor** [comment]
Thanks for looking at the issue. Yes, the IDs are formatted as per the specification and there are no extra spaces.  Here's a chunk of the Twitter API response -- 

[twitterOutput.txt](https://github.com/digitalmethodsinitiative/dmi-tcat/files/1138763/twitterOutput.txt)
 
I also tried to randomly pick up about 3,000 ids and look them up, but I got this: 
Total number of tweets in your ID file:                                        3320
Number of new tweets inserted into the bin:                                      14
Number of tweets skipped because they already existed in bin:                     0
Number of tweets skipped because they are no longer accessible:                3306

**Comment by dentoir** [comment]
Hi @thevarunfactor 

I have no idear why that is happening. The figures are obviously not correct. I normally get a few % of lost tweets and they are truly inaccessible/deleted. From the log output I do see you get empty array() elements which means the Twitter API is giving empty responses, which the scripts registers as: those tweets are not accessible. Do you mind sharing the list (say the 3000) tweets with me, so I can run the lookup locally?

**Comment by thevarunfactor** [comment]
Sure @dentoir, that would be great. Thanks
[sampletweets.txt](https://github.com/digitalmethodsinitiative/dmi-tcat/files/1138842/sampletweets.txt)

**Comment by dentoir** [comment]
I found your problem. You've exported these tweets as numbers in your spreadsheet software and the software seems to have rounded them down to a certain level, which is wrong. The tweet ids are huge numbers, but are all unique. Your tweet ids are ending with three zeros. The problem will be fixed when you explicitly set the column type to string in either Excel, or Open Office and export the ids again. The tweets you've already looked up are not correct and should be discarded.

**Comment by thevarunfactor** [comment]
Perfect. It works now. Thank you so much for your help, @dentoir
