### ISSUE TITLE
Server full, database locked & corrupted tables

### ISSUE THREAD

**Issue by mhockenhull** [digitalmethodsinitiative/dmi-tcat#271]
Specs:
Ubuntu 14.04.5 LTS \n \l
PHP 5.5.9-1ubuntu4.21
TCAT commit c297b94061fbb3c1abfba150ce0b8368b0de7b46
TCAT branch * master

I seem to have gotten my TCAT instance into some trouble + combined with a couple of problems occurring at once. 

TCAT wasn't collecting data and the /capture page wasn't rendering, so I logged into the server and discovered that the server's memory was completely used up. I thought I could fix this by manually removing some of the datasets via SQL and did so. I then consulted the github to realize too late that this could lock SQL up, since I dropped tables without removing them from the TCAT index list. The github issues also led me to look at the apache logs, which suggested that corruption in some of the SQL tables might be the problem. 

I realise I made some bad decisions, but am curious if you have some suggestions for how I can solve this and get the server running again? Can/should I:
- Export some of the bins and do a clean install?
- Drop more tables to free up space, whilst making sure that the index over the query bins match the actual bins to avoid a lock?
- Something else?

Log excerpts: 
[apache.txt](https://github.com/digitalmethodsinitiative/dmi-tcat/files/1159291/apache.txt)

I have tried to get logs for TCAT, MySql, syslog but they are all empty for the recent period, I'm assuming do to the server being full. I will access the older logs and post them here ASAP.

**Comment by ErikBorra** [comment]
Hi @mhockenhull,

first free up some disk space, then repair the crashed tables, then remove the references to the dropped tables in tcat_query_bins and tcat_query_bin_phrases. Last but not least, increase your disk space.

Best,

Erik

**Comment by mhockenhull** [comment]
Hi Erik, 
Thank you for the response. I am working on it now, but haven't solved the problem yet. You can either close the issue now, or I'll close it when the problem is fully solved. 
Best, 
Michael

**Comment by mhockenhull** [comment]
Issue now resolved, server is working again. 
Thanks for the help!
