### ISSUE TITLE
Counting tweets but none available for analysis

### ISSUE THREAD

**Issue by michaelniemann** [digitalmethodsinitiative/dmi-tcat#273]
Hi,

I have installed TCAT on a NeCTAR instance using [http://launchpod.intersect.org.au](http://launchpod.intersect.org.au). I can successfully access the capture webpage and set up and activate querybins.  The tracking seems to be going quite nicely, sometimes even hitting rate limits, so I know it is working. My problem is when I visit the analysis page, I cannot do any analysis. It tells me that the same number of tweets have been captured as the capture page, but I can get no data on those tweets and conduct no successful queries on them either. I can't even look at the 'raw' data or a 'tweets vs time' graph.

Through launchpod, I set up a password for 'admin' and 'tcat', which are used to access the capture and analysis pages. When I ssh into the NeCTAR instance, launchpod tells me to do so with a 'ech2-user' account which uses the keypair set up for the instance. Once on the server, I cannot find any record of TCAT or any active MySql db. The 'admin' and 'tcat' usernames do not work for ssh and seemingly have no accounts on the instance server.

Does anyone have any idea of what I am missing? Where might the TCAT data be hiding? Can the capture continue without MySql working?

I am happy to provide extra info if you tell me what you need to help me. Launchpod is using TCAT 830652e, which is supposedly a stable version.

Thanks,

Michael

**Comment by ErikBorra** [comment]
Have you made sure that the date selection on the analysis page reflects the range of data you captured?

@brendam or @hoylen may be of help for Nectar specific issues.

**Comment by michaelniemann** [comment]
Thanks @ErikBorra . That seems to be the problem. I had extended it back in time, because I thought it was initially only collecting historical data based on the search API, but adding a couple of weeks forward now gives me data!

Much appreciated.
