### ISSUE TITLE
DMI-TCAT: Christa Brouwer 'wereld natuur fonds' 'donatie' 'doneren' 'goede doelen' 

### ISSUE THREAD

**Issue by chri-sta** [digitalmethodsinitiative/dmi-tcat#275]
I can't find the DMI-TCAT tag

**Comment by ErikBorra** [comment]
Dear Birgitta,

TCAT is server-side software that has to be installed on a linux machine. We do not provide any public data collection. I suspect that you better contact your teacher.

Best,

Erik
