### ISSUE TITLE
Problem with adding the media column to Tweet exports

### ISSUE THREAD

**Issue by Alotsi** [digitalmethodsinitiative/dmi-tcat#279]
Hi everyone,

On the installation I am using the tweet export function works fine by itself. However when I try to add either the media, mentions, or the hashtag columns to the export, it produces an empty file (with only column names and no data).

Does anyone know what can be done about this?  
Thanks!

**Comment by dentoir** [comment]
Hoi @Alotsi,

Please add some more information about your specific TCAT installation and especially give a fragment of the Apache error logs, as described here:

https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Bug-submission-guidelines#how-to-file-an-issue

Best,

Emile

**Comment by Alotsi** [comment]
Hi Emile @dentoir , 

The installation details are Ubuntu 16.04. PhP 7, with the most recent TCAT. 
The apache error log does not show anything .
However we get the following message in the capture view:

Your database must be updated before some new TCAT features can be used. Follow the documentation and run the command-line script common/upgrade.php from your shell.

Php upgrade does not fix this:
php upgrade.php 
2017-10-03 17:45:55	Running in interactive mode
2017-10-03 17:45:55	Executing global upgrade
2017-10-03 17:45:58	Restarting active capture role: follow

More importantly upgrade-media.php fails with the following response:

php upgrade-media.php 
10581 (possibly) deprecated media objects found in bin danske_forskere
2017-10-03 17:45:22	Warning: API key 0 got response code 400
 
Thanks!

**Comment by dentoir** [comment]
Hi @Alotsi 

Thanks for the update. It's strange no error messages show op in the error log. I assume you've checked after you ran the export with media.

However, it looks like your REST api key is not accepted by Twitter. This key should be configured in config.php. It should be easy, you could use the same key pair as your follow key. The values should be under the $twitter_keys array. Afterwards, you can try running upgrade-media.php again.

**Comment by dentoir** [comment]
Hi @Alotsi 

This was a bug in the php 7 branch, it should be fixed now with the latest commit. Thanks for reporting!

**Comment by Alotsi** [comment]
Great, it works, thank you so much! @dentoir
