### ISSUE TITLE
Not able to see datasets in analysis page in dropdown menu.

### ISSUE THREAD

**Issue by PravalikaRao** [digitalmethodsinitiative/dmi-tcat#282]
When I open the analysis page in the browser, I am not able to see the datasets in the drop-down menu. This is not allowing me to create the query bins and to extract tweets. Please suggest me a solution for this. 
Please find the attachment where you can see analysis page screenshot.
![screenshot from 2017-10-17 10-39-54](https://user-images.githubusercontent.com/26156720/31671832-e02c6a96-b328-11e7-8de1-3064ebde2c4e.png)

**Comment by ErikBorra** [comment]
Please go to http://54.81.5.52/capture and create a query bin before going to the analysis page.

**Comment by PravalikaRao** [comment]
Thank you, Erik. I problem got solved.
