### ISSUE TITLE
Improve analysis performance by using the existing FULLTEXT indexes

### ISSUE THREAD

**Issue by dentoir** [digitalmethodsinitiative/dmi-tcat#285]
We should consider how we can use MATCH() AGAINST() syntax in the analysis frontend, instead of LIKE syntax. Particularly the sqlSubset() function in analysis/common/functions.php should be studied.

**Comment by ErikBorra** [comment]
i.e., what are the benefits of using match against over like in terms of performance, query formulation, etcetera. Community input is welcomed.

**Comment by dentoir** [comment]
FULLTEXT using the syntax I suggested runs in to unexpected problems with stoplists or short words (no string 'D66' found etc.) - and FULLTEXT is not supported by all modern storage engines, therefore I don't think this is the way to go for now.
