### ISSUE TITLE
Urlexpand error during installation

### ISSUE THREAD

**Issue by laspic** [digitalmethodsinitiative/dmi-tcat#286]
Hello,

I use Python 2.7.9, [GCC 4.9.2] on linux2.

I get this error during the urlexpand's process of installation:

```
root@xxx:~# cd /var/www/dmi-tcat/helpers/; python urlexpand.py
Traceback (most recent call last):
  File "urlexpand.py", line 29, in <module>
    with open(os.path.dirname(__file__) + '/../config.php', 'r') as f:
IOError: [Errno 2] No such file or directory: '/../config.php'
```
I don't know to resolve it. I don't ever know what does it mean. I precise that :
* all the Python packages and modules are well installed;
* the file _config.php_ isn't missing;
* dmi-tcat works well to track tweets;
* and, last but not least, the script _urlexpand-debug.py_ **works like a charm** for its part !

What happens ? What can I do ?

**Comment by dentoir** [comment]
Hi @laspic 

Can you do a git pull, and at line 28, add the following line:

`print os.path.dirname(__file__) + '/../config.php'`

Does the output of the script point to the correct location of config.php or do you get some other error?

**Comment by laspic** [comment]
Thank you for your response. 

Git tells : 
`Already up-to-date.`

And when I run _urlexpand.py_ with your new line : 
```
root@xxx:/var/www/dmi-tcat/helpers# python urlexpand.py
/../config.php
Traceback (most recent call last):
  File "urlexpand.py", line 31, in <module>
    with open(os.path.dirname(__file__) + '/../config.php', 'r') as f:
IOError: [Errno 2] No such file or directory: '/../config.php'
```

**Comment by dentoir** [comment]
It  appears os.path.dirname(__file__) is undefined. I didn't know that was possible. Is strange that this is happening on Linux. I'll look for a more universal way of getting the directory of the script which is being executed.
