### ISSUE TITLE
Keep getting error on line 3

### ISSUE THREAD

**Issue by anoukpops** [digitalmethodsinitiative/dmi-tcat#287]
Hello! Whatever I try to do, I keep getting this error:
Undefined variable: argc in C;....... on line 3 (line 3 n both cases is if ($argc < 1)

I tried to the the user timelines - this happened when i try to run the php. Then I tried to import json, and when running the pho, the same error occurred.
Any ideas what might be the problem?
Thanks,
Ana

**Comment by dentoir** [comment]
Hi @anoukpops 

How are you starting the script? You should run the script from the command-line like this:

`php timeline.php`

Best,

Emile

**Comment by dentoir** [comment]
Timeout reached.
