### ISSUE TITLE
Mentions in Hashtag-user activity

### ISSUE THREAD

**Issue by Ecozzo** [digitalmethodsinitiative/dmi-tcat#288]
I get 0 for number of mentions tweeted together with the hashtag for some hashtags when exporting tweets I can see there are mentions

**Comment by dentoir** [comment]
HI @Ecozzo 

Can you provide more information about your TCAT installation, OS version, logs, etc. as described here: https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Bug-submission-guidelines
