### ISSUE TITLE
Get specific user tweets

### ISSUE THREAD

**Issue by ravenous87** [digitalmethodsinitiative/dmi-tcat#289]
Hi, maybe it's a dumb question but can I retrieve the tweets from a specific user? When making a new query bin I know I can write the user's Twitter name on "phrases to track" but that gets _everything_: when he is mentioned, etc and not just **what he writes**, which is what I'm looking for.

On the other hand, on the analysis tool I've tried to use the "from user" parameter but apparently that doesn't work since it doesn't retrieve any tweets.

Thank you for your help.

**Comment by ErikBorra** [comment]
Yes you can, see [user timelines](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/FAQ#user-timelines) in the FAQ.

**Comment by ravenous87** [comment]
Thank you for the quick answer. I'm no programmer so I barely understand the steps described in that link. I'm guessing there's no other easier way?

**Comment by ErikBorra** [comment]
No other way atm. Sorry.

**Comment by xmacex** [comment]
Close this one?
