### ISSUE TITLE
geo located Twitter trends on a regular basis

### ISSUE THREAD

**Issue by francescaruisi** [digitalmethodsinitiative/dmi-tcat#291]
Hello all!

I am totally new to TCAT and before installing I wish to kindly ask you if it is able to geo located Twitter trends for a due country on a regular base (plausibly every 7 days). 

I really appreciate every feedback about

**Comment by ErikBorra** [comment]
Hi @francescaruisi 

That's not something TCAT is currently able to do

Best,

Erik

**Comment by francescaruisi** [comment]
Dear Erik,

thank you for your kind and prompt reply. 

Maybe my question has not been so clear. I will try to better explain. 

Following the literature I noted this study using TCAT https://wiki.digitalmethods.net/Dmi/WinterSchool2016TwitterAsACitysAttentionBarometer

I wish to reproduce a similar study by observing other regions and this is the reason why I asked if TCAT is able to collect geo-located tweets in defined areas within a due time. 
If twitter trends collection in a due country is not an available option on TCAT I guess it is possible to collect geo-located tweets by specifying a certain geograpghical area. 
Please, could you confirm it?

Really thank you again for your feedback

Francesca

**Comment by ErikBorra** [comment]
Hi @francescaruisi 

it is indeed possible to specify a geographic bounding box and to track all the geotagged tweets within that area. Note that geotagged tweets only constitute less than 1% of tweets. See the [FAQ](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/FAQ#location-track) for more information on how to set up tracking geotagged tweets.

Best,

Erik

**Comment by francescaruisi** [comment]
Thank you really much Erik! :) I will try then to test it in this sense.
thank you

Francesca
