### ISSUE TITLE
Blank query manager page

### ISSUE THREAD

**Issue by Landmaj** [digitalmethodsinitiative/dmi-tcat#294]
I wanted to change a query yesterday and was greeted by this:

![screenshot-2018-1-4 dmi-tcat query manager](https://user-images.githubusercontent.com/13437951/34564269-46777032-f156-11e7-9303-34bcbaf4ca33.png)

The page is mostly blank except for some text and links at the top. Analysis page works without problems.

I haven't made any changes recently and I was told by our server admin that no major updates or configuration changes were made.

This shows up in log:
`[Wed Jan 03 18:22:14.102063 2018] [:error] [pid 14488:tid 139922467952384] [client #removed#] FastCGI: server "/var/php-fpm/#removed#/php" stderr: PHP message: PHP Warning:  shell_exec() has been disabled for security reasons in /home/str_tcat/www/dmi-tcat/capture/common/functions.php on line 698`
`[Wed Jan 03 18:22:14.102080 2018] [:error] [pid 14488:tid 139922467952384] [client #removed#] FastCGI: server "/var/php-fpm/#removed#/php" stderr: PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1' in /home/str_tcat/www/dmi-tcat/common/upgrade.php:130`
`[Wed Jan 03 18:22:14.102084 2018] [:error] [pid 14488:tid 139922467952384] [client #removed#] FastCGI: server "/var/php-fpm/#removed#/php" stderr: Stack trace:`
`[Wed Jan 03 18:22:14.102086 2018] [:error] [pid 14488:tid 139922467952384] [client #removed#] FastCGI: server "/var/php-fpm/#removed#/php" stderr: #0 /home/str_tcat/www/dmi-tcat/common/upgrade.php(130): PDOStatement->execute()` 
`[Wed Jan 03 18:22:14.102088 2018] [:error] [pid 14488:tid 139922467952384] [client #removed#] FastCGI: server "/var/php-fpm/#removed#/php" stderr: #1 /home/str_tcat/www/dmi-tcat/capture/index.php(164): upgrades(true)` 
`[Wed Jan 03 18:22:14.102090 2018] [:error] [pid 14488:tid 139922467952384] [client #removed#] FastCGI: server "/var/php-fpm/#removed#/php" stderr: #2 {main}`
`[Wed Jan 03 18:22:14.102092 2018] [:error] [pid 14488:tid 139922467952384] [client #removed#] FastCGI: server "/var/php-fpm/#removed#/php" stderr:   thrown in /home/str_tcat/www/dmi-tcat/common/upgrade.php on line 130`

Running upgrade.php from command line results in the same error:

![bez tytulu](https://user-images.githubusercontent.com/13437951/34564924-165d795c-f159-11e7-9595-82b32726821b.png)

I exported our queries and did a clean install but the problem persists. What could cause this problem? Since I haven't done anything with TCAT for two months and it suddenly stopped working, I guess it has to be something with our server (Ubuntu 14.04).

**Comment by dentoir** [comment]
Hi,

From a quick glance it looks like the upgrade script is choking on a table with an odd name. Can you do a `SHOW TABLES` query on your database and see if something odd show up there. It should be a table ending in _tweets though. I don't have time to study your message more closely now.

**Comment by Landmaj** [comment]
Thank you, indeed that was a problem! After reinstalling TCAT I used the same database and only wiped it with a script found on the internet. Those tables were left and they were the cause:

+--------------------------+
| Tables_in_str_tcat       |
+--------------------------+
| #meetyourfarmer_media    |
| #meetyourfarmer_mentions |
| #meetyourfarmer_places   |
| #meetyourfarmer_tweets   |
| #meetyourfarmer_urls     |
| #meetyourfarmer_withheld |
+--------------------------+

After removing them by hand everything is back to normal.
