### ISSUE TITLE
Analysis gets ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by dormeir99o** [digitalmethodsinitiative/dmi-tcat#296]
Hello,

I've installed a fresh TCAT on Amazon t2.micro instance, 1 vCPU and 1G RAM, Ubuntu 16.04.
Capture is doing great, and I'm able to get to Analysis and see the datasets box and the graph, but when I query anything on Analysis (from today only) the page is loading for about 30 seconds and then goes to ERR_CONNECTION_TIMED_OUT.
I realize It's a small server and that it's so small that some configurations, like ini_set("memory_limit", "4G"); in the config.php file, makes no sense in a server with 1G RAM, but I have two questions:
a. Is the problem in the memory of the server? I do see it always has at least 100MB free.
b. If it's a memory problem - what's the minimal size of memory I need to use in order to make Analysis work? Or can I keep using the the 1G RAM but change some configurations so that Analysis will work? I tried changing memory_limit to 1G but it didn't help.

I haven't seen any errors on syslog, apache, mysql, controller.log...

**Comment by dentoir** [comment]
Hi @dormeir99o 

Did you use the auto-installer to install TCAT and did you modify anything to your MySQL server configuration? The auto-installer doesn't touch my.cnf I believe if you have 1 G RAM or less. However, I don't think this is MySQL/memory related.

The most obvious improvement would be to increase the connection timeout windo for Apache/PHP. Thirty seconds is too short even for a big server. TCAT needs to load tables into its caches during the first queries. If you install using the auto-installer (which installs mod_php) I don't think the default timeout should be that low?

**Comment by dormeir99o** [comment]
Hi @dentoir,

Yes, I used the auto-installer, and didn't modify the MySQL server configuration. should I?

I've changed **max_execution_time** to 12000 in both /etc/php/7.0/cli/php.ini and /etc/php/7.0/apache2/php.ini , and changed **Timeout** to 12000 in /etc/apache2/apache2.conf, still the same results... What I am doing wrong?

**Comment by ErikBorra** [comment]
I am afraid 1GB is just way too little for even medium-sized data sets (100k tweets or more).

**Comment by dormeir99o** [comment]
Right now we have about a 1000 tweets...

**Comment by holnburger** [comment]
I have 2GB of RAM and currently 15 million tweets, biggest set is about 1m. Takes it's time but it works.
And shouldn't be a problem with 1000 tweets…
Sorry, I don't have a solution, just wanted to drop that 1GB should be fine for that size of data set.

**Comment by ErikBorra** [comment]
Good to know @holnburger 
Hopefully @dentoir can help you @dormeir99o

**Comment by dormeir99o** [comment]
Hi all,

I've changed the instance type to t2.small - 2GB RAM, but I still get the same result when querying on capture - loading for about 30 seconds and then "took too long to respond"...

**Comment by dentoir** [comment]
Hi @dormeir99o 

As even tiny queries seem to fail on your server, I guess this must be somehow related to Apache. However, I've recently tested Ubuntu 16.04 with auto-installeer and it did run well. Can you inspect the following file

`/var/log/apache2/error.log`

And also:

`/var/log/apache2/access.log`

Do you see anything in the first file *after* you've started your analysis query? And, do you see anything in the second file *after* you've started your analysis query?

**Comment by dormeir99o** [comment]
Thanks @dentoir,
eventually I terminated the micro instance, created a t2.small and installed TCAT again (the same way), now it works..
