### ISSUE TITLE
on AWS EC2: cannot export tweets or use most analysis features

### ISSUE THREAD

**Issue by zhanglipku** [digitalmethodsinitiative/dmi-tcat#300]
Hello, I have successfully installed TCAT on my EC2 (t2.small) virtual machine on AWS, I have changed security groups to allow both SSH and HTTP visit. However I do need help with the following issues:

currently I CAN: 
1. Visit TCAT from a web browser, using the ec2-**-**-**-***.us-east-2.compute.amazonaws.com URL. 
2. Add query bin and see the number of fetched tweets growing. 
3. See the "Overview of your selection"

currently I CAN'T:

1. Launch any feature in the "Tweet statistics and activity metrics" section. Ever time I tried, it gives me an error message "the can't be connected", and an IP address (let's call it p) "took too long to respond". Later I learnt that p is the private IP address assigned by AWS in addition to the primary IP.
2. Export any of the tweets fetched (the data set I am working with is rather small, about 2k). Same error message as above.
3. Perhaps related, at the end of my installation, TCAT wants me to log on TCAT using the aforementioned IP address, but I cannot. The only way I have access to TCAT is via the DNS assigned by AWS (ec2-**-**-**-***.us-east-2.compute.amazonaws.com). Is it because, during the installation process, when TCAT asks me to specify the IP address, I just hit enter, so the private IP address rather than the public one is taken as my URL?

Thank you very much.

**Comment by dentoir** [comment]
Hi @zhanglipku 

Looks like the `BASE_URL` configuration parameter may not be correctly set-up in your installation. It should be your public hostname, not your private IP address. Can you verify its value inside `config.php`?

Best,

Emile

**Comment by zhanglipku** [comment]
Hello Emile @dentoir 

I re-installed TCAT and specified my public DNS as the server. Now I can launch analysis as well as download the csv export file. 

But the new issue is: no matter how many tweets have been archived, the downloaded files are all blank (though all the column names are there). Please see attached screenshot.

![download 1](https://user-images.githubusercontent.com/17376900/35527597-46d1308e-04f9-11e8-82ae-486edc9920fa.png)

**Comment by dentoir** [comment]
Hi @zhanglipku 

Your date range selection is one day before the start of your tweet capture ;-)

**Comment by dentoir** [comment]
I think the original issue is solved.
