### ISSUE TITLE
Install on Nectar Ubuntu 16.04 LTS fails at git step - git not installed

### ISSUE THREAD

**Issue by brendam** [digitalmethodsinitiative/dmi-tcat#301]
Not sure if this is specific to the Nectar image of Ubuntu 16.04 LTS or not, but I just did an install using the installation script and it failed because git was not installed. Need to add git to the packages the script installs before it tries to use it?

**Comment by brendam** [comment]
Looks like it might have been the call to git on line 979. Might need to move line 1079 further up the script?

**Comment by dentoir** [comment]
Installing git itself could be moved up to line 898 I suppose, as it is required.

**Comment by dentoir** [comment]
Fixed

**Comment by brendam** [comment]
thanks!
