### ISSUE TITLE
gevent problem - fresh install

### ISSUE THREAD

**Issue by oxygala** [digitalmethodsinitiative/dmi-tcat#304]
using the automated install script on Ubuntu or Debian (both fresh installs, 16.04 and 8.0 respectively), I have the following error during the installation of gevent that causes the script to abort.

`TypeError: cythonize() got an unexpected keyword argument 'include_path'`

up to now I could not overcome this problem. 

thanks.

**Comment by dentoir** [comment]
Hi @oxygala 

Strange, this is new to me. Can you dump me a bit more of your installation log? Sounds like this may be an issue with the upstream python repository, but nevertheless problematic if this breaks the auto installer. If I have time I'll try a new auto-install myself on Amazon. I'm working on a replacement for this subpart of TCAT at the moment.

Best,

Emile

**Comment by dentoir** [comment]
Fixed, was related to this https://github.com/gevent/gevent/issues/1083
