### ISSUE TITLE
Call to undefined function pdo_connect()

### ISSUE THREAD

**Issue by RealMithrandir** [digitalmethodsinitiative/dmi-tcat#308]
I've been getting the following errors on all Analysis page exports (which just show a 500 error after an export is clicked). The system was working fine yesterday, so this has started within the past 12 hours or so.

`[Wed Mar 28 13:28:02.562210 2018] [:error] [pid 21355] [client 12.90.248.238:10155] PHP Fatal error:  Uncaught Error: Call to undefined function pdo_connect() in /var/www/dmi-tcat/analysis/common/functions.php:7\nStack trace:\n#0 /var/www/dmi-tcat/analysis/ajax.serverload.php(3): require_once()\n#1 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 7, referer: http://34.207.141.11/analysis/index.php?dataset=Russian_nerve_agent_attack&query=&url_query=&geo_query=&exclude=&from_user_name=&from_user_lang=&exclude_from_user_name=&from_user_description=&from_source=&startdate=2018-03-26&enddate=2018-03-27&whattodo=&graph_resolution=day&outputformat=csv`

Any help would be appreciated!

Thanks!

**Comment by supersambo** [comment]
Hi, 
I'm experiencing the same issue...

**Comment by supersambo** [comment]
Hi, 
thanks, this solved the problem! 
(I did not try all downloads though, but some of them in each section)

**Comment by RealMithrandir** [comment]
I'll try the same thanks!

**Comment by RealMithrandir** [comment]
This solved the problem for me too.
