### ISSUE TITLE
Capture stopped after auto-update

### ISSUE THREAD

**Issue by RealMithrandir** [digitalmethodsinitiative/dmi-tcat#310]
Hello,

I noticed that my captures have stopped after an auto-update (attached error log screenshots). I have attempted the manual update and re-start commands a few times and the cron jobs do not appear to start (ps aux | grep php | egrep 'dmitcat|controller' returns nothing). I turned off auto-update in config.php to see if that made a difference but the results didn't change. I've included the returns fro the controller and error logs. Any help would be appreciated. Thanks!

controller log:
![screen shot 2018-04-02 at 11 12 33 am](https://user-images.githubusercontent.com/11824645/38201819-95ee0fda-3667-11e8-91d2-a6a29ffcd19f.png)

error log"
`2018-03-28 03:00:01	running php version 7.0.28-0ubuntu0.16.04.1 in mode cli with extensions Core,date,libxml,openssl,pcre,zlib,filter,hash,pcntl,Reflection,SPL,session,standard,mysqlnd,PDO,xml,calendar,ctype,curl,dom,mbstring,fileinfo,ftp,geos,gettext,iconv,json,exif,mysqli,pdo_mysql,Phar,posix,readline,shmop,SimpleXML,sockets,sysvmsg,sysvsem,sysvshm,tokenizer,wddx,xmlreader,xmlwriter,xsl,Zend OPcache (ini file: /etc/php/7.0/cli/php.ini)
2018-03-28 03:00:01	installing term signal handler for this script
2018-03-28 03:00:01	geoPHP library is fully functional
2018-03-28 03:00:01	started script track with pid 12096
2018-03-28 03:00:01	connecting to API socket
2018-03-28 03:00:01	connecting - query array (
  'locations' => '35.7270,32.3106,42.3850,37.3190,124.1827,37.6329,130.6747,43.0060,37.3193,55.4907,37.9676,55.9576,28.3081,59.0001,32.3317,60.8582',
  'track' => 'tillerson,italia elezione,italia elezioni,italia election,italia elections,italy elezione,italy elezioni,italy election,italy elections,italian elezione,italian elezioni,italian election,italian elections,italiano elezione,italiano elezioni,italiano election,italiano elections,elezioni2018,ElezioniPolitiche2018,4marzovotoLega,elezioni,4marzo,4Marzo2018,nord stream,nordstream,pipeline russia,pipeline russian,pipeline rusland,pipeline russisk,gazprom denmark,gazprom pipeline,gazprom danish,gazprom dansk,Gazprom dänisch,Gazprom dänischer,Gazprom dänemark,Gazprom rørledning,nordstream2,nord stream 2,germandeathcamps,germandeathcampsnotpolish,polishdeathcamps,salisbury,skripal,novichok,nerve agent,salisburyattack',
)
2018-03-28 19:21:34	stream stopped - error tmhOAuth::__set_state(array(
   'response' => 
  array (
    'raw' => 'HTTP/1.1 100 Continue

HTTP/1.1 200 OK
connection: close
content-Encoding: gzip
content-type: application/json
date: Wed, 28 Mar 2018 03:00:02 GMT
server: tsa
transfer-encoding: chunked
x-connection-hash: b95b5a9e8e31151afb313e7233571119

1',
    'content-length' => 0,
    'headers' => 
    array (
      'HTTP/1.1 100 Continue' => '',
      '' => 
      array (
        0 => '',
        1 => '',
      ),
      'HTTP/1.1 200 OK' => '',
      'connection' => 'close',
      'content-Encoding' => 'gzip',
      'content-type' => 'application/json',
      'date' => 'Wed, 28 Mar 2018 03:00:02 GMT',
      'server' => 'tsa',
      'transfer-encoding' => 'chunked',
      'x-connection-hash' => 'b95b5a9e8e31151afb313e7233571119',
    ),
    'code' => 200,
    'response' => true,
    'info' => 
    array (
      'url' => 'https://stream.twitter.com/1.1/statuses/filter.json',
      'content_type' => 'application/json',
      'http_code' => 200,
      'header_size' => 250,
      'request_size' => 597,
      'filetime' => -1,
      'ssl_verify_result' => 0,
      'redirect_count' => 0,
      'total_time' => 58893.006724999999,
      'namelookup_time' => 0.12491099999999999,
      'connect_time' => 0.13752,
      'pretransfer_time' => 0.17363799999999999,
      'size_upload' => 1069.0,
      'size_download' => 114978475.0,
      'speed_download' => 1952.0,
      'speed_upload' => 0.0,
      'download_content_length' => -1.0,
      'upload_content_length' => 1069.0,
      'starttransfer_time' => 0.186421,
      'redirect_time' => 0.0,
      'redirect_url' => '',
      'primary_ip' => '199.16.156.217',
      'certinfo' => 
      array (
      ),
      'primary_port' => 443,
      'local_ip' => '172.31.28.158',
      'local_port' => 34638,
      'request_header' => 'POST /1.1/statuses/filter.json HTTP/1.1
Host: stream.twitter.com
User-Agent: tmhOAuth 0.8.3+SSL - //github.com/themattharris/tmhOAuth
Accept: */*
Accept-Encoding: deflate, gzip
Authorization: OAuth oauth_consumer_key="XG5bUoF6nIcbeWKJVTmVXwFJN", oauth_nonce="e38fbbf27352d9a9d885a3714625db3d", oauth_signature="3tVmvZGV86hlBcPNoOlI13L8MPg%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1522206001", oauth_token="334400519-hnhbc3iZfuJI2JiTdEIjQsMVtEUpHyWdAKVDlCgv", oauth_version="1.0"
Content-Length: 1069
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue

',
    ),
    'error' => '',
    'errno' => 0,
  ),
   'buffer' => '',
   'config' => 
  array (
    'user_agent' => 'tmhOAuth 0.8.3+SSL - //github.com/themattharris/tmhOAuth',
    'host' => 'stream.twitter.com',
    'consumer_key' => 'XG5bUoF6nIcbeWKJVTmVXwFJN',
    'consumer_secret' => 'QmMH1ebe5wYj5O3JacmpZVmcuAP1gbFrLvPhQarPI9FlpfSa4U',
    'token' => '334400519-hnhbc3iZfuJI2JiTdEIjQsMVtEUpHyWdAKVDlCgv',
    'secret' => 'jRzDQiSPLqCFIxfXUhFQA2oZdouHep73VGqPuG8REMSGT',
    'bearer' => '',
    'oauth_version' => '1.0',
    'oauth_signature_method' => 'HMAC-SHA1',
    'curl_http_version' => 2,
    'curl_connecttimeout' => 30,
    'curl_timeout' => 10,
    'curl_ssl_verifyhost' => 2,
    'curl_ssl_verifypeer' => true,
    'use_ssl' => true,
    'curl_cainfo' => '/var/www/dmi-tcat/capture/common/tmhOAuth/cacert.pem',
    'curl_capath' => '/var/www/dmi-tcat/capture/common/tmhOAuth',
    'curl_followlocation' => false,
    'curl_proxy' => false,
    'curl_proxyuserpwd' => false,
    'curl_encoding' => '',
    'is_streaming' => true,
    'streaming_eol' => '
',
    'streaming_metrics_interval' => 10,
    'as_header' => true,
    'force_nonce' => false,
    'force_timestamp' => false,
    'streaming_callback' => 'tracker_streamCallback',
  ),
   'request_settings' => 
  array (
    'params' => 
    array (
      'locations' => '35.7270,32.3106,42.3850,37.3190,124.1827,37.6329,130.6747,43.0060,37.3193,55.4907,37.9676,55.9576,28.3081,59.0001,32.3317,60.8582',
      'track' => 'tillerson,italia elezione,italia elezioni,italia election,italia elections,italy elezione,italy elezioni,italy election,italy elections,italian elezione,italian elezioni,italian election,italian elections,italiano elezione,italiano elezioni,italiano election,italiano elections,elezioni2018,ElezioniPolitiche2018,4marzovotoLega,elezioni,4marzo,4Marzo2018,nord stream,nordstream,pipeline russia,pipeline russian,pipeline rusland,pipeline russisk,gazprom denmark,gazprom pipeline,gazprom danish,gazprom dansk,Gazprom dänisch,Gazprom dänischer,Gazprom dänemark,Gazprom rørledning,nordstream2,nord stream 2,germandeathcamps,germandeathcampsnotpolish,polishdeathcamps,salisbury,skripal,novichok,nerve agent,salisburyattack',
    ),
    'headers' => 
    array (
      'Host' => 'stream.twitter.com',
      'Authorization' => 'OAuth oauth_consumer_key="XG5bUoF6nIcbeWKJVTmVXwFJN", oauth_nonce="e38fbbf27352d9a9d885a3714625db3d", oauth_signature="3tVmvZGV86hlBcPNoOlI13L8MPg%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1522206001", oauth_token="334400519-hnhbc3iZfuJI2JiTdEIjQsMVtEUpHyWdAKVDlCgv", oauth_version="1.0"',
    ),
    'with_user' => true,
    'multipart' => false,
    'method' => 'POST',
    'without_bearer' => false,
    'url' => 'https://stream.twitter.com/1.1/statuses/filter.json',
    'oauth1_params' => 
    array (
      'oauth_consumer_key' => 'XG5bUoF6nIcbeWKJVTmVXwFJN',
      'oauth_nonce' => 'e38fbbf27352d9a9d885a3714625db3d',
      'oauth_signature' => '3tVmvZGV86hlBcPNoOlI13L8MPg%3D',
      'oauth_signature_method' => 'HMAC-SHA1',
      'oauth_timestamp' => '1522206001',
      'oauth_token' => '334400519-hnhbc3iZfuJI2JiTdEIjQsMVtEUpHyWdAKVDlCgv',
      'oauth_version' => '1.0',
    ),
    'prepared_params' => 
    array (
      'locations' => '35.7270%2C32.3106%2C42.3850%2C37.3190%2C124.1827%2C37.6329%2C130.6747%2C43.0060%2C37.3193%2C55.4907%2C37.9676%2C55.9576%2C28.3081%2C59.0001%2C32.3317%2C60.8582',
      'track' => 'tillerson%2Citalia%20elezione%2Citalia%20elezioni%2Citalia%20election%2Citalia%20elections%2Citaly%20elezione%2Citaly%20elezioni%2Citaly%20election%2Citaly%20elections%2Citalian%20elezione%2Citalian%20elezioni%2Citalian%20election%2Citalian%20elections%2Citaliano%20elezione%2Citaliano%20elezioni%2Citaliano%20election%2Citaliano%20elections%2Celezioni2018%2CElezioniPolitiche2018%2C4marzovotoLega%2Celezioni%2C4marzo%2C4Marzo2018%2Cnord%20stream%2Cnordstream%2Cpipeline%20russia%2Cpipeline%20russian%2Cpipeline%20rusland%2Cpipeline%20russisk%2Cgazprom%20denmark%2Cgazprom%20pipeline%2Cgazprom%20danish%2Cgazprom%20dansk%2CGazprom%20d%C3%A4nisch%2CGazprom%20d%C3%A4nischer%2CGazprom%20d%C3%A4nemark%2CGazprom%20r%C3%B8rledning%2Cnordstream2%2Cnord%20stream%202%2Cgermandeathcamps%2Cgermandeathcampsnotpolish%2Cpolishdeathcamps%2Csalisbury%2Cskripal%2Cnovichok%2Cnerve%20agent%2Csalisburyattack',
    ),
    'basestring_params' => 'locations=35.7270%2C32.3106%2C42.3850%2C37.3190%2C124.1827%2C37.6329%2C130.6747%2C43.0060%2C37.3193%2C55.4907%2C37.9676%2C55.9576%2C28.3081%2C59.0001%2C32.3317%2C60.8582&oauth_consumer_key=XG5bUoF6nIcbeWKJVTmVXwFJN&oauth_nonce=e38fbbf27352d9a9d885a3714625db3d&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1522206001&oauth_token=334400519-hnhbc3iZfuJI2JiTdEIjQsMVtEUpHyWdAKVDlCgv&oauth_version=1.0&track=tillerson%2Citalia%20elezione%2Citalia%20elezioni%2Citalia%20election%2Citalia%20elections%2Citaly%20elezione%2Citaly%20elezioni%2Citaly%20election%2Citaly%20elections%2Citalian%20elezione%2Citalian%20elezioni%2Citalian%20election%2Citalian%20elections%2Citaliano%20elezione%2Citaliano%20elezioni%2Citaliano%20election%2Citaliano%20elections%2Celezioni2018%2CElezioniPolitiche2018%2C4marzovotoLega%2Celezioni%2C4marzo%2C4Marzo2018%2Cnord%20stream%2Cnordstream%2Cpipeline%20russia%2Cpipeline%20russian%2Cpipeline%20rusland%2Cpipeline%20russisk%2Cgazprom%20denmark%2Cgazprom%20pipeline%2Cgazprom%20danish%2Cgazprom%20dansk%2CGazprom%20d%C3%A4nisch%2CGazprom%20d%C3%A4nischer%2CGazprom%20d%C3%A4nemark%2CGazprom%20r%C3%B8rledning%2Cnordstream2%2Cnord%20stream%202%2Cgermandeathcamps%2Cgermandeathcampsnotpolish%2Cpolishdeathcamps%2Csalisbury%2Cskripal%2Cnovichok%2Cnerve%20agent%2Csalisburyattack',
    'postfields' => 'locations=35.7270%2C32.3106%2C42.3850%2C37.3190%2C124.1827%2C37.6329%2C130.6747%2C43.0060%2C37.3193%2C55.4907%2C37.9676%2C55.9576%2C28.3081%2C59.0001%2C32.3317%2C60.8582&track=tillerson%2Citalia%20elezione%2Citalia%20elezioni%2Citalia%20election%2Citalia%20elections%2Citaly%20elezione%2Citaly%20elezioni%2Citaly%20election%2Citaly%20elections%2Citalian%20elezione%2Citalian%20elezioni%2Citalian%20election%2Citalian%20elections%2Citaliano%20elezione%2Citaliano%20elezioni%2Citaliano%20election%2Citaliano%20elections%2Celezioni2018%2CElezioniPolitiche2018%2C4marzovotoLega%2Celezioni%2C4marzo%2C4Marzo2018%2Cnord%20stream%2Cnordstream%2Cpipeline%20russia%2Cpipeline%20russian%2Cpipeline%20rusland%2Cpipeline%20russisk%2Cgazprom%20denmark%2Cgazprom%20pipeline%2Cgazprom%20danish%2Cgazprom%20dansk%2CGazprom%20d%C3%A4nisch%2CGazprom%20d%C3%A4nischer%2CGazprom%20d%C3%A4nemark%2CGazprom%20r%C3%B8rledning%2Cnordstream2%2Cnord%20stream%202%2Cgermandeathcamps%2Cgermandeathcampsnotpolish%2Cpolishdeathcamps%2Csalisbury%2Cskripal%2Cnovichok%2Cnerve%20agent%2Csalisburyattack',
    'basestring' => 'POST&https%3A%2F%2Fstream.twitter.com%2F1.1%2Fstatuses%2Ffilter.json&locations%3D35.7270%252C32.3106%252C42.3850%252C37.3190%252C124.1827%252C37.6329%252C130.6747%252C43.0060%252C37.3193%252C55.4907%252C37.9676%252C55.9576%252C28.3081%252C59.0001%252C32.3317%252C60.8582%26oauth_consumer_key%3DXG5bUoF6nIcbeWKJVTmVXwFJN%26oauth_nonce%3De38fbbf27352d9a9d885a3714625db3d%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1522206001%26oauth_token%3D334400519-hnhbc3iZfuJI2JiTdEIjQsMVtEUpHyWdAKVDlCgv%26oauth_version%3D1.0%26track%3Dtillerson%252Citalia%2520elezione%252Citalia%2520elezioni%252Citalia%2520election%252Citalia%2520elections%252Citaly%2520elezione%252Citaly%2520elezioni%252Citaly%2520election%252Citaly%2520elections%252Citalian%2520elezione%252Citalian%2520elezioni%252Citalian%2520election%252Citalian%2520elections%252Citaliano%2520elezione%252Citaliano%2520elezioni%252Citaliano%2520election%252Citaliano%2520elections%252Celezioni2018%252CElezioniPolitiche2018%252C4marzovotoLega%252Celezioni%252C4marzo%252C4Marzo2018%252Cnord%2520stream%252Cnordstream%252Cpipeline%2520russia%252Cpipeline%2520russian%252Cpipeline%2520rusland%252Cpipeline%2520russisk%252Cgazprom%2520denmark%252Cgazprom%2520pipeline%252Cgazprom%2520danish%252Cgazprom%2520dansk%252CGazprom%2520d%25C3%25A4nisch%252CGazprom%2520d%25C3%25A4nischer%252CGazprom%2520d%25C3%25A4nemark%252CGazprom%2520r%25C3%25B8rledning%252Cnordstream2%252Cnord%2520stream%25202%252Cgermandeathcamps%252Cgermandeathcampsnotpolish%252Cpolishdeathcamps%252Csalisbury%252Cskripal%252Cnovichok%252Cnerve%2520agent%252Csalisburyattack',
    'signing_key' => 'QmMH1ebe5wYj5O3JacmpZVmcuAP1gbFrLvPhQarPI9FlpfSa4U&jRzDQiSPLqCFIxfXUhFQA2oZdouHep73VGqPuG8REMSGT',
  ),
   'metrics' => 
  array (
    'start' => 1522206001,
    'interval_start' => 1522264889,
    'messages' => 74077,
    'last_messages' => 74075,
    'bytes' => 382933214,
    'last_bytes' => 382928184,
    'mps' => 1.3,
    'bps' => 5697.1000000000004,
  ),
))
2018-03-28 19:21:34	processing buffer before exit`

**Comment by dentoir** [comment]
Probably related to #309 which is now fixed.

Can your perhaps `git pull` and try again?

**Comment by jamestripp** [comment]
Hi @dentoir,

This issue happened before and was fixed by running controller.php. So I don't think it is related.

I'll keep an eye on the servers and let you know if it reoccurs.

Best,

James

**Comment by dentoir** [comment]
Assuming this was related to that fixed issue.
