### ISSUE TITLE
Only export tweets that conatin links

### ISSUE THREAD

**Issue by bipsen** [digitalmethodsinitiative/dmi-tcat#312]
The pie chart in the selection overview shows the percentages of how many of the tweets contain links, and the statistics export contains this information as well. Is it possible to do a tweet export in the style of full export, but only with the tweets containing links (to external websites)?

**Comment by ErikBorra** [comment]
You might try just adding http in the url input box, click update, then full export (incl URLs).

**Comment by bipsen** [comment]
Thanks, that works! But many of the tweets are given in the format "domain.com". Won't this only return links that have "http" in them (http://domain.com)?

**Comment by ErikBorra** [comment]
There should be a full url column as well.

**Comment by bipsen** [comment]
Okay. When I put in http and do full export, I get a csv file with no data (only headers) though. It works when I do 1000 random.

**Comment by dentoir** [comment]
Hi @bipsen 

Do you still have a problem with exporting URLs? To help you further we'd need PHP error logs and all other relevant log files as described here: https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Bug-submission-guidelines

**Comment by dentoir** [comment]
insufficient data
