### ISSUE TITLE
Digitalocean denial of service

### ISSUE THREAD

**Issue by keremyildirim** [digitalmethodsinitiative/dmi-tcat#314]
Hi, 
I'm a new user and I don't know much about servers or cloud computing but I love using Dmi-tcat and I have been playing around with it for the last week or so. I opened up a Debian server using my DigitalOcean account with. Everything seems to be working fine except I am trying to capture a lot of tweets and for the last couple of days, I have been receiving an email from Digitalocean saying they deteced a "denial of service attack" with an outbound traffic from my server exceeding 1037.29 Mb/s (inbound traffic 0.4 mb/s).

For this reason, they take my server offline. This happens almost at the same time, around 8:30 pm every evening. I was wondering if there is a way to fix this, because it basically disrupts the whole operation and I need to create a new server from a backup which is very inconvenient and my server stops collecting tweets in the meantime.

Thank you for your help

Kerem

**Comment by ErikBorra** [comment]
Hi Kerem,

it sounds like somebody had access to your server and managed to install some malicious software. It seems to be backed-up too, so every time you'll restore the backup you'll have the same problem. I suggest you make a back-up of your database and /var/www/dmi-tcat/config.php file and then reinstall dmi-tcat from scratch on a _new_ machine.

Best,

Erik
