### ISSUE TITLE
database upgrade stuck

### ISSUE THREAD

**Issue by supersambo** [digitalmethodsinitiative/dmi-tcat#316]
Hi, 
I just noticed that I get the following message in my query manager and that dmi-tcat stopped capturing tweets on 11th of May (I have auto aupdate enabled)

`Your database is out-of-date and needs to be upgraded to fix bugs. Follow the documentation and run the command-line script common/upgrade.php from your shell.`

When I try to run the update I get 

`2018-05-16 08:40:31     upgrade.php already running, skipping this check`

`ps aux | grep upgrade` returns the following

`supersa+ 10177  0.0  0.0   4504   520 ?        S    May08   0:00 sh -c nohup php upgrade.php --non-interactive --au2`
`supersa+ 10178  0.1  8.1 983916 665176 ?       S    May08  11:43 php upgrade.php --non-interactive --au2`
`supersa+ 24662  0.0  0.0  15752  1012 pts/1    S+   10:45   0:00 grep --color=auto upgrade
`

Given that this concerns database updates I' hesitating to kill those apparently stuck processes. 

Is there a correct and secure way to do this?

Best, s

**Comment by supersambo** [comment]
Update:
I finally decided to kill the running upgrade processes which got me tracking again. Also because dmi-tcats webinterface had become very slow (took around 10 seconds to load the page)

I then restartet upgrade.php in a separate tmux session so I could monitor it. After several hours I noticed that the upgrade process was extremely slow. I'm not entirely sure what this does but apparently it took my server around 5-8 seconds to process an average of around 70 tweets. Having datasets with several million tweets this would have taken forever.

So I canceled the script, ran it again but this time chose not to upgrade those databases. The webinterface remained slow and I was still getting the message that I had to upgrade the databases. I tried to export my corrupt databases via the webinterface in order to delete them afterwards as they were not currently collecting. However the csv export did not return anything. 

Lucky enough those datasets were not important at all so I deleted them entirely without any backup. Dmi-tcat is now collecting again and the webinterface is working properly! 

Not sure if I should leave this Issue open as this is not a feasible solution for the most cases? In any cas my problem is solved for now.

**Comment by dentoir** [comment]
Hi @supersambo 

The interrupted capture is probably related to locking contention. You tracking process is trying to insert tweets into the database while it is being upgraded. If you have a fast disk (SSD) and machine, I've experienced the lock times can be acceptable, but if the machine is too slow, it may grind to a halt. What may help, is adjusting the following line in your config.php file:

`define('USE_INSERT_DELAYED', true);`

Unfortunately there is no simple solution for this issue, other than skipping the upgrade, or perhaps: start a different bin with the same query and slowly upgrade the archived bin which should prevent all locking. The upgrade script needs to perform `UPDATE` statements on the tables and these take a very long time on large MyISAM tables. The upgrade script sorts tables by size, starting with the smallest bins first.

Best,

Emile

**Comment by dentoir** [comment]
An additional comment about the running speed. The nr. of tweets updated shouldn't be divided by the total nr. of tweets in the bin to assess the upgrade duration. Only those tweets which need to be updated in relation to issue #311 are updated, and only for the affected timeframe. Nevertheless it will still take very long for very large bins.

**Comment by supersambo** [comment]
Hi @dentoir,
thank you for the clarification. I changed the setting you mentioned and lowered the auto-update level!

Best, 
stephan
