### ISSUE TITLE
autoupdate

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#317]
Hi,

My local TCAT installation with AUTOUPDATE set to TRUE, is indicating to install a new version. The link provided is http://192.168.2.4/capture/index.php# and when clicking it, nothing happens. Any idea to activate the update process?

Arnout

**Comment by dentoir** [comment]
Hi,

In `config.php` the variable `BASE_URL` should be set to the root URL of your server. In your example it seems to be an IP address. This may be the cause of the problem, but I'm not sure.

To start an upgrade manually, you may login to the console/ssh and run the script the script `upgrade.php` from withing the `common` subdirectory.

Best,

Emile
