### ISSUE TITLE
lookup.php gives error

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#318]
Hi,

I just wanted to import a new set of tweets using lookedup.php after exporting the ids using parse-csv.php. Although this always worked fine (last succesfull usage was last week), I now got errors.

First error indicated problems with SQL-syntax. Now it only indicates 'PHP Notice: Undefined index: statuses in /var/www/dmi-tcat/capture/common/functions.php on line 2639.' This message appears each few minutes untill I quit with CTRL-C.

Any suggestions how to solve it? I checked functions.php wut cannot find any strange things...

Arnout

**Comment by arnoutponsioen** [comment]
Now, after local login via my browser, I also get errors... 'pagina werkt niet'

**Comment by dentoir** [comment]
Hi @arnoutponsioen 

Your installation appears to be missing crucial PHP module dependencies: `mbstring` and `curl` and perhaps others.
Did you use the auto installer on the machine you wish to import the tweets to? The auto installer should automatically install those dependencies.

Best,

Emile

**Comment by arnoutponsioen** [comment]
Hi Dentoir,
I don't know how dependencies are suddenly missing. I worked flawlessly more than 2 years, now it doesn't anymore. I try to reinstall TCAT. Thanks.
