### ISSUE TITLE
installing TCAT on synology drive

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#319]
Hi,

I have TCAT running on seperate older PC on which ubuntu server is installed. Worked fine.
I would like to install it on my synology networkdrive which I use mainly als cloud storage and is always on. PHP and SQL are installed. 

My question is if anyone installed TCAT on a synology drive and has good experiences with it?

Arnout

**Comment by dentoir** [comment]
I've not used the technology, but TCAT can establish connections to any properly setup MySQL server. It does not need to be local.

**Comment by arnoutponsioen** [comment]
thanks dentoir. I will wait for someone who has used synology for installing tcat.
