### ISSUE TITLE
new install - problem finding index files?

### ISSUE THREAD

**Issue by arnoutponsioen** [digitalmethodsinitiative/dmi-tcat#322]
Hi, I try to reinstall TCAT due to problems before. I installed ubuntu 15.10 fresh. They run the install script. I downloads all kinds of things, but then suddenly seems to fail to find other 'inedx-files'. I include a screenshot. Any suggestions??

![image](https://user-images.githubusercontent.com/17899995/41525515-90be573e-72e1-11e8-8924-68e7ea917eb0.png)

**Comment by arnoutponsioen** [comment]
Anyone to suggest a solution for this install problem?

**Comment by dentoir** [comment]
I'm closing this as this is old. The auto-installer now explicitly supports Debian and Ubuntu LTS and no longer older versions, to make install related questions easier to answer.
