### ISSUE TITLE
problem with database upgrade in linux

### ISSUE THREAD

**Issue by zhanglipku** [digitalmethodsinitiative/dmi-tcat#325]
hello my TCAT is run on Ubuntu on AWS. I used the automatic option. It runs fine.
I was prompted to upgrade the database and was provided a link to the instruction page. On the nstruction page I was asked to find the tcat directory, but all I get using the "ls" command is 
![screen shot 2018-07-07 at 12 01 09 pm](https://user-images.githubusercontent.com/17376900/42412660-813321a8-81de-11e8-8d54-da1a54866f88.png)

I don't find a directory named "dmi-tcat" or "common"  created on my AWS server (I used this EC2 instance solely for tcat). Please help.

Instead, my "home" directory has two sub folders, one is "tcat" which is empty, the other is "Ubuntu", where the "tcat-install-linux.sh" is stored. Neither has the "upgrade.php" file.

**Comment by brendam** [comment]
I think you will find it here `/var/www/dmi-tcat`.   Try `ls /var/www/dmi-tcat’ and if that is where it is use `cd /var/www/dmi-tcat/` to go to that directory.

**Comment by zhanglipku** [comment]
Thank you very much! This is helpful. I found the directory, but still have problems. I followed the instruction by typing the following: $cd common->$ screen $php upgrade.php. I got a series of error messages below:

![screen shot 2018-07-08 at 2 03 15 am](https://user-images.githubusercontent.com/17376900/42417253-87e8f4f8-8253-11e8-8246-949599c69e05.png)

Before I run the upgrade scrip I stopped all the tracking bins already. Your help will be appreciated.

**Comment by zhanglipku** [comment]
hi @dentoir 

I tried this common, but it gives me an error message:

![screen shot 2018-08-07 at 10 31 09 pm](https://user-images.githubusercontent.com/17376900/43812946-a9fadc4a-9a91-11e8-80de-4d6758ddd7ed.png)

**Comment by dentoir** [comment]
hi @zhanglipku 

It appears one of your MySQL tables needs to be repaired. Did your server crash or has it ran out of disk space/memory? You should run (from inside a `screen`):

`mysqlcheck --repair --databases twittercapture`

Without repairing the table the bin 'thestorm' ans possibly others won't be able to capture tweets and you won't be able to upgrade.
