### ISSUE TITLE
Re hashtag-URL grpah in TCAT

### ISSUE THREAD

**Issue by sameeh-s** [digitalmethodsinitiative/dmi-tcat#328]
I'm trying to  to study URLs associated with a specific hashtag in my dataset. To do that I'm using the bi-partite hashtag-URL network. The network and csv file however include all other hashtags in the subselection of my dataset. Is there a way to only include the hashtag I'm interested in?

**Comment by dentoir** [comment]
Hi @sameeh-s 

In graph context these hashtags are unconnected right? This is a known issue and indeed causes some confusion.

**Comment by dentoir** [comment]
All nodes are always added to the datafile, links are only added when filter conditions are met.
