### ISSUE TITLE
Feature suggestion: exporting data directly to AWS S3

### ISSUE THREAD

**Issue by zhanglipku** [digitalmethodsinitiative/dmi-tcat#330]
Not sure if it's possible or already available. Please let me know!

**Comment by dentoir** [comment]
Again, quite a delayed reply, but TCAT will not support this on the short-term.

However, you could play around with FUSE. Mount an S3 backed partition under /var/www/dmi-tcat/analysis/cache and your CSV files should be directly stored in the Amazon cloud. Never tried it, but it should work.
