### ISSUE TITLE
Capture not working -  Aborted connection to db: 'twittercapture' user: '<user>' host: 'localhost' (Got an error writing communication packets)

### ISSUE THREAD

**Issue by dormeir999** [digitalmethodsinitiative/dmi-tcat#331]
Hi everyone,

I have 5 TCAT servers, all of them with the same configuration, the biggest of them has 73 milion tweets,
and it stopped writing tweets to the DB, though the query bin is up and running.
I saw "Capture stopping #302" issue, checked that I have posix and pcntl modules, deleted my /proc, performed an upgrade of the app and the DB, pinging api.twitter.com shows 0% packet loss. I'm not sure if I can perform the strace check since I don't see the track proccess running at all, only the urlexpand:

ps -ef | grep tcat
tcat      1731     1  0 14:17 ?        00:00:00 /usr/bin/php /var/www/dmi-tcat/capture/stream/../../helpers/urlexpand              .php
tcat      1740  1731  0 14:17 ?        00:00:00 /usr/bin/php /var/www/dmi-tcat/capture/stream/../../helpers/urlexpand              .php

I get no output when I run the controller manually - 
![image](https://user-images.githubusercontent.com/17915074/45100034-59a06d80-b131-11e8-9d25-a4e036356e4c.png)

**This is what In the mysql error.log:**
tail /var/log/mysql/error.log
2018-09-05T14:07:18.526829Z 0 [Note] Plugin 'FEDERATED' is disabled.
2018-09-05T14:07:18.528242Z 0 [Note] InnoDB: Buffer pool(s) load completed at 180905 14:07:18
2018-09-05T14:07:18.542212Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
2018-09-05T14:07:18.542228Z 0 [Note] Server hostname (bind-address): '127.0.0.1'; port: 3306
2018-09-05T14:07:18.542237Z 0 [Note]   - '127.0.0.1' resolves to '127.0.0.1';
2018-09-05T14:07:18.542261Z 0 [Note] Server socket created on IP: '127.0.0.1'.
2018-09-05T14:07:18.645094Z 0 [Note] Event Scheduler: Loaded 0 events
2018-09-05T14:07:18.645272Z 0 [Note] /usr/sbin/mysqld: ready for connections.
Version: '5.7.23-0ubuntu0.16.04.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  (Ubuntu)
2018-09-05T14:13:28.147729Z 7 [Note] Aborted connection 7 to db: 'twittercapture' user: 'tcatdbuser' host: 'localhost' (Got an error writing communication packets)

There are no broken tables or missing data files, for all I know. I thought it might be a resources problem. I'm using  Ubuntu 16.04.3 LTS \n \l, Amazon AWS t2.large virutal shared server, optimized EBS (not SSD), 2vCPUs, 8G RAM, PHP 7.0.30-0ubuntu0.16.04.1, MySQL version 5.7.23-0ubuntu0.16.04.1, and the analysis and capture web pages are very slow... so I used mysqltuner to perform fine tuning, and now it's recommending the key_buffer_size to be over 22.1G, which I don't have. Do you think that might be the problem?
**here's mysqltuner output:**

 perl mysqltuner.pl
 >>  MySQLTuner 1.7.10 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[OK] Logged in using credentials from Debian maintenance account.
[OK] Currently running supported MySQL version 5.7.23-0ubuntu0.16.04.1
[OK] Operating on 64-bit architecture

-------- Log file Recommendations ------------------------------------------------------------------
[--] Log file: /var/log/mysql/error.log(285K)
[OK] Log file /var/log/mysql/error.log exists
[OK] Log file /var/log/mysql/error.log is readable.
[OK] Log file /var/log/mysql/error.log is not empty
[OK] Log file /var/log/mysql/error.log is smaller than 32 Mb
[!!] /var/log/mysql/error.log contains 139 warning(s).
[!!] /var/log/mysql/error.log contains 86 error(s).
[--] 26 start(s) detected in /var/log/mysql/error.log
[--] 1) 2018-09-05T15:40:45.400029Z 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 2) 2018-09-05T15:39:07.020182Z 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 3) 2018-09-05T15:37:45.484206Z 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 4) 2018-09-05T15:36:48.574340Z 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 5) 2018-09-05T15:34:58.353030Z 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 6) 2018-09-05T15:33:38.621205Z 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 7) 2018-09-05T15:32:32.116199Z 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 8) 2018-09-05T15:30:49.532739Z 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 9) 2018-09-05T15:29:57.000689Z 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 10) 2018-09-05T15:28:51.240210Z 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 40 shutdown(s) detected in /var/log/mysql/error.log
[--] 1) 2018-09-05T15:40:44.749774Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
[--] 2) 2018-09-05T15:39:06.321601Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
[--] 3) 2018-09-05T15:37:44.893040Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
[--] 4) 2018-09-05T15:36:47.680395Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
[--] 5) 2018-09-05T15:34:57.436660Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
[--] 6) 2018-09-05T15:33:37.894570Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
[--] 7) 2018-09-05T15:32:31.330402Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
[--] 8) 2018-09-05T15:30:48.816517Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
[--] 9) 2018-09-05T15:29:56.266529Z 0 [Note] /usr/sbin/mysqld: Shutdown complete
[--] 10) 2018-09-05T15:28:50.421887Z 0 [Note] /usr/sbin/mysqld: Shutdown complete

-------- Storage Engine Statistics -----------------------------------------------------------------
[--] Status: +ARCHIVE +BLACKHOLE +CSV -FEDERATED +InnoDB +MEMORY +MRG_MYISAM +MyISAM +PERFORMANCE_SCHEMA
[--] Data in InnoDB tables: 16.0K (Tables: 1)
[--] Data in MyISAM tables: 65.6G (Tables: 25)
[OK] Total fragmented tables: 0

-------- Security Recommendations ------------------------------------------------------------------
[OK] There are no anonymous accounts for any database users
[OK] All database users have passwords assigned
[--] There are 618 basic passwords in the list.

-------- CVE Security Recommendations --------------------------------------------------------------
[OK] NO SECURITY CVE FOUND FOR YOUR VERSION

-------- Performance Metrics -----------------------------------------------------------------------
[--] Up for: 5s (23 q [4.600 qps], 11 conn, TX: 44K, RX: 2K)
[--] Reads / Writes: 100% / 0%
[--] Binary logging is disabled
[--] Physical Memory     : 7.8G
[--] Max MySQL memory    : 7.2G
[--] Other process memory: 120.9M
[--] Total buffers: 4.2G global + 20.6M per thread (151 max threads)
[--] P_S Max memory usage: 72B
[--] Galera GCache Max memory usage: 0B
[OK] Maximum reached memory usage: 4.2G (54.19% of installed RAM)
[!!] Maximum possible memory usage: 7.2G (92.32% of installed RAM)
[OK] Overall possible memory usage with other process is compatible with memory available
[OK] Slow queries: 0% (0/23)
[OK] Highest usage of available connections: 1% (3/151)
[OK] Aborted connections: 0.00%  (0/11)
[!!] name resolution is active : a reverse name resolution is made for each new connection and can reduce performance
[OK] Query cache is disabled by default due to mutex contention on multiprocessor machines.
[OK] No Sort requiring temporary tables
[OK] No joins without indexes
[OK] Temporary tables created on disk: 0% (0 on disk / 4 total)
[OK] Thread cache hit rate: 72% (3 created / 11 connections)
[OK] Table cache hit rate: 28% (32 open / 114 opened)
[OK] Open file limit used: 1% (11/1K)
[OK] Table locks acquired immediately: 100% (105 immediate / 105 locks)

-------- Performance schema ------------------------------------------------------------------------
[--] Memory used by P_S: 72B
[--] Sys schema is installed.

-------- ThreadPool Metrics ------------------------------------------------------------------------
[--] ThreadPool stat is disabled.

-------- MyISAM Metrics ----------------------------------------------------------------------------
[!!] Key buffer used: 18.2% (781M used / 4B cache)
[!!] Key buffer size / total MyISAM indexes: 4.0G/22.1G
[!!] Read Key buffer hit rate: 50.0% (6 cached / 3 reads)

-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[--] InnoDB Thread Concurrency: 0
[OK] InnoDB File per table is activated
[OK] InnoDB buffer pool / data size: 128.0M/16.0K
[OK] Ratio InnoDB log file size / InnoDB Buffer pool size: 17.0M * 2/128.0M should be equal 25%
[OK] InnoDB buffer pool instances: 1
[--] Number of InnoDB Buffer Pool Chunk : 1 for 1 Buffer Pool Instance(s)
[OK] Innodb_buffer_pool_size aligned with Innodb_buffer_pool_chunk_size & Innodb_buffer_pool_instances
[!!] InnoDB Read buffer efficiency: 74.34% (1130 hits/ 1520 total)
[!!] InnoDB Write Log efficiency: 0% (2 hits/ 0 total)
[OK] InnoDB log waits: 0.00% (0 waits / 2 writes)

-------- AriaDB Metrics ----------------------------------------------------------------------------
[--] AriaDB is disabled.

-------- TokuDB Metrics ----------------------------------------------------------------------------
[--] TokuDB is disabled.

-------- XtraDB Metrics ----------------------------------------------------------------------------
[--] XtraDB is disabled.

-------- RocksDB Metrics ---------------------------------------------------------------------------
[--] RocksDB is disabled.

-------- Spider Metrics ----------------------------------------------------------------------------
[--] Spider is disabled.

-------- Connect Metrics ---------------------------------------------------------------------------
[--] Connect is disabled.

-------- Galera Metrics ----------------------------------------------------------------------------
[--] Galera is disabled.

-------- Replication Metrics -----------------------------------------------------------------------
[--] Galera Synchronous replication: NO
[--] No replication slave(s) for this server.
[--] Binlog format: ROW
[--] XA support enabled: ON
[--] Semi synchronous replication Master: Not Activated
[--] Semi synchronous replication Slave: Not Activated
[--] This is a standalone server

-------- Recommendations ---------------------------------------------------------------------------
General recommendations:
    Control warning line(s) into /var/log/mysql/error.log file
    Control error line(s) into /var/log/mysql/error.log file
    MySQL was started within the last 24 hours - recommendations may be inaccurate
    Reduce your overall MySQL memory footprint for system stability
    Configure your accounts with ip or subnets only, then update your configuration with skip-name-resolve=1
Variables to adjust:
  *** MySQL's maximum memory usage is dangerously high ***
  *** Add RAM before increasing MySQL buffer variables ***
    key_buffer_size (> 22.1G)

**I do see processes running in the DB -** 
 show processlist;
+-----+------------+-----------+----------------+---------+------+----------+------------------------------------------------------------------------------------------------------+
| Id  | User       | Host      | db             | Command | Time | State    | Info                                                                                                 |
+-----+------------+-----------+----------------+---------+------+----------+------------------------------------------------------------------------------------------------------+
| 661 | tcatdbuser | localhost | twittercapture | Query   |    1 | updating | UPDATE `EN_humor_urls` SET url_followed = 'https://twitter.com/News24/status/999342972327034881', do |
| 717 | tcatdbuser | localhost | NULL           | Query   |    0 | starting | show processlist                                                                                     |
+-----+------------+-----------+----------------+---------+------+----------+------------------------------------------------------------------------------------------------------+
2 rows in set (0.00 sec)

**More information:**
**/var/www/dmi-tcat/logs/:**
tail controller.log
2018-09-05 15:03:01     not yet executing auto-update, because the last commit is less than a day old
2018-09-05 15:03:01     script track is running with pid [1913] and has been idle for 2071 seconds
2018-09-05 15:03:01     we have no information about previous running time of script track - cannot record a gap
2018-09-05 15:03:01     script track was idle for more than 600 seconds - killing and starting
2018-09-05 15:03:01     sending a TERM signal to track for 1913
2018-09-05 15:04:01     not yet executing auto-update, because the last commit is less than a day old
2018-09-05 15:04:01     script track is running with pid [1913] and has been idle for 2131 seconds
2018-09-05 15:04:01     we have no information about previous running time of script track - cannot record a gap
2018-09-05 15:04:01     script track was idle for more than 600 seconds - killing and starting

tail track.error.log
  array (
    'start' => 1536157710,
    'interval_start' => 1536157710,
    'messages' => 1,
    'last_messages' => 0,
    'bytes' => 34,
    'last_bytes' => 0,
  ),
))
2018-09-05 14:28:30     processing buffer before exit
root@ip-172-31-86-96:/var/www/dmi-tcat/logs# tail -20 track.error.log
    array (
      'language' => 'en',
      'track' => 'comedy%2Cfail%2Cfun%2CFunny%2Chaha%2CHaHaHa%2Chilarious%2Chumor%2Chumour%2Cjoke%2Cjokes%2Claugh%2Claughing%2CLOL%2Cmeme%2Cmemes',
    ),
    'basestring_params' => 'language=en&oauth_consumer_key=DNOz8bDFH1sFS8uZGlAW6aDSL&oauth_nonce=5aec1b28a51d9e47bc378c22c2aaeb0e&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1536157710&oauth_token=799854104-FNW3be9TVLSlz5kaKlQIKtCV95GN8BjUuOURuRzf&oauth_version=1.0&track=comedy%2Cfail%2Cfun%2CFunny%2Chaha%2CHaHaHa%2Chilarious%2Chumor%2Chumour%2Cjoke%2Cjokes%2Claugh%2Claughing%2CLOL%2Cmeme%2Cmemes',
    'postfields' => 'language=en&track=comedy%2Cfail%2Cfun%2CFunny%2Chaha%2CHaHaHa%2Chilarious%2Chumor%2Chumour%2Cjoke%2Cjokes%2Claugh%2Claughing%2CLOL%2Cmeme%2Cmemes',
    'basestring' => 'POST&https%3A%2F%2Fstream.twitter.com%2F1.1%2Fstatuses%2Ffilter.json&language%3Den%26oauth_consumer_key%3DDNOz8bDFH1sFS8uZGlAW6aDSL%26oauth_nonce%3D5aec1b28a51d9e47bc378c22c2aaeb0e%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1536157710%26oauth_token%3D799854104-FNW3be9TVLSlz5kaKlQIKtCV95GN8BjUuOURuRzf%26oauth_version%3D1.0%26track%3Dcomedy%252Cfail%252Cfun%252CFunny%252Chaha%252CHaHaHa%252Chilarious%252Chumor%252Chumour%252Cjoke%252Cjokes%252Claugh%252Claughing%252CLOL%252Cmeme%252Cmemes',
    'signing_key' => 'r9old5DoaZvDZgAdDcif5VHo3U8O4v8VG2eM1OHXuyVuaBHSoH&Yo2Mai3OznfcSeC8ywBX6doMSiIz1FIw8UkbVEr2xOTtt',
  ),
   'metrics' =>
  array (
    'start' => 1536157710,
    'interval_start' => 1536157710,
    'messages' => 1,
    'last_messages' => 0,
    'bytes' => 34,
    'last_bytes' => 0,
  ),
))
2018-09-05 14:28:30     processing buffer before exit

tail urlexpand.log
2018-09-05 14:40:03     starting resolve process
2018-09-05 14:43:32     finished for now
2018-09-05 14:44:02     assembling list of viable tables
2018-09-05 14:44:02     starting resolve process
2018-09-05 14:45:30     finished for now
2018-09-05 14:46:01     assembling list of viable tables
2018-09-05 14:46:02     starting resolve process
2018-09-05 14:57:10     finished for now
2018-09-05 14:58:02     assembling list of viable tables
2018-09-05 14:58:02     starting resolve process

**TCAT version** 
cd /var/www/dmi-tcat/ && (git log | head -n 1)
commit b476e6ba30d42b9110247f03429a8a25c35caf7e

**TCAT branch**
(cd /var/www/dmi-tcat/ && (git branch | grep '*'))
* master

**And the problem:**
1.EN_humor_tweets
+------------------+
| Number_of_Tweets |
+------------------+
|         72918844 |
+------------------+
+---------------------+
| UPDATE_TIME         |
+---------------------+
**| 2018-09-01 20:05:04 |**
+---------------------+

**help anybody??**
@dentoir @ekborra ?

**Comment by dormeir99o** [comment]
I've tried changing the server to x2large, with 8 vCPU and 32G RAM, and then changing mysql key buffer size to more that 22g as mysqltuner recommended, but still - track wasn't up and no error notification in mysql, apache or tcat logs... :(

**Comment by dentoir** [comment]
Hi @dormeir99o 

Thanks for this report. If you haven't managed to resolve this issue yet, could you try the following, but these are long shots:

Set `USE_INSERT_DELAYED` to `TRUE` in config.php

or,

Change your database host name from `localhost` to `127.0.0.1` - because this may force the MySQL client library to use TCP/IP connections instead of Unix sockets.

I've seen this error in different projects where the second method helped fix this error, but never in TCAT. Those were always very big INSERT statements. If this still does not work, try looking into `read` and `write` buffer sizes of your MySQL server.
