### ISSUE TITLE
tcat not capturing anymore -  Uncaught PDOException: SQLSTATE[HY000]: General error: 3167 

### ISSUE THREAD

**Issue by supersambo** [digitalmethodsinitiative/dmi-tcat#337]
I just noticed that my tcat hasn't been capturing anymore since around September 20th. I haven't changed anything in this time and do allow only trivial auto updates. 

I have now git pulled manually but the update didn't solve the issue. Here is the output of controller.log and track.error.log do not show any error. However dmitcat_track.php doesn't appear to be running (when checking via `ps ax | grep dmitcat_track.php`).

When I start the tracking script manually I get the following error
```
PHP Warning:  curl_exec(): Could not call the CURLOPT_WRITEFUNCTION in /var/www/dmi-tcat/capture/common/tmhOAuth/tmhOAuth.php on line 836
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 3167 The 'INFORMATION_SCHEMA.GLOBAL_STATUS' feature is disabled; see the documentation for 'show_compatibility_56' in /var/www/dmi-tcat/capture/common/functions.php:2880
Stack trace:
#0 /var/www/dmi-tcat/capture/common/functions.php(2880): PDOStatement->execute()
#1 /var/www/dmi-tcat/capture/common/functions.php(2241): database_activity(Object(PDO))
#2 /var/www/dmi-tcat/capture/common/functions.php(2857): TweetQueue->insertDB()
#3 /var/www/dmi-tcat/capture/common/functions.php(2622): processtweets(Array)
#4 /var/www/dmi-tcat/capture/common/tmhOAuth/tmhOAuth.php(740): tracker_streamCallback(Array, 6087, NULL)
#5 [internal function]: tmhOAuth->curlWrite(Resource id #64, '{"created_at":"...')
#6 /var/www/dmi-tcat/capture/common/tmhOAuth/tmhOAuth.php(836): curl_exec(Resource id #64)
#7 /var/www/dmi-tcat/capture/common/tmhOAuth/tmhOAuth.php(571): tmhOAuth->curlit()
#8 /var/www/dmi-tcat/capture/common/tmhOAuth/tmhOAuth.php(538): tmhOAuth->oauth1_request()
#9 /v in /var/www/dmi-tcat/capture/common/functions.php on line 2880
``
I suppose this is the issue now but I'm not sure if it was the issue before pulling?

Best, 
stephan

**Comment by supersambo** [comment]
Are there any ideas why this might be happening or any additional info I could contribute to be able to solve this? thanks!

**Comment by dentoir** [comment]
Hi @supersambo 

I assume you've updated your operating system or MySQL packages in the mean time. The error message you are seeing is caused by a SQL query TCAT performs on an apparent deprecated global variable. What MySQL version and OS are you using? This will probably be relevant to multiple installments, though I haven't seen this error before. The short-time fix is described [here](https://support.plesk.com/hc/en-us/articles/115002488349-How-to-enable-show-compatibility-56-variable-for-MySQL-5-7-url)

**Comment by dentoir** [comment]
Another fix for your issue may be to set `USE_INSERT_DELAYED` to `FALSE` in your TCAT `config.php` file.
