### ISSUE TITLE
(fixed) TCAT bin captures a tweet with partial match, if any bin captures it with expected non-partial match

### ISSUE THREAD

**Issue by xmacex** [digitalmethodsinitiative/dmi-tcat#339]
Hi, contrary to what the documentation says

> 1. a single word/hashtag. Consider that Twitter does not do partial matching on words, i.e. [twitter] will get tweets with [twitter], [#twitter] but not [twitteraddiction]

We observe (_caveat emptor_), that TCAT *does* capture partial matches.

Take for example the tweet [1055865573584842752](https://twitter.com/PatriotMarie/status/1055843945442353153)

> @PatriotMarie: #Missouri #Vote ?@HawleyMO? he cares for #Vets ??Claire McCaskill's husband invested in pro-veteran properties that tried to evict homeless vets over $233 owed rent. ? #VoteRed

If we then proceed to investigate which phrases, in which bins captured tweets

```sql
SELECT t.id, p.id, p.phrase, b.querybin
FROM NavCom2018_g5_tweets AS t
     JOIN tcat_captured_phrases AS c ON t.id = c.tweet_id
     JOIN tcat_query_phrases AS p ON c.phrase_id = p.id
     JOIN tcat_query_bins_phrases AS bp ON p.id = bp.phrase_id
     JOIN tcat_query_bins AS b ON bp.querybin_id = b.id
```

We find among many more, the following

```
id    id    phrase    querybin
1055865573584842752    882    #votered    NavCom2018_08
1055865573584842752    968    IoT air    NavCom2018_g5
```

The bin *NavCom2018_g5* tracks the conjunction of those terms, and NavCom2018_08 tracks [#votered]. Both occurrences are inconsistent with what the documentation says.

Now, if I bold the first occurrences of **iot** and **air** in the body of the given tweet, we see both [iot] and [air] exist in it.

> @Patr**iot**Marie: #Missouri #Vote ?@HawleyMO? he cares for #Vets ??Cl**air**e McCaskill's husband invested in pro-veteran properties that tried to evict homeless vets over $233 owed rent. ? #VoteRed

The expected behaviour, given *no-partial-matching*, is that [#votered] should match the tweet, and [iot air] should not.

I hypothesize that a tweet is partially matched when it is placed in various bins. I cannot at this point point to a specific location in the TCAT codebase which would prove of disprove this hypothesis. Circumstantial evidence in the case above is that the bin tracking [iot air], almost always captures tweets which one or more bins capture too.

The implication would be that if any bin captures a particular tweet from the Twitter API according to the documented behaviour, it is then distributed to bins where it is not expected to end up. The bins are not independent, but tweets bleed from bin to bin.

Am I hallucinating? Am I misunderstanding the documentation? Is this some anomaly in our installation? Am I expressing this clearly? Is this real? Can someone replicate this issue? What is the meaning of life?

**Comment by dentoir** [comment]
Hi @xmacex 

Thanks for your report. Just to be clear, did you use single quotes around your query string `'iot air'`? Could you manually verify your data somehow without joining on `tcat_captured_phrases`? That table is not actually used inside TCAT at the moment.

I did look at the ancient code which determines which keywords should be send to which bin (after the API has send us the data) and it looks like it uses a `stripos()`, and before that a `preg_match()` with identical behavior capture-wise, namely ignoring word boundaries, but tripping over special characters - see issue #199. So it looks like there is a potential for false positives there, though I can't explain your results if you did use the single quotes. I'll start a little test query myself.

**Comment by dentoir** [comment]
Hi @xmacex 

I believe I've addressed your issue in a new branch called [issue339](https://github.com/digitalmethodsinitiative/dmi-tcat/tree/issue339). Do you mind checking whether your issue occurs in that branch? As you can see from the patch there are a some subtleties involved when applying word boundary detecting for tweet texts (mainly because the `@` and `#` symbols are not considered word characters).  I believe the issue you've described should be fixed, but I now want to explicitly verify this new code doesn't actually drop candidate tweets for which I'll have to add some debugging code.

**Comment by dentoir** [comment]
The patch link is [this one](https://github.com/digitalmethodsinitiative/dmi-tcat/commit/5beaef6eb3abe6768f2b0d34f026da159c47070d)

**Comment by dentoir** [comment]
Hi @xmacex 

Did you by any chance have time to look at this patch? I'll be running it on our own servers to test it, so I can merge it soon.

**Comment by dentoir** [comment]
The issue339 branch now has an option `ENABLE_JSON_DUMP` (off by default) which writes a big JSON log file containing the raw streaming data. A handy function to verify whether a code change does not result in discarding too much data.

**Comment by xmacex** [comment]
Oh yeah, there were no quotes around [iot air], so the query was something like `kitten, aardvark, giraffe, iot air, lizard`.

**Comment by dentoir** [comment]
This has now been merged into master. I'm keeping the issue open for a little while. Using the new JSON debugging option I found the Twitter API returns tweets were the tweet text does not contain the keyword, but the quoted text does. We don't parse quoted text or store quoted text (not the same as a comment prefixing a RT!). Not sure if storing those tweets is desired behavior.
