### ISSUE TITLE
No hosts in data set (ther probably should be) on tcat11

### ISSUE THREAD

**Issue by joelgalvez** [digitalmethodsinitiative/dmi-tcat#340]
Querying for hosts OR url's on "YellowVest" data set on tcat11 gives empty result, even though there are ~200k tweets - some of them do contain urls.

**Comment by joelgalvez** [comment]
http://tcat11.digitalmethods.net/analysis/index.php?dataset=YellowVests

**Comment by dentoir** [comment]
Hi @joelgalvez 

Could you e-mail me directly at emile <@ symbol> digitalmethods.net ?
We don't discuss DMI specific server issues on Github. However, I could run a query on that dataset. Try to set the timeframe to the entire month and query 'bbc' for example.
