### ISSUE TITLE
Verifying twitter connection

### ISSUE THREAD

**Issue by roelfl** [digitalmethodsinitiative/dmi-tcat#341]
Hi,

After installing TCAT I tried out a first query but no tweets are being captured.
I verified the twitter consumer & access tokens.
Is there a way to check if the connection with Twitter is made?

Kind regards,
Roel

**Comment by dentoir** [comment]
Hi @roelfl 

Please follow the steps described [here](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Bug-submission-guidelines) and provide error log output, so we can help you.

Best,

Emile

**Comment by dentoir** [comment]
resolved
