### ISSUE TITLE
capture/index.php calls upgrade with dryrun

### ISSUE THREAD

**Issue by bosim** [digitalmethodsinitiative/dmi-tcat#347]
```capture/index.php``` contains

```$tests = upgrades(true);```

which, even in dry_run mode, is costly. Especially the query below is very costly.

```
 $sql = "SELECT id, text FROM $v WHERE " .
                    "                LENGTH(text) > 140 AND " .
                    "                created_at >= '2017-11-01 00:00:00' AND " .
                    "                LENGTH(text) - LENGTH(REPLACE(text, '#', '')) > 0 " .
                    "                ORDER BY created_at ASC";
```

I wonder why the dry_run check is run everytime ```capture/index.php```; just for convenience?

**Comment by dentoir** [comment]
For now, no warnings are displayed in the backend for upgrade steps which were added prior to May 2018 (in other words: none). Ofcourse upgrading using the `cli` method still works.

**Comment by bosim** [comment]
Nice change. Thanks for fixing.
