### ISSUE TITLE
Bin comments field input is not sanitized

### ISSUE THREAD

**Issue by xmacex** [digitalmethodsinitiative/dmi-tcat#350]
Hi, I noticed the bin comments field is not sanitized with e.g. encoding. I noticed it because I had a bin owner email wrapped in &lt;in.this@sty.le&gt; (ie with left and right beaks), and couldn't see it. I guess some standard PHP encoding function would be a sufficient fix.

![screenshot 2019-02-09 at 13 20 52](https://user-images.githubusercontent.com/879300/52520888-2f6a5300-2c6f-11e9-9a2b-d1900bbed91a.png)

**Comment by xmacex** [comment]
In addition non-Latin-1 to `<` and `>` messing with HTML side of things, characters (or that's what I suspect to be the relevant superset) make the web UI unable to modify the comment. Are our database strings in UTF-8? I need to investigate.

When a comment is

> helse tværspor added 23-04-2017 (JMB) 

```SQL
SELECT querybin,comments FROM tcat_query_bins WHERE querybin='AI';
```
Gives the funky result
```
+----------+---------------------------------------+
| querybin | comments                              |
+----------+---------------------------------------+
| AI       | helse
tv?rspor added 23-04-2017 (JMB) |
+----------+---------------------------------------+
1 row in set (0.00 sec)
```

![screenshot 2019-02-09 at 13 47 53](https://user-images.githubusercontent.com/879300/52521054-97ba3400-2c71-11e9-8d4a-b449b0d79dd2.png)

Same solution ie. a standard input encoding function should fix this, I believe.

**Comment by xmacex** [comment]
Note to self or whoever:

```php
filter_var("hi it me <mace>", FILTER_SANITIZE_FULL_SPECIAL_CHARS);
```
On the way in

**Comment by dentoir** [comment]
Hi @xmacex thangs for your bugfix! I've merge the pull request. We've been discussing a testing architectur for a while and we're not committed to performing function-level unit testing a the moment. Most probably we'll head towards a testing framework which takes a more black blox approach to test TCAT's primary functionality.

**Comment by xmacex** [comment]
Thanks @dentoir, I hope the fix is helpful for you and the community.

Regarding testing architecture, I just prefer to get some tests in place as constrains to help myself reason more clearly when writing code like this and check refactorings.

**Comment by xmacex** [comment]
Something like

```SQL 
UPDATE tcat_query_bins
SET comments = REPLACE(REPLACE(comments, '<', '&lt;'), '>', '&gt;')
WHERE comments REGEXP '.*[<>].*';
```
is the appropriate database migration, or at least get's some basic HTML encoding done.
