### ISSUE TITLE
Ubuntu 18.04 LTS support

### ISSUE THREAD

**Issue by supersambo** [digitalmethodsinitiative/dmi-tcat#351]
I updated my server today to Ubuntu 18.04 LTS. I had forgotten that dmi-tcat is not compatible with this release according to the wiki. In fact, the interface is messed up displaying fragments of php code. 
This is not a big issue in this particular case, however I was wondering why it is not compatible  (php, mysql?) and if there is a plan to get dmi-tcat working on newer ubuntu versions in the future?

**Comment by jclarkpowers** [comment]
For what it's worth, I have been running TCAT on 18.04 LTS for some months without trouble.
However, this is perhaps a specific case, as I am using the Ubuntu distribution for the Windows Subsystem for Linux.
All command line work is easily done in the Linux environment, while the Windows environment offers ready browser access to TCAT.

**Comment by supersambo** [comment]
Thanks for the reply. I'm not sure if I understand how this setup works but in any case I take this as good news! I was going to switch back to 16.04 but making this work on 18.04 would be the better option.

**Comment by jclarkpowers** [comment]
I had trouble at first with 18.04, but after replacing the default PHP (7+) with 5.6, I got TCAT working properly in the browser. Perhaps try that?

**Comment by supersambo** [comment]
After some playing around I noticed that php wasn't enabled in apache2 after the upgrade which was responsible for all the php code displayed (could have figured this out earlier). After enabling php (7.2) the analysis view is functioning again. The query manager loads but it takes an eternity (around 3 minutes).

I tried switching to php5.6 (following these steps https://tecadmin.net/switch-between-multiple-php-version-on-ubuntu/) but this did not work at all. I got a lot of fatal errors in my apache2 error log complaining about undefined methods relating to the dmi-tcats config.

**Comment by dentoir** [comment]
Hi @supersambo 

Ubuntu 18.04 should indeed be supported. Not sure about slow loading query manager. Try pulling the latest version from Github, I've made a change to upgrade detection which could speed things up.

**Comment by supersambo** [comment]
oh thanks! yes that did absolutely make things faster. /capture is now loading instantly and everything seems to work. 

I'm now running tcat on an ubuntu 18.04 machine with php 7.2 using keyword track. Apparently everything seems to working. Is there something you'd expect not to be functioning properly with this setup?

**Comment by dentoir** [comment]
Hi @supersambo no Ubuntu 18.04 and Debian 9 are now the standard Linux distributions we support in the auto installer. They should work well.
