### ISSUE TITLE
recover capture and analysis password

### ISSUE THREAD

**Issue by thmunson** [digitalmethodsinitiative/dmi-tcat#354]
Hello,

Is there a way to recover capture (admin) and analysis (tcat) passwords via Terminal?

Thanks!
Bill

**Comment by dentoir** [comment]
Hi @thmunson 

No, as is common, the passwords are stored as hashes, in `/etc/apache2/tcat.htpasswd`
You can however reset the passwords using the `htpasswd` command-line tool. Use the following command to change to password for lets say admin:

`htpasswd /etc/apache2/tcat.htpasswd admin`

You may need to reload the apache configuration afterwards, with:

`systemctl apache2 reload`

**Comment by thmunson** [comment]
Thank you! I'll give that a go.

Bill

**Comment by dentoir** [comment]
Please reopen if this failed (it should work ;-) )

**Comment by thmunson** [comment]
Hi again,

So, I tried this and I am getting a permissions error:

cannot open file /etc/apache2/tcat.htpasswd for read/write access

I tried chmod and every setting I used is denied. I also tried to change it via SFTP client and was denied.

Thanks!
Bill
