### ISSUE TITLE
This site can’t be reached...

### ISSUE THREAD

**Issue by yperry50** [digitalmethodsinitiative/dmi-tcat#355]
Hello,

Prior writing this question/post, I have reviewed several similar issues but the issue is not being resolved.
Currently on AWS EC2 with Ubuntu (Latest version). Using public IP address to load capture and analysis (via google chrome). I can see the tweets being collected but can't update overview or any other option such as update graph, etc. However in the config.php file there is private host name. 
 Any idea how I can resolve this issue?

Many Thanks,

Perry

[:var:log:mysql$ nano error.log.txt](https://github.com/digitalmethodsinitiative/dmi-tcat/files/3031937/var.log.mysql.nano.error.log.txt)
[Syslog.txt](https://github.com/digitalmethodsinitiative/dmi-tcat/files/3031961/Syslog.txt)

**Comment by dentoir** [comment]
Hi @yperry50 

Change the hostname of the serve to the proper hostname, which could be either the public IP address or a DNS name which resolves to the proper address.

During automatic installation you have the option to set the hostname. However, Amazon generates temporary hostnames which may change unless you assign a permanent IP address to the VPS.

Best,

Emile

**Comment by yperry50** [comment]
Thanks, Emile.

I changed the host name to the public IP provided by AWS. 
I also changed the config.php under /var/www/dmi-tcat to: define('BASE_URL', 'http://18.222.62.159/var/www/dmi-tcat/');
When I click on 'update overview' on any other lunch button I receive the following error message: "NOT FOUND. The requested URL /var/www/dmi-tcat/analysis/index.php was not found on this server." Apache/2.4.29 (Ubuntu) Server at 18.222.62.159 Port 80. 

If you want me to run command that will help better to debug the issue, please let me know.

Many Thanks,

Perry

**Comment by yperry50** [comment]
Resolved. I configure the config.php as follows: config.php under /var/www/dmi-tcat to: define('BASE_URL', 'http://18.222.62.159/');

I removed var/www/dmi-tcat after the IP address. Thanks again for your kind assistant, Emile.

**Comment by dentoir** [comment]
Super!
