### ISSUE TITLE
is there a limit to number of ids you can track in a query bin?

### ISSUE THREAD

**Issue by doylek1** [digitalmethodsinitiative/dmi-tcat#356]
hope this isn't a stupid question... I'm capturing a user sample. When I copy user ids into the users to track bar it accepts my 200 or so ids, but then doesn't appear to follow them all in the query manager. Is there a limit to the number of ids you can track in a single bin? Or is something else going on (if anyone knows)?

**Comment by xmacex** [comment]
@doylek1 Hi, I have seen a bin tracking 4000 users.

**Comment by dentoir** [comment]
From the Twitter API documentation _The default access level allows up to 400 track keywords, 5,000 follow userids and 25 0.1-360 degree location boxes._
https://developer.twitter.com/en/docs/tweets/filter-realtime/overview/statuses-filter.html
