### ISSUE TITLE
Installation fails related to mysql

### ISSUE THREAD

**Issue by MastaBaba** [digitalmethodsinitiative/dmi-tcat#358]
I'm trying to install dmi-tcat on a clean Ubuntu 14.04.

The automated installation process fails with this:

```
Errors were encountered while processing:
 /var/cache/apt/archives/mysql-client-core-5.5_5.5.62-0ubuntu0.14.04.1_amd64.deb
 /var/cache/apt/archives/mysql-client-5.5_5.5.62-0ubuntu0.14.04.1_amd64.deb
 /var/cache/apt/archives/mysql-server-core-5.5_5.5.62-0ubuntu0.14.04.1_amd64.deb
 /var/cache/apt/archives/mysql-server-5.5_5.5.62-0ubuntu0.14.04.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
tcat-install-linux.sh: command failed: install aborted
```

If I then try to run the install script again, I get this:

`tcat-install-linux.sh: cannot install: mysql-server already installed`

What's the best way forward?

**Comment by dentoir** [comment]
Hi @MastaBaba 

Could you expand your log output a bit, I can't see the cause of the dpkg failure from this fragment.

Best,

Emile

**Comment by MastaBaba** [comment]
Thanks, @dentoir. 

The log was rather long and I couldn't quickly see the cause. But, more importantly, I don't have it anymore.

I went for a manual install instead, which went smoothly. 

I'm guessing the following was the problem: With the automated installation, the script expects the MySQL server to be on localhost. In my case, that's not where MySQL resides.

**Comment by dentoir** [comment]
Okay!
