### ISSUE TITLE
Remote Access and Gephi Installation

### ISSUE THREAD

**Issue by yperry50** [digitalmethodsinitiative/dmi-tcat#359]
Hi there,

I succeeded to remote access my Ubuntu (ver 18.04) on EC2 with X2go (Installed x2go server on the Ubuntu and x2go client on my mac). Nonetheless, when I'm connecting and see the server, it takes less than 10 seconds when the server doesn't response any more and I have to reboot the server. 

Any idea what is happening? any other way to remote access? I read an article provided by AWS that I can connect via browser to Ubuntu but when I put the following address can't be connected (https://18.222.62.159) --> Error message: This site can’t be reached 18.222.62.159 refused to connect. 

The reason I would like to remote access is to install Gephi. Is there a way to install Gephi via terminal? 

Many Thanks,

Perry

**Comment by dentoir** [comment]
Hi @yperry50 

You want to establish an X11 connection to your AWS VPS and run Gephi remotely? That is well beyond the scope of our support I'm afraid ;-)

My suggestion would be to use Gephi locally and simply download the .gexf from the server. For remote server administration I always use SSH.

Best,

Emile

**Comment by yperry50** [comment]
Got it. Thank You. Everything is working. Many Thanks.
