### ISSUE TITLE
[SOLVED ] Trouble when using the network features on the analysis side of DMI - TCAT

### ISSUE THREAD

**Issue by fredrikjonasson** [digitalmethodsinitiative/dmi-tcat#364]
I am running into trouble when trying to export the network-graphs from the analysis/index.php of the tool. 

After pressing anyone of the network analysis button i get the following page (with php warnings turned on):
![Screenshot from 2019-05-20 11-31-47](https://user-images.githubusercontent.com/17785337/58011676-10435300-7af3-11e9-97e9-17e9fea6379c.png)

After pressing the blue link indicating that there is a file to download i get to the following page:
![Screenshot from 2019-05-20 11-33-52](https://user-images.githubusercontent.com/17785337/58011735-34069900-7af3-11e9-9aeb-1e8bae2431de.png)

Am i missing something or do you think there is some bug in the code making this happen?

**Comment by ErikBorra** [comment]
It seems like your cache dir is not writeable. Try running `chown www-data:www-data cache` in your analysis directory.

**Comment by fredrikjonasson** [comment]
I  got the answer `chown: cannot access 'cache': No such file or directory
`.

**Comment by ErikBorra** [comment]
Make sure that dmi-tcat/analysis/cache exists and that it is writeable by the web server. TCAT's installation instructions might help you out further.

**Comment by fredrikjonasson** [comment]
Following the installation instructions about the cache helped. Seems like i had gotten into some troubles with the permissions as you suggested. Thanks for the help.
