### ISSUE TITLE
from_user_timezone and from_user_utcoffset no longer available?

### ISSUE THREAD

**Issue by johannessweater** [digitalmethodsinitiative/dmi-tcat#366]
Hi -- I'm seeing that the from_user_timezone and from_user_utcoffset fields, which were previously available, are now empty for all tweets I'm collecting. This is the case in both the full data download and the "User stats (individual)" module, which is supposed to include the UTC offset. Is this a change on Twitter's end? Thanks for your help.

**Comment by niczem** [comment]
yes, it was removed by twitter because of the new eu privacy laws:
https://twittercommunity.com/t/upcoming-changes-to-the-developer-platform/104603
