### ISSUE TITLE
IP Changed

### ISSUE THREAD

**Issue by yperry50** [digitalmethodsinitiative/dmi-tcat#367]
Hi there,

AWS changed our IP address due to server upgrade. obviously, we have no access to DMI-TCAT https GUI and the DB. Could you please advise, which files (incl. locations of the files) need to be updated with the right IP address?

Many Thanks,

Yehuda

**Comment by dentoir** [comment]
Edit the variable `BASE_URL` in `/var/www/dmi-tcat/config.php` and `ServerName` in /etc/apache2/sites-available/tcat.conf
Afterwards restart apache2 with `apache2ctl restart`

**Comment by yperry50** [comment]
Thanks you, Emile. I succeeded to access the DB. However, I can not access the tables since the tables couldn't be fetch...Any idea how to fix it? In addition, I was able to access https://IP/analysis. I received the login screen, added the credential and receiving blank screen. same for /capture. Security issues?

**Comment by dentoir** [comment]
Could you send us the final 100 lines from `/var/log/apache2/error.log` ?

**Comment by yperry50** [comment]
[Wed Jun 19 00:08:45.140331 2019] [mpm_prefork:notice] [pid 1205] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed Jun 19 00:08:45.140353 2019] [core:notice] [pid 1205] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jun 19 14:07:06.387484 2019] [mpm_prefork:notice] [pid 1205] AH00173: SIGHUP received.  Attempting to restart
[Wed Jun 19 14:07:06.435101 2019] [mpm_prefork:notice] [pid 1205] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed Jun 19 14:07:06.435123 2019] [core:notice] [pid 1205] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jun 19 14:10:48.247352 2019] [php7:error] [pid 7605] [client 98.109.128.163:49503] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/analysis/common/functions.php:989\nStack trace:\n#0 /var/www/dmi-tcat/analysis/common/functions.php(989): PDOStatement->execute()\n#1 /var/www/dmi-tcat/analysis/common/functions.php(20): get_all_datasets()\n#2 /var/www/dmi-tcat/analysis/index.php(5): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 989
[Wed Jun 19 14:10:59.329545 2019] [php7:error] [pid 7600] [client 98.109.128.163:49508] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/analysis/common/functions.php:989\nStack trace:\n#0 /var/www/dmi-tcat/analysis/common/functions.php(989): PDOStatement->execute()\n#1 /var/www/dmi-tcat/analysis/common/functions.php(20): get_all_datasets()\n#2 /var/www/dmi-tcat/analysis/index.php(5): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 989
[Wed Jun 19 14:11:13.268699 2019] [php7:error] [pid 7605] [client 98.109.128.163:49514] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/analysis/common/functions.php:989\nStack trace:\n#0 /var/www/dmi-tcat/analysis/common/functions.php(989): PDOStatement->execute()\n#1 /var/www/dmi-tcat/analysis/common/functions.php(20): get_all_datasets()\n#2 /var/www/dmi-tcat/analysis/index.php(5): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 989
[Wed Jun 19 14:16:28.941751 2019] [php7:error] [pid 8126] [client 98.109.128.163:49613] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/analysis/common/functions.php:989\nStack trace:\n#0 /var/www/dmi-tcat/analysis/common/functions.php(989): PDOStatement->execute()\n#1 /var/www/dmi-tcat/analysis/common/functions.php(20): get_all_datasets()\n#2 /var/www/dmi-tcat/analysis/index.php(5): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 989
[Wed Jun 19 14:16:58.849921 2019] [php7:error] [pid 7600] [client 98.109.128.163:49621] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/analysis/common/functions.php:989\nStack trace:\n#0 /var/www/dmi-tcat/analysis/common/functions.php(989): PDOStatement->execute()\n#1 /var/www/dmi-tcat/analysis/common/functions.php(20): get_all_datasets()\n#2 /var/www/dmi-tcat/analysis/index.php(5): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 989
[Wed Jun 19 14:17:02.328751 2019] [php7:error] [pid 7603] [client 98.109.128.163:49622] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/analysis/common/functions.php:989\nStack trace:\n#0 /var/www/dmi-tcat/analysis/common/functions.php(989): PDOStatement->execute()\n#1 /var/www/dmi-tcat/analysis/common/functions.php(20): get_all_datasets()\n#2 /var/www/dmi-tcat/analysis/index.php(5): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 989
[Wed Jun 19 14:17:28.835102 2019] [php7:error] [pid 7604] [client 98.109.128.163:49633] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/analysis/common/functions.php:989\nStack trace:\n#0 /var/www/dmi-tcat/analysis/common/functions.php(989): PDOStatement->execute()\n#1 /var/www/dmi-tcat/analysis/common/functions.php(20): get_all_datasets()\n#2 /var/www/dmi-tcat/analysis/index.php(5): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 989
[Wed Jun 19 14:17:30.249445 2019] [php7:error] [pid 8126] [client 98.109.128.163:49637] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/analysis/common/functions.php:989\nStack trace:\n#0 /var/www/dmi-tcat/analysis/common/functions.php(989): PDOStatement->execute()\n#1 /var/www/dmi-tcat/analysis/common/functions.php(20): get_all_datasets()\n#2 /var/www/dmi-tcat/analysis/index.php(5): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 989
[Wed Jun 19 14:17:32.544107 2019] [php7:error] [pid 7600] [client 98.109.128.163:49639] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/capture/query_manager.php:788\nStack trace:\n#0 /var/www/dmi-tcat/capture/query_manager.php(788): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(19): getBins()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/query_manager.php on line 788
[Wed Jun 19 14:17:38.681560 2019] [php7:error] [pid 8126] [client 98.109.128.163:49643] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/capture/query_manager.php:788\nStack trace:\n#0 /var/www/dmi-tcat/capture/query_manager.php(788): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(19): getBins()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/query_manager.php on line 788
[Wed Jun 19 14:17:40.213634 2019] [php7:error] [pid 7600] [client 98.109.128.163:49646] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/analysis/common/functions.php:989\nStack trace:\n#0 /var/www/dmi-tcat/analysis/common/functions.php(989): PDOStatement->execute()\n#1 /var/www/dmi-tcat/analysis/common/functions.php(20): get_all_datasets()\n#2 /var/www/dmi-tcat/analysis/index.php(5): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 989
[Wed Jun 19 14:17:40.981840 2019] [php7:error] [pid 7603] [client 98.109.128.163:49647] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/analysis/common/functions.php:989\nStack trace:\n#0 /var/www/dmi-tcat/analysis/common/functions.php(989): PDOStatement->execute()\n#1 /var/www/dmi-tcat/analysis/common/functions.php(20): get_all_datasets()\n#2 /var/www/dmi-tcat/analysis/index.php(5): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 989
[Wed Jun 19 14:17:42.891089 2019] [php7:error] [pid 7605] [client 98.109.128.163:49648] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 144 Table 'wittercapture/Abortion_and_Feminism_June_12th_2019_1027am_tweets' is marked as crashed and last (automatic?) repair failed in /var/www/dmi-tcat/analysis/common/functions.php:989\nStack trace:\n#0 /var/www/dmi-tcat/analysis/common/functions.php(989): PDOStatement->execute()\n#1 /var/www/dmi-tcat/analysis/common/functions.php(20): get_all_datasets()\n#2 /var/www/dmi-tcat/analysis/index.php(5): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 989

**Comment by dentoir** [comment]
The log shows your database tables have crashed and need to be repaired from the command-line. The basic procedure is thus, as root:

- shutdown mysql with `systemctl stop mysql`
- `cd /var/lib/mysql/twittercapture`
- `myisamchk Abortion_and_Feminism_June_12th_2019_1027am_tweets`
- run the myisamchk command for all tables the log mentions having been crashed
- if the myisamchk command does *not* tell you the repair failed, you should be okay and restart mysql with `systemctl start mysql`
- if the myisamchk does tell you the repair failed, you can try `myisamchk --safe-recover Abortion_and_Feminism_June_12th_2019_1027am_tweets`

Repairs could take quite a while depending on the size of the dataset, but generally do not result in data loss.

**Comment by yperry50** [comment]
Hi Emile,

Thanks for your reply. As we speak, I run repair on all the tables and now I'm able to access the tables and the GUI via https. Thanks to you and the team for your help.
