### ISSUE TITLE
Potential bug while exporting GAP data

### ISSUE THREAD

**Issue by fredrikjonasson** [digitalmethodsinitiative/dmi-tcat#369]
Hi, 

I have encountered following error(attached screenshot) when trying to export gap data. I have tried with a fresh install of the program. The bin i am trying to export is a 1%. 

I have tried searching amongst closed issues without finding anything. 

Does anyone recognize this?

Best regards,

Fredrik
![Screenshot from 2019-07-06 19-54-55](https://user-images.githubusercontent.com/17785337/60759613-5a8f7d80-a028-11e9-97fa-519cb90a0032.png)

**Comment by ErikBorra** [comment]
Closing this issue as it has gone stale. Feel free to reopen.
