### ISSUE TITLE
No Access to http://Ip/capture

### ISSUE THREAD

**Issue by yperry50** [digitalmethodsinitiative/dmi-tcat#371]
Dear Team,

AWS Increased on our Ubuntu's  hard drive size and as a result also changed the IP address.
I updated the new IP address in the following files:

BASE_URL in /var/www/dmi-tcat/config.php and ServerName in /etc/apache2/sites-available/tcat.conf

After restart I can see the Analysis page but not the Capture page with the new IP.
Also tweets stop the collection process.

Below is the Error log files. Please let me know if you need additional information. 
As Always, Many Thanks!

                                                           /var/log/apache2/error.log                                                                                                        

[Sun Jul 21 00:06:00.553356 2019] [mpm_prefork:notice] [pid 1314] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sun Jul 21 00:06:00.553376 2019] [core:notice] [pid 1314] AH00094: Command line: '/usr/sbin/apache2'
[Sun Jul 21 02:04:19.782458 2019] [auth_basic:error] [pid 14177] [client 98.109.128.163:49715] AH01618: user root not found: /analysis/index.php
[Sun Jul 21 02:05:33.866292 2019] [php7:error] [pid 14178] [client 98.109.128.163:49738] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:05:45.719321 2019] [php7:error] [pid 14179] [client 98.109.128.163:49742] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:05:57.993672 2019] [php7:error] [pid 14180] [client 98.109.128.163:49746] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:06:18.129045 2019] [php7:error] [pid 14180] [client 98.109.128.163:49759] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:08:27.686279 2019] [php7:error] [pid 28442] [client 98.109.128.163:49786] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:08:28.441848 2019] [php7:error] [pid 14177] [client 98.109.128.163:49789] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:16:45.192375 2019] [mpm_prefork:notice] [pid 1314] AH00173: SIGHUP received.  Attempting to restart
[Sun Jul 21 02:16:45.224468 2019] [mpm_prefork:notice] [pid 1314] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sun Jul 21 02:16:45.224492 2019] [core:notice] [pid 1314] AH00094: Command line: '/usr/sbin/apache2'
[Sun Jul 21 02:17:01.945120 2019] [php7:error] [pid 29819] [client 98.109.128.163:49912] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:17:12.604297 2019] [php7:error] [pid 29821] [client 98.109.128.163:49915] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:17:31.059522 2019] [php7:error] [pid 29818] [client 98.109.128.163:49917] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:18:28.950057 2019] [php7:error] [pid 29822] [client 98.109.128.163:49930] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:20:48.118839 2019] [php7:error] [pid 29819] [client 98.109.128.163:49951] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/dmi-tcat/common/functions.php:6\nStack trace:\n#0 /var/www/dmi-tcat/common/functions.php(6): PDO->__construct('mysql:host=loca...', 'tcatdbuser', 'DZjaXr5jHgJ69CG...', Array)\n#1 /var/www/dmi-tcat/analysis/common/functions.php(9): pdo_connect()\n#2 /var/www/dmi-tcat/analysis/ajax.serverload.php(3): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/common/functions.php on line 6, referer: http://52.15.59.22/analysis/index.php?dataset=AF061920190929PM&query=&url_query=&media_url_query=&geo_query=&exclude=&from_user_name=&from_user_lang=&lang=&exclude_from_user_name=&from_user_description=&from_source=&startdate=2019-06-19&enddate=2019-06-22&whattodo=&graph_resolution=day&outputformat=csv
[Sun Jul 21 02:20:48.529942 2019] [php7:error] [pid 29821] [client 98.109.128.163:49965] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/dmi-tcat/common/functions.php:6\nStack trace:\n#0 /var/www/dmi-tcat/common/functions.php(6): PDO->__construct('mysql:host=loca...', 'tcatdbuser', 'DZjaXr5jHgJ69CG...', Array)\n#1 /var/www/dmi-tcat/analysis/common/functions.php(9): pdo_connect()\n#2 /var/www/dmi-tcat/analysis/ajax.serverload.php(3): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/common/functions.php on line 6, referer: http://52.15.59.22/analysis/index.php?dataset=AF061920190929PM&query=&url_query=&media_url_query=&geo_query=&exclude=&from_user_name=&from_user_lang=&lang=&exclude_from_user_name=&from_user_description=&from_source=&startdate=2019-06-19&enddate=2019-07-20&whattodo=&graph_resolution=day&outputformat=csv
[Sun Jul 21 02:20:49.197383 2019] [mpm_prefork:notice] [pid 1314] AH00169: caught SIGTERM, shutting down
[Sun Jul 21 02:21:29.092934 2019] [mpm_prefork:notice] [pid 1311] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sun Jul 21 02:21:29.093253 2019] [core:notice] [pid 1311] AH00094: Command line: '/usr/sbin/apache2'
[Sun Jul 21 02:21:29.423546 2019] [php7:error] [pid 1351] [client 98.109.128.163:49991] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/dmi-tcat/common/functions.php:6\nStack trace:\n#0 /var/www/dmi-tcat/common/functions.php(6): PDO->__construct('mysql:host=loca...', 'tcatdbuser', 'DZjaXr5jHgJ69CG...', Array)\n#1 /var/www/dmi-tcat/analysis/common/functions.php(9): pdo_connect()\n#2 /var/www/dmi-tcat/analysis/ajax.serverload.php(3): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/common/functions.php on line 6, referer: http://52.15.59.22/analysis/index.php?dataset=AF061920190929PM&query=&url_query=&media_url_query=&geo_query=&exclude=&from_user_name=&from_user_lang=&lang=&exclude_from_user_name=&from_user_description=&from_source=&startdate=2019-06-19&enddate=2019-07-20&whattodo=&graph_resolution=day&outputformat=csv
[Sun Jul 21 02:29:17.546115 2019] [php7:error] [pid 1353] [client 98.109.128.163:50091] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:30:02.402777 2019] [php7:error] [pid 1831] [client 98.109.128.163:50104] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:30:08.507979 2019] [php7:error] [pid 1355] [client 98.109.128.163:50109] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:32:54.718072 2019] [php7:error] [pid 2940] [client 98.109.128.163:50171] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387, referer: http://52.15.59.22/analysis/index.php?dataset=AF061920190929PM&query=&url_query=&media_url_query=&geo_query=&exclude=&from_user_name=&from_user_lang=&lang=&exclude_from_user_name=&from_user_description=&from_source=&startdate=2019-06-19&enddate=2019-06-22&whattodo=&graph_resolution=day&outputformat=csv
[Sun Jul 21 02:33:10.708606 2019] [php7:error] [pid 1352] [client 98.109.128.163:50180] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:33:12.461724 2019] [php7:error] [pid 1354] [client 98.109.128.163:50181] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:33:12.548371 2019] [php7:error] [pid 1351] [client 98.109.128.163:50182] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:33:44.242024 2019] [php7:error] [pid 1831] [client 98.109.128.163:50183] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387, referer: http://52.15.59.22/analysis/index.php?dataset=AF061920190929PM&query=&url_query=&media_url_query=&geo_query=&exclude=&from_user_name=&from_user_lang=&lang=&exclude_from_user_name=&from_user_description=&from_source=&startdate=2019-06-19&enddate=2019-06-22&whattodo=&graph_resolution=day&outputformat=csv
[Sun Jul 21 02:44:28.324364 2019] [php7:error] [pid 1355] [client 98.109.128.163:50361] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:44:42.128476 2019] [php7:error] [pid 1351] [client 98.109.128.163:50370] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:45:04.665330 2019] [php7:error] [pid 2940] [client 98.109.128.163:50377] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:45:10.406739 2019] [php7:error] [pid 1355] [client 98.109.128.163:50379] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:49:24.640253 2019] [php7:error] [pid 2940] [client 98.109.128.163:50443] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:49:30.922287 2019] [php7:error] [pid 1355] [client 98.109.128.163:50453] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:49:37.155115 2019] [php7:error] [pid 1353] [client 98.109.128.163:50458] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:49:42.079634 2019] [php7:error] [pid 1354] [client 98.109.128.163:50457] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:49:56.611022 2019] [php7:error] [pid 1351] [client 98.109.128.163:50460] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:56:15.146015 2019] [php7:error] [pid 1354] [client 98.109.128.163:50553] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387
[Sun Jul 21 02:56:22.717715 2019] [php7:error] [pid 1831] [client 98.109.128.163:50555] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1017 Can't find file: 'tcat_controller_tasklist' (errno: 2 - No such file or directory) in /var/www/dmi-tcat/capture/common/functions.php:387\nStack trace:\n#0 /var/www/dmi-tcat/capture/common/functions.php(387): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(14): create_admin()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/common/functions.php on line 387

**Comment by xmacex** [comment]
The error is coming from https://github.com/digitalmethodsinitiative/dmi-tcat/blob/1dfc4bf59a36f1e87222dd54c45eb214c57cc802/capture/common/functions.php#L387 (presuming your TCAT is updated).

There is something funny going on about your database, and you might be missing a table called *tcat_controller_tasklist* in the database or it might be inconsistent. Can you check if it exists?

```sh
myisamchk --extend-check /var/lib/mysql/twittercapture/tcat_controller_tasklist
```

Presuming your database files are at */var/lib/mysql/twittercapture*.
