### ISSUE TITLE
merge.php exits with ERROR 1100 [HY000] with exported database as argument

### ISSUE THREAD

**Issue by anthbrtn** [digitalmethodsinitiative/dmi-tcat#372]
Upon attempting to make a redundant instance, I receive the following error when running the merge.php script on the sql.gz file exported from the first instance using the export.php script:

```
foo@bar:/foo/bar/helpers# php merge.php twittercapture_temporary "barfoo-track-all-2019-07-27_10:45.sql.gz"
Query bin already exists: barfoo
Now merging...
ERROR 1100 (HY000) at line 2813: Table 'tcat_query_bins' was not locked with LOCK TABLES
There was a problem with importing data into the temporary database.
```

Naturally, I set up a query bin manually on this second instance with the same phrases before I used the export script from the first instance, so that I did not have any gaps in the data collection. The query bins from instance 1 and instance 2 also share the same name.

Troubleshooting steps taken:

- Empty database named twittercapture_temporary was created; is empty; credentialed properly; required privileges are granted to the default tcat database user (in essence, all instructions at the top of merge.php have been followed).
- mysql_error.log shows no errors
- second instance was set up using the tcat-install-linux.sh script

Am wondering if this is a case of needing to close access to the database/stop the controller.php cron and anything else from accessing the database on the first instance before running the export.php script, although that's just based on my primary understanding of how lockfiles work in mysql. If this is the case, I'd be happy to commit some more verbose instructions to export.php, as it is unclear.

**Comment by ErikBorra** [comment]
Closing this issue as it has gone stale. Feel free to reopen.

**Comment by anthbrtn** [comment]
Haven't had this problem since a few updates ago, so probably good to stay closed.
