### ISSUE TITLE
Exports marked as 'downloads' work but those marked as 'launch' do not? 

### ISSUE THREAD

**Issue by warren-pearce** [digitalmethodsinitiative/dmi-tcat#379]
Hi - I have just had TCAT installed at my institution, and getting a strange error: any tweet exports where the link is marked as 'download' work fine (e.g. random set of tweets, export all tweets), but any exports marked as 'launch' (i.e. most) do not. I get a screen that looks correct with a URL link to a file, but if I click on the link I get a 404 message, and if I right click to 'save the link as' the file I download has no content.

I am going to raise it with the Information Services people here, but thought I would ask here if it is a known issue. Thanks!

**Comment by xmacex** [comment]
Hmm a web server configuration issue? Can the web server write to directory `analysis/cache`?

Do the web server error logs (e.g. `/var/log/apache2/error.log` for Apache2 on Ubuntu or Debian) say something? You can list HTTP 404 errors e.g. with `awk '$9 == 404 {print}' /var/log/apache2/access.log` to see which URL caused them, and then check if they are available to the server to send over.

**Comment by niczem** [comment]
hi warren, is there any update on the issue?
