### ISSUE TITLE
"URL Frequency" missing in analysis module 

### ISSUE THREAD

**Issue by Pingus098** [digitalmethodsinitiative/dmi-tcat#380]
Hi! 

I would like to examine URLs that were posted in the tweets (tweeted links). I see in the tutorials that there should be an "URL Frequency" option in the analysis module that exports  URLs found in tweets. However, I cannot find it in my DMI-TCAT. Should I configure something else for this functionality? I used automated installation on Ubuntu AWS. 

Thanks! 
<img width="900" alt="Untitled" src="https://user-images.githubusercontent.com/55962981/65841402-30491580-e322-11e9-8197-7aa234c57e6d.png">

**Comment by Pingus098** [comment]
Seems like the "URL Frequency" is only available if you select only a portion of data using parameters under Data selection; but not on a whole dataset.

**Comment by ErikBorra** [comment]
The URL frequency is only available when the URL expander has finished its work for that data set. So indeed, if you select a period for which URL expansion has completed, it will show the URL export.
