### ISSUE TITLE
Inconsistent URL frequency results: includes/excludes retweets

### ISSUE THREAD

**Issue by laurieresearch** [digitalmethodsinitiative/dmi-tcat#381]
Hi

I'm working with several datasets in TCAT analysing URL frequencies. There seem to be inconsistencies between the different datasets in terms of how URL frequency is calculated. 

In one dataset URL frequency appears to be calculated as: 'no. of unique tweets featuring URL'. In another, URL frequency appears to include 'no. of times URL is retweeted'. In some cases, however, the URL frequency module results don't tally with either of these measures.

I'm not clear if these inconsistencies are due to software updates that occured between periods of data collection/analysis or whether they are the result of a bug?

Happy to send over examples if required.

Laurie

**Comment by niczem** [comment]
Hi Laurie and sorry for the late reply!

Could you upload the examples here so we can see what is going wrong?

**Comment by ErikBorra** [comment]
Closing this issue as no extra input has been provided. Feel free to reopen.
