### ISSUE TITLE
Due to a MySQL 'Normal shutdown,' all data were deleted and streaming stopped

### ISSUE THREAD

**Issue by thesickish** [digitalmethodsinitiative/dmi-tcat#382]
Hi,

I had three instances of DMI-TCAT running, which varied in both how long they had been running and how much data they were collecting. Yesterday morning, all three were deleted at about the same time, with the data unrecoverable and streaming stopped.

The server administrators to looked into it, and reported that this was due to a MySQL 'Normal shutdown' (according to /var/log/mysql/error.log). This was followed by repeated commands to 'static_destroy _open_tables,' which I believe means that all of the data were deleted. The server memory is back to full, with the lost data unrecoverable. 

Given that all three instances shutdown at the same time, and varied quite drastically in how much memory they were using, I do not think this was an issue with running out of memory. Has anyone else run into this issue? Is there a way to disable MySQL shutdowns? I am including more of the error file below, in case it is helpful.

Thanks,
Yotam

------

2019-11-20  6:59:37 139846491522816 [Note] /usr/sbin/mysqld: Normal shutdown
2019-11-20  6:59:37 139846491522816 [Note] Event Scheduler: Purging the queue. 0 events
2019-11-20  6:59:40 139845540239104 [Note] InnoDB: FTS optimize thread exiting.
2019-11-20  6:59:40 139846491522816 [Note] InnoDB: Starting shutdown...
2019-11-20  6:59:40 139846491522816 [Note] InnoDB: Waiting for page_cleaner to finish flushing of buffer pool
2019-11-20  6:59:41 139846491522816 [Note] InnoDB: Shutdown completed; log sequence number 1616757
18878 /build/mariadb-10.1-df7_m4/mariadb-10.1-10.1.41/storage/tokudb/ha_tokudb.cc:161 static_destroy _open_tables ./twittercapture/first_bin_media 0x7f304dfef008
18878 /build/mariadb-10.1-df7_m4/mariadb-10.1-10.1.41/storage/tokudb/ha_tokudb.cc:161 static_destroy _open_tables ./twittercapture/tcat_query_bins_phrases 0x7f30476bb008
18878 /build/mariadb-10.1-df7_m4/mariadb-10.1-10.1.41/storage/tokudb/ha_tokudb.cc:161 static_destroy _open_tables ./twittercapture/tcat_query_bins_users 0x7f304d90e008
18878 /build/mariadb-10.1-df7_m4/mariadb-10.1-10.1.41/storage/tokudb/ha_tokudb.cc:161 static_destroy _open_tables ./twittercapture/tcat_error_ratelimit 0x7f3047715008

**Comment by niczem** [comment]
We didn't notice this issue with any of our instances and it seems like no one else reported. Please reopen if more info.

**Comment by AnnieBarrett** [comment]
We have had the same issue.

**Comment by ErikBorra** [comment]
Hi @AnnieBarrett 

I am so sorry to hear that this happened to you too. Do you have any additional information that might help us debug the problem? E.g. The controller.log and error.log at the time of shut-down and restart; the manner in which you installed tcat, maybe also the version of ubuntu, mysql and tokudb.

Googling around for `static_estroy _open_tables` returns very little results. It seems related to tokudb, but apart from that we are really in the dark.

Best,

Erik

**Comment by AnnieBarrett** [comment]
Hi Erik,

Apologies we were receiving the same mysql logs with regards to

“ MySQL 'Normal shutdown' (according to /var/log/mysql/error.log). This was followed by repeated commands to 'static_destroy _open_tables,'”

however we are not using tokudb. All of the mysql logs have now been overwriten so cannot send you the full text. We are using Ubuntu 18.04.4 LTS and installed via the installation script.

Annie

HASS IT

Remote Working Guidance: https://www.ncl.ac.uk/itservice/remoteworking/

Digital Learning and Eductional Continuity: https://services.ncl.ac.uk/digitallearning/

Get started with Microsoft Teams: https://newcastle.sharepoint.com/sites/O365/SitePages/Get-started-with-Microsoft-Teams.aspx

**Comment by niczem** [comment]
Hi Annie,

also sorry to hear that! 

_"however we are not using tokudb. All of the mysql logs have now been overwriten so cannot send you the full text. We are using Ubuntu 18.04.4 LTS and installed via the installation script."_

This indicates that this had another cause as the error log of @thesickish indicates a fault in in tokudb:

(..)
18878 /build/mariadb-10.1-df7_m4/mariadb-10.1-10.1.41/storage/tokudb/ha_tokudb.cc:161 static_destroy _open_tables ./twittercapture/first_bin_media 0x7f304dfef008
18878 /build/mariadb-10.1-df7_m4/mariadb-10.1-10.1.41/storage/tokudb/ha_tokudb.cc:161 static_destroy _open_tables ./twittercapture/tcat_query_bins_phrases 0x7f30476bb008
18878 /build/mariadb-10.1-df7_m4/mariadb-10.1-10.1.41/storage/tokudb/ha_tokudb.cc:161 static_destroy _open_tables ./twittercapture/tcat_query_bins_users 0x7f304d90e008
18878 /build/mariadb-10.1-df7_m4/mariadb-10.1-10.1.41/storage/tokudb/ha_tokudb.cc:161 static_destroy _open_tables ./twittercapture/tcat_error_ratelimit 0x7f3047715008

```

please reopen if it occurs again or more information for reproducing the bug can be given
