### ISSUE TITLE
Problem line 1029

### ISSUE THREAD

**Issue by aymannkhatib** [digitalmethodsinitiative/dmi-tcat#392]
Hello,

I hope i am in the right place to talk about it.

I wanted to install dmi-tcat so i ran "sudo ./tcat-install-linux.sh"

It all went good for a while until i got " Disabling Linux kernel transparant HugePage support
./tcat-install-linux.sh: line 1029: /sys/kernel/mm/transparent_hugepage/enabled: No such file or directory
tcat-install-linux.sh: command failed: install aborted"

Screenshot:
![image](https://user-images.githubusercontent.com/56873157/79218459-c07b2200-7e50-11ea-9c85-aaedaee774af.png)

Would anyone have an idea of why it is not working?

Thak you  very much for your answer

**Comment by niczem** [comment]
Hi and thanks for submitting the issue - i created a possible fix in this branch:
https://github.com/digitalmethodsinitiative/dmi-tcat/pull/393

can you check if it works?

**Comment by johannessweater** [comment]
Hi -- I just now tried installing TCAT on a Debian instance and ran into the same problem.

**Comment by niczem** [comment]
which debian version are you using? 9 or 10?

**Comment by johannessweater** [comment]
I'm using Debian 9. I just tried again with a new instance and got the same error again (re hugepages package).

**Comment by niczem** [comment]
Okey I tried to disable the hugepage support as documented [here](https://oracle-base.com/articles/linux/configuring-huge-pages-for-oracle-on-linux-64#disabling-transparent-hugepages) and tested it on a debian 9 - it should work now :)

**Comment by johannessweater** [comment]
Success! :-D
