### ISSUE TITLE
All exported data are blank

### ISSUE THREAD

**Issue by helixg** [digitalmethodsinitiative/dmi-tcat#394]
**Describe the bug**
I have installed TCAT on the GCP instance. And when I want to export all my data stored in several bins by using `http://localhost/api/querybin.php`  and the export button in `http://localhost/analysis/`  However, the data exported are all blank with the size of 554 bytes. 

**To Reproduce**
1. Go to 'http://localhost/api/querybin.php/binname'
2. Click on 'tweets'
3. Click on 'export selected tweets'
4. See error: the exported data are blank

**Expected behavior**
When the data size is small, I can export data neatly, but when the data size becomes large, the exported file will only be 554 bytes with no actual data.

**Screenshots**
![issue1.png](https://i.loli.net/2020/04/24/IkTaS576tqDZzy4.png)
![issue3.png](https://i.loli.net/2020/04/24/TXLmyG7U6KlPCND.png)
![issue2.png](https://i.loli.net/2020/04/24/2GceXP3jACfJxRq.png)

**Environment:**
 - Uubuntu 18.04 php 7.0
 - Chrome

**Additional context**
I guess the reason for the exporting failure may because of the dataset is so big, but how can I export all these large data?

**Comment by ErikBorra** [comment]
You might run out of PHP application memory. What does error.log say?

**Comment by helixg** [comment]
> You might run out of PHP application memory. What does error.log say?

Where can I find the error.log?

**Comment by helixg** [comment]
> You might run out of PHP application memory. What does error.log say?

> [Mon May 04 06:25:08.901659 2020] [mpm_prefork:notice] [pid 1834] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Mon May 04 06:25:08.901701 2020] [core:notice] [pid 1834] AH00094: Command line: '/usr/sbin/apache2'
[Mon May 04 14:48:59.323509 2020] [auth_basic:error] [pid 7792] [client 197.232.1.182:1580] AH01618: user  not found: /manager/html
[Mon May 04 14:48:59.904210 2020] [auth_basic:error] [pid 7792] [client 197.232.1.182:1580] AH01617: user admin: authentication failure for "/manager/html": Password Mismatch
[Mon May 04 14:49:00.312940 2020] [auth_basic:error] [pid 7792] [client 197.232.1.182:1580] AH01617: user admin: authentication failure for "/manager/html": Password Mismatch
[Mon May 04 14:49:00.716595 2020] [auth_basic:error] [pid 7792] [client 197.232.1.182:1580] AH01617: user admin: authentication failure for "/manager/html": Password Mismatch
[Mon May 04 14:49:01.122013 2020] [auth_basic:error] [pid 7792] [client 197.232.1.182:1580] AH01618: user tomcat not found: /manager/html
[Mon May 04 14:49:01.528770 2020] [auth_basic:error] [pid 7792] [client 197.232.1.182:1580] AH01618: user tomcat not found: /manager/html
[Mon May 04 14:49:01.935565 2020] [auth_basic:error] [pid 7792] [client 197.232.1.182:1580] AH01618: user tomcat not found: /manager/html
[Mon May 04 15:29:07.646536 2020] [authz_core:error] [pid 3594] [client 45.125.46.19:21669] AH01630: client denied by server configuration: /var/www/dmi-tcat/.php
[Mon May 04 17:17:35.575690 2020] [php7:notice] [pid 7792] [client ::1:52872] PHP Notice:  Undefined index: PATH_INFO in /var/www/dmi-tcat/api/querybin.php on line 2416, referer: http://localhost/api/querybin.php/twic4/tweets
[Mon May 04 17:17:35.648664 2020] [php7:notice] [pid 7792] [client ::1:52872] PHP Notice:  Undefined index: startdate in /var/www/dmi-tcat/api/querybin.php on line 2589, referer: http://localhost/api/querybin.php/twic4/tweets
[Mon May 04 17:17:35.648689 2020] [php7:notice] [pid 7792] [client ::1:52872] PHP Notice:  Undefined index: enddate in /var/www/dmi-tcat/api/querybin.php on line 2590, referer: http://localhost/api/querybin.php/twic4/tweets
[Mon May 04 17:25:02.853173 2020] [php7:notice] [pid 19354] [client ::1:54198] PHP Notice:  Undefined index: startdate in /var/www/dmi-tcat/api/querybin.php on line 2589, referer: http://localhost/api/querybin.php
[Mon May 04 17:25:02.853254 2020] [php7:notice] [pid 19354] [client ::1:54198] PHP Notice:  Undefined index: enddate in /var/www/dmi-tcat/api/querybin.php on line 2590, referer: http://localhost/api/querybin.php
[Mon May 04 17:35:17.111810 2020] [php7:notice] [pid 29722] [client ::1:56482] PHP Notice:  Undefined index: startdate in /var/www/dmi-tcat/api/querybin.php on line 2589, referer: http://localhost/api/querybin.php/twic8
[Mon May 04 17:35:17.111880 2020] [php7:notice] [pid 29722] [client ::1:56482] PHP Notice:  Undefined index: enddate in /var/www/dmi-tcat/api/querybin.php on line 2590, referer: http://localhost/api/querybin.php/twic8
[Mon May 04 18:01:07.956331 2020] [mpm_prefork:notice] [pid 1526] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Mon May 04 18:01:07.986568 2020] [core:notice] [pid 1526] AH00094: Command line: '/usr/sbin/apache2'
[Mon May 04 18:17:55.430679 2020] [php7:error] [pid 1541] [client ::1:54478] PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 4096 bytes) in /var/www/dmi-tcat/analysis/mod.export_tweets.php on line 59, referer: http://localhost/api/querybin.php/twic8/tweets

The text above is the most recent 

> error.log

 file

**Comment by helixg** [comment]
BTW, when I use the terminal export method `php export.php -a`, the out put is this
`Could not open input file: export.php`
how can I fix this?

**Comment by ErikBorra** [comment]
Hi @helixg,

There seem to be a couple of issues. First of, you are running out of PHP memory: `Allowed memory size of 4294967296 bytes exhausted (tried to allocate 4096 bytes) in /var/www/dmi-tcat/analysis/mod.export_tweets.php`. Try increasing the php memory limit, if your system allows it. Currently you have 4GB, try setting it to e.g. 8GB by editing config.ph and adding the following to the top (or replacing a similar line): `ini_set('MEMORY_LIMIT','8GB');` Let us know whether that helps.
