### ISSUE TITLE
Ubuntu version

### ISSUE THREAD

**Issue by claudiala** [digitalmethodsinitiative/dmi-tcat#395]
Hi!
I tried to install DMI-TCAT, but I have Ubuntu 16.04 and not 18.04, do you have some solution? Because  it seems in the command line that it is an unsupported version the one I’m using .
“
In alternative I have also a Windows partition.

Thanks and I’m wAiting for your feedback.
Claudia

**Comment by niczem** [comment]
Hi Claudia, sadly not as listed in the requirements:

> Requirements
> Twitter API credentials (these can be obtained from https://apps.twitter.com);
> One of the following Linux distributions:
> Ubuntu 18.04
> Debian 9.*
>
