### ISSUE TITLE
Unable to access http://[hostname]]/capture/index.php

### ISSUE THREAD

**Issue by AnnieBarrett** [digitalmethodsinitiative/dmi-tcat#396]
We were running a list of queries using tcat a month ago and lost access to the admin page and many of the queries. We did not manage to fix this and installed dmi-tcat on a new server (installed via the provided installation script, on Ubuntu 18.04.4 LTS server) to try and run the queries again. We have once again lost access to the admin page (HTTP 500 error, same behaviour on Chrome, Edge and Firefox). The application is still collecting tweets from 3 of the queries which can be seen in the analysis page (unsure if there is a mechanism for stopping these without access to the admin page? They were all started at 16.01 on 18/03/20). The fourth query (YtBring67MBack) is not showing (this is the same query we were unable to access in the analysis page when the previous instance broke – assuming this is a coincidence but mentioning it in case). Checking the database there are tables for YtBring67MBack_places and YtBring67MBack_withheld but no other tables with the prefix of YtBring67MBack. 

The apache error logs from April 25th and 26th show PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'twittercapture.YtBring67MBack_tweets' doesn't exist in… 

I have checked the database and can confirm this table doesn’t exist. There is not a dmi-tcat log for a corresponding date. 

Would appreciate any guidance or advice. 

Many  thanks in advance.

**Comment by niczem** [comment]
Hi Annie, 

it looks like your table has crashed or is corrupted. You can try to repair it:
https://dev.mysql.com/doc/refman/8.0/en/repair-table.html

**Comment by AnnieBarrett** [comment]
Hi Niczem,

Thank you for replying to my post.

The problem is that the table doesn’t exist anymore, so I don’t think I will be able to repair it? Please see below for list of tables – you can see that YtBring67MBack only has 2 tables whereas all of the working queries have 7.

[cid:image001.png@01D62450.1CBEAC90]

It looks like the same issue as logged here: https://github.com/digitalmethodsinitiative/dmi-tcat/issues/382. It has happened twice to us now (tables in a certain query being deleted).

Any advice for how to proceed much appreciated.

Thanks,
Annie

HASS IT

Remote Working Guidance: https://www.ncl.ac.uk/itservice/remoteworking/

Digital Learning and Eductional Continuity: https://services.ncl.ac.uk/digitallearning/

Get started with Microsoft Teams: https://newcastle.sharepoint.com/sites/O365/SitePages/Get-started-with-Microsoft-Teams.aspx

**Comment by mrkamyar7** [comment]
I am experiencing the same issue, can you please help me out? The Admin panel is inaccessible for me!

**Comment by ErikBorra** [comment]
Hi @mrkamyar7 ,

Could you provide some more detail? Was TCAT running before? What does the controller.log and the error.log say? What does 'inaccessible' mean? Please open a new issue via https://github.com/digitalmethodsinitiative/dmi-tcat/issues/new/choose and follow the steps. 

Best,

Erik
