### ISSUE TITLE
admin page links to old documentation

### ISSUE THREAD

**Issue by ErikBorra** [digitalmethodsinitiative/dmi-tcat#399]
/capture/index.php links to https://developer.twitter.com/en/docs/streaming-apis/parameters#track while that should be https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters#track

**Comment by ErikBorra** [comment]
https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/FAQ should be updated as well

**Comment by niczem** [comment]
closed with #404
