### ISSUE TITLE
Google chart not displayed

### ISSUE THREAD

**Issue by jamestripp** [digitalmethodsinitiative/dmi-tcat#401]
**Describe the bug**
The Tweet freqency line plot and url piechart are not displayed when one loads /var/www/dmi-tcat/analysis/index.php. Investigation of the javascript console indicates this is a type error. The error seems to occur when creatign the google visualisation object.

**To Reproduce**
1. Navigate to servername/analysis/
2. Open the javascript console. Not the error message TypeError: google.visualization is undefined. See attached.

**Expected behavior**
Plots of the tweet frequeny and url frequency should be displayed.

**Screenshots**
<img width="871" alt="Screenshot 2020-06-15 at 10 48 13" src="https://user-images.githubusercontent.com/5781056/84644056-8c76b880-aef6-11ea-9300-8175cf7ff18b.png">

<img width="1187" alt="Screenshot 2020-06-15 at 10 55 44" src="https://user-images.githubusercontent.com/5781056/84644210-c5169200-aef6-11ea-81c9-8fcac3f36caf.png">

**Environment:**
- MacOS Catalina
- Safari and Firefox
 
**Additional context**

**Comment by tmantynen** [comment]
I had the same problem. (dmi-tcat master/a57ed66, Ubuntu 20.04, Apache 2.4.43, PHP 7.3.19, MySQL 8.0.20, Firefox 77.0.1).

I was able to fix this issue on my installation. Please see my pull request #403 

![Screenshot_20200623_114623](https://user-images.githubusercontent.com/12476658/85383002-2ae2c980-b548-11ea-864a-ede2e3bbd727.png)

**Comment by jamestripp** [comment]
Great. That fixed it. Thanks!
