### ISSUE TITLE
Using the "Export all tweets from selection" option but get empty document.

### ISSUE THREAD

**Issue by luyang1210** [digitalmethodsinitiative/dmi-tcat#407]
**Describe the bug**
So I am a user of DMI TCAT tool. I install it on a linux VM (Ubuntu 18.04). It seems that tweet capture works fine. But when I choose to export the data in csv and download to my local machine, I always get a csv file with the header but no data. Just want to know if that ever happened to you? Any solution can help? Thanks.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - OS (if bug relates server/backend/install): [e.g. ubuntu 16.04 php 7.0]
 - Browser (if bug relates to frontend):[e.g. chrome, safari]

**Additional context**

**Comment by niczem** [comment]
may be the same as to #394

**Comment by ErikBorra** [comment]
Generally this happens because the analysis/cache directory is not writeable, or if your system does not have any disk space left.
