### ISSUE TITLE
no graphs showing in analysis web interface, 

### ISSUE THREAD

**Issue by anderscollstrup** [digitalmethodsinitiative/dmi-tcat#409]
I have 4 tcat servers and all of the collect tweets, but none of them show graph.

![no-graph](https://user-images.githubusercontent.com/43263564/89878870-6f8ef680-dbc2-11ea-8856-3a9ff73bd766.png)

![no-graph2](https://user-images.githubusercontent.com/43263564/89879959-f2648100-dbc3-11ea-8cc7-92e750b98076.png)

I don't see any errors in apache or dmi-tcat logs
I use debian 8.

How do I get my graph back?

**Comment by bredfiel1** [comment]
Having the same issue.  Did you happen to find a resolution?

**Comment by anderscollstrup** [comment]
No, unfortunately not. The issue still persist.

**Comment by carlosguadian** [comment]
Hi, I have the same issue, and I think we need an update. This error is fixed here https://github.com/digitalmethodsinitiative/dmi-tcat/issues/401

**Comment by ErikBorra** [comment]
@niczem could you look at this and update the code if necessary?

**Comment by anderscollstrup** [comment]
Sorry, this issue was solved at our end with latest update. I forgot to close the issue. Sorry
