### ISSUE TITLE
Query bins aren't capturing tweets

### ISSUE THREAD

**Issue by ntpugum** [digitalmethodsinitiative/dmi-tcat#410]
Hi, 
I followed Automated installation and created my query bin.
However,they have no collected any tweets.
I checked some older issues(e.g.#103 #154), but I failed it.

I will be grateful for any help you can provide!

**Comment by niczem** [comment]
Hi and thanks for the inquiry.  Do you have any additional info (e.g. the php or apache error log?)

**Comment by enomis21** [comment]
Any news about that issue? Me too I have a word tracking mode installation that's not running anymore. Has worked untill the middle of June and then stopped. I tried recently to install another instance of the software, always word track mode, with no success. A third instance I'm running with follow user mode works correctly.
thanks for the attention

**Comment by ErikBorra** [comment]
Hi @enomis21,

do you have any additional information, such as server logs that might help us debug the issue?

Best,

Erik

**Comment by enomis21** [comment]
> Hi @enomis21,
> 
> do you have any additional information, such as server logs that might help us debug the issue?
> 
> Best,
> 
> Erik

Hello @ErikBorra, 
I solved the issue upgrading the software, I probably had an error caused by stopping the previous upgrade when in background or something similar. Thank you very much for your interest in helping me and really thank you for your work about TCAT.
have a good day.

**Comment by ErikBorra** [comment]
Good to hear it was solved. Glad to be of help.

Best regards,

Erik
