### ISSUE TITLE
Raspberry Pi: Can't install dmi-tcat

### ISSUE THREAD

**Issue by glocalglocal** [digitalmethodsinitiative/dmi-tcat#411]
I was hoping to install dmi-tcat on a Raspberry Pi 4B, 4GB to capture a fairly small number of tweets per day (under 3000) over a longer period of time, but when I run this:

`curl https://raw.githubusercontent.com/digitalmethodsinitiative/dmi-tcat/master/helpers/tcat-install-linux.sh | sudo bash`

I get: 

> bash: error: unsupported distribution: Raspbian

I see [here ](https://github.com/digitalmethodsinitiative/dmi-tcat/issues?q=is%3Aissue+raspberry) and elsewhere that others (eg @thevarunfactor, @fubespu, @joep1) have successfully used earlier models of RPis before to do a similar thing. Rasbian being based on Debian, I thought at least installation would go through. Can someone please help. 

My plan is to keep the headless RPi with its very low power consumption capturing tweets quietly in the background and saving them on a USB flash drive. Then, I'll get the database off to a 'proper' PC for processing. Ideally, I would get a copy of the database without having to interrupt dmi-tcat collecting if possible. I don't see why this won't work, particularly as 4B is considerably more powerful than earlier RPi models. Are there any problems I should anticipate? Obsviously, I'd rather not discover I made a stupid mistake several months down the road. Eg I opted for external storage because microSDs wear out quickly and can fail unexpectedly. I am also thinking about UPS in case of power failure.

**Comment by ErikBorra** [comment]
Hi @glocalglocal,

The install script only works for Debian distributions. In order to install DMI-TCAT on Raspbian, you will have to follow the manual install instructions.

Best,

Erik

**Comment by glocalglocal** [comment]
Thanks, @ErikBorra. I am nowhere near confident enough I understand more than half of the instructions there so I won't even give it a try. I may try the docker version, but I am not optimistic about that either and I will probably have to forget about running dmi-tcat on Raspbian after all.  

Thanks, 
Michael

**Comment by ErikBorra** [comment]
Hi Michael,

The manual installation instructions should be pretty detailed. Closing this issue for now. Don't hesitate to ask for clarifications in a new issue.

Best,

Erik

**Comment by glocalglocal** [comment]
Fair enough. They may be pretty detailed but they are also completely meaningless to the uninitiated, including this seasoned Windows and novice Linux user. The same goes for the Docker instructions. Having said that, I do appreciate the effort of the people behind this project.
