### ISSUE TITLE
Changed IP GCP 

### ISSUE THREAD

**Issue by orangebacked** [digitalmethodsinitiative/dmi-tcat#412]
**Describe the bug**
Deal digital methods initiative, I have been trying to configure a machine in GCP with little success. GCP assigns ephemeral IP address to their VM's - I wasn't aware of that when I configured the machine. I looked at your closed issues and found a similar problem ( #387 ); however, I get a different error log. 
 
`PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'twittercapture.trumpbiden2_tweets' doesn't exist in /var/www/dmi-tcat/capture/query_manager.php:788\nStack trace:\n#0 /var/www/dmi-tcat/capture/query_manager.php(788): PDOStatement->execute()\n#1 /var/www/dmi-tcat/capture/index.php(19): getBins()\n#2 {main}\n  thrown in /var/www/dmi-tcat/capture/query_manager.php on line 788`

**Environment:**

GCP VM 

GCP Image: 
debian-9-stretch-v20200805

Machine type
custom (4 vCPUs, 12.75 GB memory)

Thank you!!

**Comment by ErikBorra** [comment]
Hi @orangebacked,

It seems something went wrong when trying to create a new query bin. A table seems to be missing. Could you try deleting the old bin via the admin interface and creating a new bin to see if the problem persists?

Thanks,

Erik

**Comment by ErikBorra** [comment]
Closing as no further input was received. Feel free to reopen.
