### ISSUE TITLE
How to test dmi-tcat sending emails ?

### ISSUE THREAD

**Issue by laspic** [digitalmethodsinitiative/dmi-tcat#421]
I had recently an unpleasant surprise regarding a problem in a capture process of tweets, a case where dmi-tcat was supposed to send me an email.
The problem was certainly entirely my fault: I didn't check that the sendmail module was working properly. I think I have now solved that but I would like to be absolutely sure. 
So, how can simply ask dmi-tcat to send me a test e-mail ?

**Comment by ErikBorra** [comment]
Send an email via PHP. If that works, dmi-tcat's mail will work as well.

**Comment by laspic** [comment]
Thank you, it's done. So let's hope it works!
