### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by luyang1210** [digitalmethodsinitiative/dmi-tcat#437]
Hi, 

I followed the "automatic installation" to install on Debian 9. It was find but I could not access via browser. So I decided to reinstall by removing directory "dmi-tcat". However, the "sudo ./tcat-install..." does not work anymore. I got "tcat-install-linux.sh: cannot install: mariadb-server already installed"

This seems that I have to manually remove everything it previously installed. Is there an uninstall.sh for us to retry it? Many thanks.

**Comment by luyang1210** [comment]
Hello?

**Comment by dale-wahl** [comment]
Hello luyang, unfortunately at this time we do not have any uninstall script. The docker installation allows for easy clean up as you can remove the image, container, and volume which completely removes TCAT, the database, and all from your system. (Currently the docker_dev branch is stable.) But that will not help in your case.

Generally, we use TCAT on it's own server or VM. I will check about any plans to add this to our dev plans.
