### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [digitalmethodsinitiative/dmi-tcat#441]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by ErikBorra** [comment]
Thanks @JamieSlome,

Please write an email to bugs[didlidoo]digitalmethods.net We will also make sure to add a SECURITY.md file. Thanks for the suggestion. Looking forward to your bug report.

Best,

Erik

**Comment by stijn-uva** [comment]
A SECURITY.md file was added to the repository in 11625b8f277ccf085161b2b3a6db7efcb5e03cb9.
