### ISSUE TITLE
/capture/index.php doesnt have a response.

### ISSUE THREAD

**Issue by gustavbang** [digitalmethodsinitiative/dmi-tcat#442]
**Describe the bug**
Cannot access localhost:capture/index.php

**To Reproduce**
1. Download DMI using Docker on Windows 10.
2. Follow the installation guide
3. run on localhost
4. logging in with admin user
5. localhost/analysis works, localhost/capture/index.php doesn't.
6. HTTP error 500 (missing specific error handling for this issue it seems).

**Expected behavior**
Being able to create query bins.

**Screenshot**
![image](https://user-images.githubusercontent.com/25503269/138597155-a3fb2aaa-bf04-4181-b62e-adeba0037969.png)

**Environment:**
 - OS: Windows 10
 - Browser: chrome, edge
 - Version: not sure

**Additional context**
I seem to be able to get a response when I use my non-admin user, and redirect directly to capture/index.php as seen here:
![image](https://user-images.githubusercontent.com/25503269/138597042-f02b5cad-3a08-4708-b6bb-1dbd9b93b003.png)
But as I log in with my admin user, I still get the above error.

**Comment by stijn-uva** [comment]
I got the same error on Debian 10 just now. Curiously, I'm pretty sure when I built the container earlier on the same machine it worked, so I'm not sure what happened.

Anyway, since TokuDB has been deprecated since 2015, it might be a sensible choice to simply disable it (at least by default) for new installs.

**Comment by dale-wahl** [comment]
Setup now [does not use TokuDB by default](https://github.com/digitalmethodsinitiative/dmi-tcat/commit/7b19524b3f0a5b7803e04bdd88ea0780b18cdc99).
