### ISSUE TITLE
Tracking keywords and language filter

### ISSUE THREAD

**Issue by kolakolak** [digitalmethodsinitiative/dmi-tcat#45]
Hello,
I've just started using DMI-TCAT and I'm not too familiar with it yet. I was wondering if it was possible to track keywords AND to filter on language ? I know it's easy to filter afterwards but my current queries capture way too many tweets. I'm not too sure as to where I should add the parameter ?
Sorry for the noob question, I'm still in the midst of understanding DMI-TCAT as a whole (I had a hard time finding where to fill in my proxy settings!).

**Comment by dormeir99o** [comment]
Hi @ErikBorra,
Just to make things clear: 
TCAT doesn't have and will not have an option to filter on language, 
although the Twitter's streaming API do allow it?

**Comment by dormeir99o** [comment]
@kolakolak do you know the answer maybe?

**Comment by ErikBorra** [comment]
Hi @dormeir99o,

according to https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters.html Setting [the language] parameter to a comma-separated list of BCP 47 language identifiers corresponding to any of the languages listed on Twitter’s advanced search page will only return Tweets that have been detected as being written in the specified languages. For example, connecting with language=en will only stream Tweets detected to be in the English language.

Modifying the following line https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/capture/common/functions.php#L2470 from 
```$params = array();```
to 
```$params = array("language"=>"en");```
should do the trick.

Change the language code to whatever you are using. Note that whenever you do this, all query bins for that server will track only tweets as being identified for that language.

Best,

Erik
