### ISSUE TITLE
Installation problem: TCAT Configuration Parameters loop

### ISSUE THREAD

**Issue by jmoralesigras** [digitalmethodsinitiative/dmi-tcat#455]
After doing the automatic installation of DMI-TCAT, both in Ubuntu 18.04 and Debian 9, and visiting the capture URL, it asks for configuration parameters.

The browser points at {ip}/capture/config_tcat.php, and there is no way to get rid of this message:
![tcat-config-error](https://user-images.githubusercontent.com/18099519/176973438-b16ec1b5-2092-44c1-ba86-3a43f1400e22.PNG)

Any help is appreciated. Thanks :)

**Comment by jmoralesigras** [comment]
Hi there.

Even after introducing the information, the bug persists.

Thanks.

El dl., 4 jul. 2022, 11.09, Dale Wahl ***@***.***> va
escriure:

**Comment by jmoralesigras** [comment]
> 

Hi there,

Just wanted to mention that this solution works fine :)

Thanks a lot!

**Comment by dale-wahl** [comment]
Oh thanks! I'm glad to hear it. I won't likely have time to dive into this until the end of the month. If it seems having access will help (and you are still using the server!), I'll let you know.

**Comment by dale-wahl** [comment]
Should be fixed via this [pull request](https://github.com/digitalmethodsinitiative/dmi-tcat/pull/454). Issue with automatic script install and docker install using same `config.php` file (docker `config.php` was updated for interactive settings and now is located `/docker/config.php-example`).
