### ISSUE TITLE
Search API Functionality

### ISSUE THREAD

**Issue by dpwoodford** [digitalmethodsinitiative/dmi-tcat#51]
It would be useful if DMI-TCAT could 'stream' (i.e. repeatedly search) via the Search API. In particular, this would be useful for use cases not supported under the streaming API, such as the tracking of specific URLs or part of URLs.

**Comment by ErikBorra** [comment]
bump

**Comment by limogin** [comment]
Are there any additional documentation resources to learn on how to do more types of queries with the application? Except this own project documentation I have not found any additional resources. I'm interested in being able to apply the types of queries that are listed in the FAQ. But I can not identify exactly how I can make them.

Thanks,

**Comment by ErikBorra** [comment]
Hi @limogin,

do you want to retrieve data via search (REST API) or track (streaming API) queries? Or do you want to query the already captured data?

Best,

Erik

**Comment by limogin** [comment]
Hi Erik, Yes, I want to track via the streaming API. It is said, defining the search into the ../capture/index.php panel 

Thanks,

Victor.

**Comment by ErikBorra** [comment]
Hi @limogin,

have you looked at https://dev.twitter.com/docs/streaming-apis/parameters#track?

Best,

Erik

**Comment by limogin** [comment]
Hi Erik, 

ok, thanks, view. 

But I can include in the query manager, in the phases to track a term as "@user" to follow the tweets of a user?. 

And I can obtain a relation of tweets by your id?. I don't find nothing related to this feature. 
I have set "track" in capture roles, but I should change this to "follow"? 
In the documentation I view 

_Choose a capture role. DMI-TCAT allows you to 'track' tweets based on a set of keywords, 'follow' users based on a set of user ids, or retrieve a 'one percent' sample from the Twitter API. As Twitter only allows you to connect to either one of them for any given IP address, and as most machines only have one IP address, you will have to choose either 'track', 'follow', or 'onepercent' and define that in CAPTUREROLES._

I can execute a php script selecting a ip address? 

Thanks for your attention, 

Victor.

**Comment by dentoir** [comment]
For historical reference, adding a @ in a tracking will make TCAT track mentions of those users, not tweets by those users. For this, you should configure TCAT (in config.php) to use the 'follow' role.

The capture/search/timeline.php CLI script can also be used to search for tweets by users.
