### ISSUE TITLE
Error Loading Analysis Page

### ISSUE THREAD

**Issue by mtrice** [digitalmethodsinitiative/dmi-tcat#68]
Hi,

So I have the capture tool running great with all four types, but the analysis page returns the error:

Error: Unable to set the character set.

I'm not sure why the character set issue is showing on the Analysis load when writing and reading DB works elsewhere..

**Comment by dyazbek-intersect** [comment]
I've got the exact same problem...

I've tried executing SET NAMES utf8mb4; and it returns OK however I still have the same error when loading the analysis page.

Perhaps it's an issue with the php mysql driver?
