### ISSUE TITLE
Ensure compatibility with PHP 7

### ISSUE THREAD

**Issue by ErikBorra** [digitalmethodsinitiative/dmi-tcat#7]
Currently not all mysql_queries are made via PDO_MySQL while this will be deprecated by PHP > 5.5.

**Comment by dentoir** [comment]
I've started a branch for PHP 7 development and testing. The first goal is getting installation and capture to function robustly. The auto-installer works for Ubuntu 16.04 now but does not enable/setup GEOS functions; basic capturing works now, but is not well-tested. The second goal is to get the analysis panel and function working through PDO.

https://github.com/digitalmethodsinitiative/dmi-tcat/tree/php7

There is a temporary document called PHP7_KNOWN_ISSUES.md in this branch, which tracks the current status. I'll let everyone know when it becomes sensible to start testing this.

**Comment by bornakke** [comment]
Brilliant!

**Comment by dentoir** [comment]
It looks like we're not the only project trying to catch up! As of yet, there is no GEO support for PHP 7, which means using it now breaks the possibility to query geographically with TCAT.

https://lists.debian.org/debian-gis/2016/03/msg00021.html

This issue is the relevant one for us (I thought I'll reference it externally to let them know we are looking forward.)

https://github.com/swig/swig/issues/571

Regardless we should move forward with the PHP7 work though.

**Comment by dentoir** [comment]
Status update! Full PHP 7 support has arrived in the branch:

https://github.com/digitalmethodsinitiative/dmi-tcat/tree/php7

This branch can be automerged with master, but deserves some serious testing first (on some different platforms, with different analysis modules and capture functions etc.).

I'd appreciate any feedback.

**Comment by bornakke** [comment]
We have shifted one of our instances to php7. So far without any errors :)

**Comment by dentoir** [comment]
During the DMI Winter School, I only encountered an error with the full tweet exports (not all field showed up when selecting extended export options such as media, or urls). We may wish to merge the PHP 7 branch soon.

**Comment by dentoir** [comment]
Good news. The PHP GEOS module is now functional on PHP 7. I've modified the autoinstaller in the PHP 7 branch to build/install the module. Feedback is welcome. To install the PHP 7 branch on a fresh server with the auto-installer, execute the following steps:

1. Clone dmi-tcat
2. Checkout php7 branch
3. Run the auto-installer with additional option -B php7

**Comment by holnburger** [comment]
Hey, I tried to install DMI-TCAT on a new Ubuntu 16.04 machine but with the auto-installer in the php7 branch I always get this error:

`./tcat-install-linux.sh: line 987: /etc/php/mods-available/geos.ini: No such file or directory`

The right path would be '/etc/php/7.0/mods-available/geos.ini'. 
Im a bit new to github, I don't know why I can't push my changes to the branch.

**Comment by dentoir** [comment]
Hi everyone,

The PHP 7 branch has now been merged into master. See our change log (https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Change-log)  for the specifics. It enumerates some issues which people could theoretically experience down the road. We've tested this upgrade on all our own servers, so we're pretty confident it should work well on most systems. I'm closing this issue now and if someone encounters a problem/bug with the new code, please open a new issue.
