### ISSUE TITLE
Upgrading database tables: Uncaught exception 'PDOException' with message 'SQLSTATE[42S21]: Column already exists

### ISSUE THREAD

**Issue by natoinet** [digitalmethodsinitiative/dmi-tcat#85]
Hello,

While running upgrade.php, I get a PDOException 'Column already exists' after a while:
```
2015-01-10 17:20:00     Executing global upgrade
2015-01-10 17:20:00     Adding new columns (ex. possibly_sensitive) to table 9n2014_tweets
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'from_user_withheld_scope'' in /var/www/dmi-tcat/common/upgrade.php:91
Stack trace:
#0 /var/www/dmi-tcat/common/upgrade.php(91): PDOStatement->execute()
#1 /var/www/dmi-tcat/common/upgrade.php(228): upgrades()
#2 {main}
thrown in /var/www/dmi-tcat/common/upgrade.php on line 91
```

A previous upgrade did not work out well since the ssh connection with the server broke down and stopped the upgrade process. Screen was not installed on the server, but I am now using nohup that is preinstalled and handy.

So, how can I resume the upgrade process without running into that exception again?

Best!

**Comment by dentoir** [comment]
Execute the following statements using your MySQL client (like phpmyadmin):

   ALTER TABLE 9n2014_tweets DROP from_user_created_at;
   ALTER TABLE 9n2014_tweets DROP from_user_withheld_scope;
   ALTER TABLE 9n2014_tweets DROP possibly_sensitive;
   ALTER TABLE 9n2014_tweets DROP withheld_copyright;
   ALTER TABLE 9n2014_tweets DROP withheld_scope;

Some of the statements will produce errors messages, this is okay.
After this, try to re-run the script.

**Comment by dentoir** [comment]
Closed (works)
