### ISSUE TITLE
using the user scripts

### ISSUE THREAD

**Issue by buethastum** [digitalmethodsinitiative/dmi-tcat#86]
Hi tcat people

I have a list of twitter users for each of whom I would like to get the latest 3200 tweets. Tcat's FAQ says it should be able to do this, however it doesn't seem to be documented yet. Having browsed a bit I assume that it's the timeline.php script I wanna use and that I need to run it from the command line. As I don't really know php I'm a but unsure of how to configure it properly (in spite of the comments in the file). Particularly how to format the array of user id's and screen names. I have quite a large amount of users (more than a thousand), I'd like to do this for. I don't know if that means it'd be easier to perhaps have them in a separate file?

If anyone would like to give a short introduction to what one needs to know and be aware to be able to set up and run this, It'd be greatly appreciated. 

Cheers, 
Bue

**Comment by buethastum** [comment]
I think I may have figured it out by doing some trial and error. What so far seems to be working was creating a following bin with the list of users I want to get the tweets from, putting the name of the bin as the value of the $bin_name variable on line 17, and running the script from the command line in a screen.

**Comment by buethastum** [comment]
however, the script keeps stopping before having gone through all of the users in the bin, meaning I have to keep starting it again (and it having to run through all the users it has already retrieved the tweets for)

**Comment by ErikBorra** [comment]
Hi @buethastum,

pardon the slow reply, we've been very busy with the [winter school](https://wiki.digitalmethods.net/Dmi/WinterSchool2015). 

Your approach of creating a following bin with the list of users is a good one. Alternatively, you can also just edit 'capture/user/timeline.php' add the list of ids or screennames (e.g. `$user_ids = array('user1','user2','user3');`) and specify a binname (e.g. `$bin_name = "myuserbin";`). TCAT will then create that bin for you, and make it available in the web interfaces once the script is done.

I have run this script for hundreds of users without a problem. What kind of messages do you get just before the script ends? 

Best,

Erik

btw: you don't have to redo all users who's timeline you are already captured, you can just remove those ids from the `$user_id` array.

**Comment by buethastum** [comment]
Hi @ErikBorra 

Thanks for your reply. 

I don't get any special messages when the script ends, it just says 'no more tweets found', as when moving on to the next user, except it stops and I'm back at the command line. When I check in the interface with an appropriate timeframe (the sample is based on users tweeting with a particular hashtag within a month, so I know they should all be there, when I set the timeframe to be that month), I can see that the amount of unique users is not the same as the amount I've put in the bin (at first it was only around half of them), and when I run the script again, it always retrieves tweets for some additional users, though it seems less and less each time. I've done this a bunch of times now, and I still haven't gotten all of them. 

Best,
Bue

**Comment by ErikBorra** [comment]
Hi Bue,

Each time the script is run new tweets should be retrieved for users which are already in the database. However, you are saying that tweets are added of users which were previously not yet in the database? Also, have you considered that some users might have changed their privacy settings?

Best,

Erik

**Comment by buethastum** [comment]
Hi again

When I run the script again it runs through the users already in the database, though generally it says '0 tweets found' and moves on to the next one until it gets to what I presume are users not already in the database from which it starts retrieving tweets from one at a time until it stops. I can see the amount of unique users in the same timeframe gets higher in the analysis interface every time I've run the script again. It can't be ruled out that some users changed their privacy settings, though it seems unlikely that around 600 users within a group of around 1300 changed it within a month. 

Best,
Bue

**Comment by ErikBorra** [comment]
That seems weird indeed :) Would you mind emailing me the list of users so that I can give it a shot?

**Comment by buethastum** [comment]
sure. Is it fine if I just send you the id's in the format that goes into the interface? (ie. one very long line of numbers separated by commas). Also, what's your email?

**Comment by ErikBorra** [comment]
format = good, mail = erik thingie digitalmethods.net

**Comment by ErikBorra** [comment]
Hi Bue,

I have run the script once and got info for 1206 users, which is 5 less than the full list of users you provided:
![screen shot 2015-01-22 at 09 33 25](https://cloud.githubusercontent.com/assets/927284/5852603/d0694c14-a219-11e4-977f-691fcaccfcdf.png)

This is how I did it:
* Open an ssh connection to the server and open a console in [screen](http://www.rackaid.com/blog/linux-screen-tutorial-and-how-to/).
* In `/var/www/dmi-tcat/config.php` I have entered 4 different API keys to the variable `$twitter_keys`. I have done this so that once the script reaches a rate limit for one key, it'll continue with the next.
* Then, edit `/var/www/dmi-tcat/capture/user/timeline.php` and add the full list of user ids to the array `$user_ids` (e.g. `$user_ids = array(517355521,587438083,332263886);`. Make sure to also specify a bin_name (e.g. `$bin_name = "buethastum";`). Then just save and close that file. 
* Run the script: `cd /var/www/dmi-tcat/capture/user/; php timeline.php` and wait until it finishes.

Maybe you can retry the same procedure on your server. Keep the `$user_ids` list, but specify a different (new) bin_name?

Best,

Erik

**Comment by buethastum** [comment]
Thank you. I think the key is to put the ids in the array in timeline.php rather than just have them in the bin. I just tried putting the ids of the missing users in the file and ran it again, and that seems to have made it retrieve tweets for all of them.

**Comment by ErikBorra** [comment]
Ok, great. I will update the FAQ to reflect the instructions in my previous content.
