### ISSUE TITLE
wrong cohashtag network extension

### ISSUE THREAD

**Issue by ocoromina** [digitalmethodsinitiative/dmi-tcat#87]
The cohashtag networks comes with a .gexf and seems it should be .gdf.  After changing the extension manually, different missing nodes are detected with gephi: 

![captura de pantalla 2015-01-23 a les 13 03 11](https://cloud.githubusercontent.com/assets/10669459/5874304/582d4466-a300-11e4-8207-7dfdcb1fa0b4.png)

At first, we thought it could be related to issue  https://github.com/digitalmethodsinitiative/dmi-tcat/issues/66

But we have checked that and our TCAT version contains the fix.

**Comment by dentoir** [comment]
I've tried reproducing this bug with several very large capture sets (using methods: follow user, or track keywords), but  I did not manage to do so yet.

Which method did you use to produce your dataset? I really would like to see a .gdf file where this problem occurs, ideally with a corresponding mysqldump of the relevant tables (at least _tweets and _hashtags). Would this be possible for you?

**Comment by ocoromina** [comment]
I think that the bug appears when you select and exclusion parameter. In my case I was trying to exclude retweets. Now the file comes with gdf extension but still with the issues when importing to gephi.

![captura de pantalla 2015-03-05 a les 11 41 33](https://cloud.githubusercontent.com/assets/10669459/6503382/b0506de8-c32c-11e4-8618-a4fecdc424d2.png)
![captura de pantalla 2015-03-05 a les 11 41 12](https://cloud.githubusercontent.com/assets/10669459/6503384/b41d346a-c32c-11e4-893a-334198c1b9fb.png)

**Comment by dentoir** [comment]
Thank you I will have a look

**Comment by ErikBorra** [comment]
This has to do with [collations](http://collation-charts.org/mysql60/mysql604.utf8_general_ci.european.html) mapping e.g. accented characters on those without accents. We'll release a bug fix today.

**Comment by dentoir** [comment]
@ocoromina could you review our changes by doing a git pull? It should have fixed this issue.

**Comment by ocoromina** [comment]
Thank you!

I will have a look tomorrow and give feedback.

**Comment by ocoromina** [comment]
Changes reviewed. Everything works perfect now.

Thank you very much!

**Comment by dentoir** [comment]
This commit introduced a regression. Querying parameters with capitals returned zero results. Last commit should have fixed the regression.
