### ISSUE TITLE
Try to delete some tweets with search.php

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#90]
Hi, im trying to delete some tweets, but when cron jobs execute "search.php" tweets deleted are stored back again, any idea how to delete permanently or hide?

**Comment by ErikBorra** [comment]
Usually we do not delete tweets, but filter them out through the query interface (i.e. make a subselection). 

If you really want to be able to delete tweets and not have the search script re-add deleted tweets, you can instruct the search script (search.php) to not insert tweets with an id smaller than the ones you retrieved last time. E.g. on line 42 of `capture/search/search.php` add the following:
```
$rec = mysql_query("SELECT MAX(id) AS max_id FROM " . quoteIdent($bin_name) . "_tweets");
if ($rec && mysql_num_rows($rec) > 0) {
    $res = mysql_fetch_assoc($rec);
    $max_id = $res['max_id'];
} else
    $max_id = 0;
```
Then, change `global $twitter_keys, $current_key, $ratefree, $all_users, $all_tweet_ids, $bin_name, $tweets_success, $tweets_failed, $tweets_processed, $dbh, $tweetQueue;` into `global $twitter_keys, $current_key, $ratefree, $all_users, $all_tweet_ids, $bin_name, $tweets_success, $tweets_failed, $tweets_processed, $dbh, $tweetQueue,$max_id;` and change 
```
if (!$t->isInBin($bin_name)) {
```
into
```
if (!$t->isInBin($bin_name) && t->id > $max_id) {
```
I have not tested it but it should work.

**Comment by psegovias** [comment]
I try it, and i made the chages, i got this:

php search.php

Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /home/xxx/public_html/dashboard/capture/search/search.php on line 104


Line 104:

            if (!$t->isInBin($bin_name) && t->id > $max_id) {

**Comment by psegovias** [comment]
I solved with:

if (!$t->isInBin($bin_name) && $t->id > $max_id) {

**Comment by psegovias** [comment]
Now i get this:


php search.php 

Warning: mysql_query(): Access denied for user 'xxx'@'localhost' (using password: NO) in /home/xxx/public_html/dashboard/capture/search/search.php on line 48

Warning: mysql_query(): A link to the server could not be established in /home/xxx/public_html/dashboard/capture/search/search.php on line 48
2015-02-19 11:03:17	key: 0	remaining requests:144
0 tweets found

Line 48:

$rec = mysql_query("SELECT MAX(id) AS max_id FROM " . quoteIdent($bin_name) . "_tweets");

**Comment by ErikBorra** [comment]
Try the following instead (also updated in the original comment):
```
$res = $dbh->query("SELECT MAX(id) AS max_id FROM " . quoteIdent($bin_name) . "_tweets");
if ($res->fetchColumn() > 0) {
   $max_id = $res['max_id];
} else
    $max_id = 0;
```

**Comment by psegovias** [comment]
Same error

**Comment by ErikBorra** [comment]
Also replace
```
global $twitter_keys, $current_key, $ratefree, $all_users, $all_tweet_ids, $bin_name, $tweets_success, $tweets_failed, $tweets_processed, $dbh, $tweetQueue,$max_id;
```
by
```
global $twitter_keys, $current_key, $ratefree, $all_users, $all_tweet_ids, $bin_name, $tweets_success, $tweets_failed, $tweets_processed, $dbh, $tweetQueue,$max_id,$dbh;
```

**Comment by psegovias** [comment]
I got this:


Parse error: syntax error, unexpected T_STRING, expecting ']' in /home/socialtrack/public_html/dashboard/capture/search/search.php on line 71


Line 71:

	$keyinfo = getRESTKey($current_key, 'search', 'tweets');

**Comment by ErikBorra** [comment]
Are your keys (in config.php) correct?

**Comment by psegovias** [comment]
Yes, im tracking another search.php with cron and no problem.

**Comment by ErikBorra** [comment]
Then I have no clue why it expects ']' on line 71 :p

**Comment by psegovias** [comment]
:cry:

**Comment by psegovias** [comment]
I delete only:

$res = $dbh->query("SELECT MAX(id) AS max_id FROM " . quoteIdent($bin_name) . "_tweets");
if ($res->fetchColumn() > 0) {
   $max_id = $res['max_id];
} else
    $max_id = 0;

And search.php work like normal.

**Comment by psegovias** [comment]
Ok, i have this now:

a " ' " miss in max_id did a change, now i got this:

php copa.php 

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'socialtr_dashboard2015.CopaAmerica2015' doesn't exist' in /home/xxx/public_html/dashboard/capture/search/copa.php:48
Stack trace:
#0 /home/xxx/public_html/dashboard/capture/search/copa.php(48): PDO->query('SELECT MAX(id) ...')
#1 {main}
  thrown in /home/xxx/public_html/dashboard/capture/search/copa.php on line 48

Any idea @ErikBorra ?

**Comment by psegovias** [comment]
miss the _tweets ??

**Comment by ErikBorra** [comment]
It's weird '_tweets' is not added, as it is in the select max(id) statement.
