### ISSUE TITLE
Problem with dataset

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#91]
I made a custom php file, to UPDATE some row on database, its based on form with values.

I require this files:

require_once '../config.php';
require_once 'common/config.php';
require_once 'common/functions.php';

and validate all variables with:
validate_all_variables();

The update its something like this:

$sql = "UPDATE " . $esc['mysql']['dataset'] . "_tweets SET value = '" . $_POST['value'] . "' WHERE `id` = " . $_GET['id'];
        $sqlresults = mysql_query($sql);   
        echo $sql;

And this is the problem, i cant get the correct dataset, any idea?

Regards!

**Comment by ErikBorra** [comment]
It seems you want to run the script from your browser. 
First, make sure to escape any user-input in the database. Easiest is to do `mysql_real_escape_string($_POST['value']);` and `mysql_real_escape_string($_GET['id']);`. Better would be to check the type and values of the user input (e.g. `if(preg_match("/^\d+$/",$_GET['id']) $id = $_GET['id']; else die('id should be an integer');`. 
Second, it seems you are mixing POST and GET parameters. Not bad per se, but not consistent either.
Third, make sure you have a GET parameter for dataset. I.e. make sure that in your URL you also have dataset=querybinname. To verify the parameters which are passed to your script via the browser,  put `var_dump($_REQUEST);` just before `validate_all_variables()`? There should be a parameter named `dataset`.
