### ISSUE TITLE
View Multiples bin?

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#93]
Hi guys, im triying to get this scenario:

One bin tracking "Love" and another bin tracking "hate" i can view separated, but how i can "merge" or visualize two differents bin on one analysis page?

Regards!

**Comment by ErikBorra** [comment]
If you know a bit of mysql you could create [views](http://dev.mysql.com/doc/refman/5.0/en/create-view.html) for each of the tables in your bins. E.g.
```
CREATE VIEW merge_love_hate_tweets AS SELECT * FROM love_tweets UNION SELECT * FROM hate_tweets;
CREATE VIEW merge_love_hate_hashtags AS SELECT * FROM love_hashtags UNION SELECT * FROM hate_hashtags;
CREATE VIEW merge_love_hate_mentions AS SELECT * FROM love_mentions UNION SELECT * FROM hate_mentions;
CREATE VIEW merge_love_hate_urls AS SELECT * FROM love_urls UNION SELECT * FROM hate_urls;
CREATE VIEW merge_love_hate_media AS SELECT * FROM love_media UNION SELECT * FROM hate_media;
```
Then, you'd have to reference that query bin in the tcat_* tables. E.g., if you want to merge two 'track' bins:
```
INSERT INTO tcat_query_bins (querybin, type, active, visible) VALUES ('merge_love_hate','track',1,1);
INSERT INTO tcat_query_bins_periods (querybin_id, starttime, endtime) VALUES (ID_OF_QUERY_BIN_JUST_CREATED, STARTTIME, ENDTIME); /* Note that you'll have to retrieve these values manually */
INSERT INTO tcat_query_bins_phrases (starttime, endtime,phrase_id,querybin_id) SELECT starttime, endtime, phrase_id, ID_OF_QUERY_BIN_JUST_CREATED FROM tcat_query_bins_phrases WHERE querybin_id IN (SELECT id FROM tcat_query_bins WHERE querybin = 'love' OR querybin = 'hate'); /* Note that you'll have to retrieve the querybin id of your new bin manually */
```
Haven't tested this though.

**Comment by psegovias** [comment]
Thanks @ErikBorra like always helping us :) i will try and let u know.

**Comment by ErikBorra** [comment]
Hi @psegovias, 

did this work for you?

Best,

Erik

**Comment by psegovias** [comment]
I will try this week. let u know.

**Comment by dstress** [comment]
I have done this on bins with overlapping timelines, to try and resolve a data hole in one bin: is there a simple way (maybe with views) to only bring in the tweets we need to fill the hole (time-period specific)?

**Comment by dstress** [comment]
I have implemented a solution, here's the SQL statements.

Scenario: 

We had been capturing DATAHOLE but had an unplanned capturing outage between a certain timeframe: we ran search.php scripts to re-do the analysis into PARTIAL but it didn't cover the required time period completely, but would fill the timeframe of the outage.  We used the advice of @ErikBorra to create the view POOLED to fill the hole. 

```sql
CREATE VIEW POOLED_tweets AS SELECT * FROM DATAHOLE_tweets UNION SELECT * FROM PARTIAL_tweets WHERE PARTIAL_tweets.`created_at` BETWEEN '2015-05-23 10:00:00' AND '2015-05-24 07:00:00';
CREATE VIEW POOLED_hashtags AS SELECT * FROM DATAHOLE_hashtags UNION SELECT * FROM PARTIAL_hashtags WHERE PARTIAL_hashtags.`created_at` BETWEEN '2015-05-23 10:00:00' AND '2015-05-24 07:00:00';
CREATE VIEW POOLED_mentions AS SELECT * FROM DATAHOLE_mentions UNION SELECT * FROM PARTIAL_mentions WHERE PARTIAL_mentions.`created_at` BETWEEN '2015-05-23 10:00:00' AND '2015-05-24 07:00:00';
CREATE VIEW POOLED_urls AS SELECT * FROM DATAHOLE_urls UNION SELECT * FROM PARTIAL_urls WHERE PARTIAL_urls.`created_at` BETWEEN '2015-05-23 10:00:00' AND '2015-05-24 07:00:00';
CREATE VIEW POOLED_media AS SELECT * FROM DATAHOLE_media UNION SELECT * FROM PARTIAL_media;
```

**Comment by ErikBorra** [comment]
Thanks @dstress for trying these combined views out. Note that with my latest commit you can also just run search.php on an existing (track) bin. It will only add tweets which aren't in the track bin yet.

**Comment by psegovias** [comment]
Well this work perfect! the only thing is when u try to export, its take a lonnnnng time, any idea how to get better performance?

**Comment by ErikBorra** [comment]
As different tables are joined, MySQL needs access to a lot of RAM / temp disk space to do so. Easiest fix would be to get more RAM and increase your settings for temp tables and sort operations in mysql conf (see installation instructions), so that MySQL does not need to swap memory all the time.
