### ISSUE TITLE
Support (already?) for MariaDB

### ISSUE THREAD

**Issue by joep1** [digitalmethodsinitiative/dmi-tcat#96]
Hey DMI-TCAT... Great tool but one issue that'd be fantastic... I want to use it with MariaDB (which has the geos support) because upgrading to MySQL 5.6 with my Deb is being a nightmare.

I'm pretty sure it should work fine with MariaDB but the log reports (as does the capture page) that "Your MySQL version is too old, please upgrade to at least MySQL 5.5.3 to use DMI-TCAT."

I actually have 5.5 on the computer, it's just that MariaDB got installed over the top.

If you could turn off this feature that stops it trying to run and logs then that'd be great (because it should just run fine with MariaDB?)... I'm guessing it checks for MySQL 5.5 or greater but when it doesn't find it (because MariaDB is there) it stops everything from starting... if you could just stop it doing this in the case of MariaDB 10.0.12 being present then I could use it and get the geo working.

I'm guessing there's a setting somewhere that can be over-ridden... but please forgive me if it isn't that simple.

**Comment by joep1** [comment]
I notice that it errors because utf8mb4 isn't supported which I guess means my MariaDB is too old. I'll report back on this one but perhaps it is my fault!

**Comment by joep1** [comment]
No, apparently it should be fine with utf8mb - therefore can people just remove the code that follows and use MariaDB? I think it'd be good to get DMI-TCAT onto MariaDB as it grows...

Is this the only code preventing it from running?:

if (dbserver_has_utf8mb4_support() == false) {
    logit(CAPTURE . ".error.log", "DMI-TCAT requires at least MySQL version 5.5.3 - please upgrade your server");
    exit();
}

**Comment by dentoir** [comment]
We haven't tested it on MariaDB yet, but it is supposed to be binary compatible. I've added a check for MySQL versions > 5, could you git pull and retry?

**Comment by joep1** [comment]
This time it produced an error in the terminal when I ran dmitcat_track.php which didn't happen before (before error was only in the log):

pi@raspberrypi /var/www/dmi-tcat/capture/stream $ sudo php dmitcat_track.php
PHP Warning:  mysql_connect(): Headers and client library minor version mismatch. Headers:50540 Library:100012 in /var/www/dmi-tcat/common/functions.php on line 5

That said, the script IS running and collection for a test term (not geo, just a text query).

Log says:

==> controller.log <==
2015-03-07 12:52:59	received instruction to execute 'reload' for script track
2015-03-07 12:52:59	received instruction to execute 'reload' for script track
2015-03-07 12:52:59	script track was not running - starting

==> track.error.log <==
)
2015-03-07 12:53:00	running php version 5.4.36-0+deb7u3 in mode cli with extensions Core,date,ereg,libxml,openssl,pcre,zlib,bcmath,bz2,calendar,ctype,dba,dom,hash,fileinfo,filter,ftp,gettext,SPL,iconv,json,mbstring,pcntl,apc,posix,Reflection,session,shmop,SimpleXML,soap,sockets,standard,exif,sysvmsg,sysvsem,sysvshm,tokenizer,wddx,xml,xmlreader,xmlwriter,zip,PDO,Phar,curl,gd,mcrypt,mysql,mysqli,pdo_mysql,mhash (ini file: /etc/php5/cli/php.ini)
2015-03-07 12:53:00	installing term signal handler for this script
2015-03-07 12:53:00	geoPHP needs the GEOS and its PHP extension (please download it at: http://trac.osgeo.org/geos/)
2015-03-07 12:53:00	geoPHP functions are not yet available, see documentation for instructions
2015-03-07 12:53:00	started script track with pid 3278
2015-03-07 12:53:00	connecting to API socket
2015-03-07 12:53:00	connecting - query array (
  'track' => 'amsterdam',
)

**Comment by joep1** [comment]
It's now running fine with MariaDB and no errors (but I am not sure what got rid of the errors).

Thanks :)

Yet to get geos working though due to trouble installing packages libgeos-c1 and phpapi-20131226 for php5-geos, but that's another story.

**Comment by joep1** [comment]
Hey, I have a more stable version of everything under Wheezy dist but using some Jessie packages (inc MariaDB) and I notice that now I get a depricated code error on trying to run dmitcat_track.php ... could the code be corrected for new mysql/mariadb?

pi@raspberrypi /var/www/html/dmi-tcat/capture/stream $ sudo php dmitcat_track.php
PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/html/dmi-tcat/common/functions.php on line 5

**Comment by joep1** [comment]
N.B. Track still seems to be running

**Comment by dentoir** [comment]
This warning is not related to MariaDB but to PHP. Its a warning about the future removal of some MySQL functions TCAT uses. These functions however still work on your OS. This issue is known in open issue #7. I think your configuration is correct.

**Comment by joep1** [comment]
Great, sorry for not realising and thanks for the quick correction/feedback. Keep up the great work on DMI-TCAT :)

**Comment by joep1** [comment]
N.B. Have successfully got DMI-TCAT working on a Rasp Pi B+ now, running Wheezy, but with MariaDB and php/geos through Jessie. Very happy! Took a longggg time though :D

**Comment by ErikBorra** [comment]
Congrats :) 

Did you install it on a model 2 Raspberry PI? Capturing should go fine on both models, analysis of (big) data sets might run into memory issues.

What took a long time? Figuring out how to do it, or actually installing all dependencies on the PI?

Best,

Erik

**Comment by joep1** [comment]
The dependencies is the big hurdle... specifically, geos was the big issue (getting DMI-TCAT to work without geo is fine, it's only when you want php5-geos and its dependence on higher mysql or MariaDB that the issues arose - Jessie debian isn't stable at all on the pi, only wheezy)... but after careful deliberation and going through all the updates/installs in a careful and logical order, it was working...

After taking an image of the SD card, and cleaning everything up, I am getting this error when I start controller.php, any ideas?:

pi@raspberrypi /var/www/html/dmi-tcat/capture/stream $ sudo php controller.php
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1932 Table 'twittercapture.tcat_controller_tasklist' doesn't exist in engine' in /var/www/html/dmi-tcat/capture/stream/controller.php:40
Stack trace:
#0 /var/www/html/dmi-tcat/capture/stream/controller.php(40): PDO->query('select task, in...')
#1 {main}
  thrown in /var/www/html/dmi-tcat/capture/stream/controller.php on line 40
