### ISSUE TITLE
Provide TSV export options

### ISSUE THREAD

**Issue by Snurb** [digitalmethodsinitiative/dmi-tcat#97]
Hi, 

It would be great if TCAT could support data export in tab-separated values (TSV) format. From what I've seen, you're already stripping tab and carriage return characters from all user-provided free text fields, so TSV format is the more straightforward and user-friendly format compared to CSV (since TCAT isn't stripping commas from text fields, which means they have to be enclosed in quotes, which creates further ripple effects in downstream processing of exported files).

Shouldn't be a major change, hopefully ?

Axel Bruns

**Comment by ErikBorra** [comment]
We'll have to streamline the way in which exports are generated. We'll try to get to it in March.

**Comment by dentoir** [comment]
This is now implemented in the latest version.
