### ISSUE TITLE
Add options to export full hashtag, @mention, and URL tables

### ISSUE THREAD

**Issue by Snurb** [digitalmethodsinitiative/dmi-tcat#98]
Hi,

we're using Tableau for most downstream analysis of the datasets gathered with TCAT. Tableau implements a relational database logic even when working with CSV data, allowing multiple CSVs to be joined with each other much in the way that you'd do it with a JOIN clause in SQL.

To take full advantage of this when working with TCAT datasets, it would be very useful to be able to export three additional tables as CSVs (or even better, TSVs ;-):

1. Hashtags: a CSV containing the tweet ID and the hashtag(s) contained in the tweet (with multiple rows for tweets containing multiple hashtags). This information already exists in the TCAT MySQL database, so it's simply a matter of adding an export function.

2. @mentions: a CSV containing the tweet ID, the username and ID of any user @mentioned in the tweet, and the type of @mention (@reply, retweet) represented by the @mention. Again, this should generate multiple rows if the same tweet @mentions multiple users. As before, the user information is already in the TCAT MySQL database and would only need an export function - identifying the type of @mention would require some further processing of the tweet to see whether the @mentioned username is preceded by one of the standard retweet markers (RT, MT, via, or a double quote ") or not. This could be done in the same procedure that's identifying @mentioned usernames, using a simple regex on the tweet text.

3. URLs: a CSV containing the tweet ID and the URL(s) contained in the tweet - again with multiple rows for tweets with multiple URLs. This is also already in the MySQL database.

Seeing as most of this information is already in the database, hopefully adding export functionality for it wouldn't be especially difficult. I know these can also be generated by connecting directly to the TCAT MySQL database, but this isn't a very sensible solution in practice for a number of reasons:

1. It would mean having to keep all datasets permanently in MySQL - not feasible for large datasets on servers with limited storage capacity.

2. Many of our end users (e.g. PhD students and staff with limited technical skills) wouldn't have the technical understanding to set up their MySQL connections to access the data.

3. Any end users would need access credentials to the MySQL database, which is especially problematic for cross-institutional research teams.

4. Direct export from MySQL means that none of the standard filtering mechanisms offered by the TCAT user interface (date limits, keyword filters, etc.) are easily available.

So, making such expert functionality available directly in the TCAT Web interface would be much preferable. It'd be great if this could be implemented.

(FWIW, as a stopgap I've written some helper scripts that process a full TCAT data export CSV to generate these additional CSVs after the fact. Here's a two-part blog post that outlines how I'm using these files in Tableau: http://mappingonlinepublics.net/2015/03/02/using-gawk-to-prepare-tcat-data-for-tableau-part-1/)

Many thanks in advance,

Axel Bruns

**Comment by ErikBorra** [comment]
This functionality is indeed not difficult to implement. We'll also try to work on this in March. 

As for 1.2, do you have a list of possible retweet markers? [Danah Boyd identified the following markers](http://www.danah.org/papers/TweetTweetRetweet.pdf): '‘RT: @’, ‘retweeting @’, ‘retweet @’, ‘(via @)’, ‘RT (via @)’, ‘thx @’, ‘HT @’, ‘r @’, and ‘♻ @’. ' Do you have anything to add to this list?

**Comment by Snurb** [comment]
Brilliant, thanks for this and the response to my other request.

On retweet markers, in my own work I generally recognise only the following:

RT @   (no colon after the "RT" - haven't seen the version with colon much at all)
MT @
via @
"@        (i.e. a plain double quote followed by the @ - this has been used by the Twitter Website itself at various points in time)

Some of the others may also be useful, though I wouldn't go as far as danah in considering all of these as retweets in the narrow sense - I've certainly seen "HT @" and "thx @" simply as a way of acknowledging someone, rather than as a real retweet. E.g. something like this:

   Oh, the CFP for IR16 closes tomorrow. Better get something in quick... (HT @ekborra)
   Oh, the CFP for IR16 closes tomorrow. Better get something in quick... (thx @ekborra)

For the same reason, "retweet @" and "retweeting @" might also be too ambiguous - it would incorrectly pick up something like:

  Oh no, he's retweeting @snurb_dot_info again...

BTW, if you're doing this via regex, just remember to include a \b or similar in front of the RT/MT/etc., too - I've learnt the hard way that a regex for "RT @" without the \b will pick up some false positives... ;-) For example,

  I support @davidcameron.

still matches "RT @"...

Axel

**Comment by dentoir** [comment]
Hello @Snurb, the latest commit should've implemented the feature request.
